<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(AtlasTargetFramework)</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Atlas.Tools.NetClientDemo</RootNamespace>
    <AssemblyName>Atlas.Tools.NetClientDemo</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atlas.Client\Atlas.Client.csproj" />
  </ItemGroup>

</Project>
