using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Atlas.Generators.Events;

[Generator(LanguageNames.CSharp)]
public sealed class EventGenerator : IIncrementalGenerator
{
    private const string EventHandlerAttributeFullName = "Atlas.Events.EventHandlerAttribute";
    private const string IEventListenerFullName = "Atlas.Events.IEventListener";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classesWithHandlers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cds &&
                    cds.Modifiers.Any(SyntaxKind.PartialKeyword),
                transform: static (ctx, ct) => ParseEventClass(ctx, ct))
            .Where(static m => m is not null)!;

        context.RegisterSourceOutput(
            classesWithHandlers.Collect(),
            static (spc, models) => Execute(spc, models!));
    }

    private static EventClassModel? ParseEventClass(
        GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
        if (classSymbol is null) return null;

        var handlers = new List<EventMethodModel>();

        foreach (var member in classSymbol.GetMembers())
        {
            if (member is not IMethodSymbol method) continue;

            var eventAttr = method.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == EventHandlerAttributeFullName);
            if (eventAttr is null) continue;

            var eventName = eventAttr.ConstructorArguments.Length > 0
                ? eventAttr.ConstructorArguments[0].Value?.ToString() ?? ""
                : "";

            if (string.IsNullOrEmpty(eventName)) continue;

            var handler = new EventMethodModel
            {
                MethodName = method.Name,
                EventName = eventName,
            };

            foreach (var param in method.Parameters)
            {
                var typeDisplay = param.Type.ToDisplayString();
                var isSupported = EventTypeHelper.TryGetReaderMethod(typeDisplay, out var readerMethod);
                handler.Parameters.Add(new EventParamModel
                {
                    ParamName = param.Name,
                    TypeFullName = typeDisplay,
                    ReaderMethod = readerMethod,
                    IsSupported = isSupported,
                });
            }

            handlers.Add(handler);
        }

        if (handlers.Count == 0) return null;

        bool implementsIEventListener = ImplementsInterface(classSymbol, IEventListenerFullName);

        return new EventClassModel
        {
            Namespace = classSymbol.ContainingNamespace.IsGlobalNamespace
                ? ""
                : classSymbol.ContainingNamespace.ToDisplayString(),
            ClassName = classSymbol.Name,
            ImplementsIEventListener = implementsIEventListener,
            Handlers = handlers,
        };
    }

    private static void Execute(
        SourceProductionContext spc,
        ImmutableArray<EventClassModel> models)
    {
        foreach (var model in models)
        {
            if (!model.ImplementsIEventListener)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    EventDiagnosticDescriptors.MissingEventListener,
                    Location.None, model.ClassName));
                continue;
            }

            bool hasUnsupported = false;
            foreach (var handler in model.Handlers)
            {
                foreach (var param in handler.Parameters)
                {
                    if (!param.IsSupported)
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(
                            EventDiagnosticDescriptors.UnsupportedParameterType,
                            Location.None, param.ParamName, handler.MethodName, param.TypeFullName));
                        hasUnsupported = true;
                    }
                }
            }

            if (hasUnsupported) continue;

            var source = EmitEventHandlerCode(model);
            spc.AddSource($"{model.ClassName}.Events.g.cs", source);
        }
    }

    private static string EmitEventHandlerCode(EventClassModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Events/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine("using Atlas.Events;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial class {model.ClassName}");
        sb.AppendLine("{");

        foreach (var handler in model.Handlers)
        {
            var handlerClassName = $"Handler_{handler.MethodName}";
            sb.AppendLine($"    private sealed class {handlerClassName} : IEventHandler");
            sb.AppendLine("    {");
            sb.AppendLine($"        private readonly {model.ClassName} _owner;");
            sb.AppendLine($"        public {handlerClassName}({model.ClassName} owner) => _owner = owner;");
            sb.AppendLine();
            sb.AppendLine("        public void Handle(ReadOnlySpan<byte> payload)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = new SpanReader(payload);");
            foreach (var param in handler.Parameters)
            {
                sb.AppendLine($"            var {param.ParamName} = r.{param.ReaderMethod}();");
            }
            var args = string.Join(", ", handler.Parameters.Select(p => p.ParamName));
            sb.AppendLine($"            _owner.{handler.MethodName}({args});");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // RegisterEventHandlers
        sb.AppendLine("    public void Atlas_RegisterEventHandlers(EventBus bus)");
        sb.AppendLine("    {");
        foreach (var handler in model.Handlers)
        {
            sb.AppendLine($"        bus.Subscribe(\"{handler.EventName}\", new Handler_{handler.MethodName}(this), this);");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // UnregisterEventHandlers
        sb.AppendLine("    public void Atlas_UnregisterEventHandlers(EventBus bus)");
        sb.AppendLine("    {");
        sb.AppendLine("        bus.UnsubscribeAll(this);");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool ImplementsInterface(INamedTypeSymbol symbol, string interfaceFullName)
    {
        return symbol.AllInterfaces.Any(i => i.ToDisplayString() == interfaceFullName);
    }
}

internal sealed class EventClassModel
{
    public string Namespace { get; set; } = "";
    public string ClassName { get; set; } = "";
    public bool ImplementsIEventListener { get; set; }
    public List<EventMethodModel> Handlers { get; set; } = new();
}

internal sealed class EventMethodModel
{
    public string MethodName { get; set; } = "";
    public string EventName { get; set; } = "";
    public List<EventParamModel> Parameters { get; } = new();
}

internal sealed class EventParamModel
{
    public string ParamName { get; set; } = "";
    public string TypeFullName { get; set; } = "";
    public string ReaderMethod { get; set; } = "";
    public bool IsSupported { get; set; }
}
