using System;
using Atlas.Client;

namespace Atlas.ClientSample;

[Atlas.Entity.Entity("Avatar")]
public partial class Avatar : ClientEntity
{
    // Generated by Atlas.Generators.Def from Avatar.def (client_methods):
    //   public partial void ShowDamage(int amount, uint attackerId);
    //   public partial void ShowHeal(int amount);

    public partial void ShowDamage(int amount, uint attackerId)
    {
        Console.WriteLine($"[Client] Avatar.ShowDamage(amount={amount}, attackerId={attackerId})");
    }

    public partial void ShowHeal(int amount)
    {
        Console.WriteLine($"[Client] Avatar.ShowHeal(amount={amount})");
    }
}
