using Atlas.Entity;
using Atlas.Serialization;
using Xunit;

namespace Atlas.Tests;

[Entity("ReplicationFrameEntity")]
public partial class ReplicationFrameEntity : CellServerEntity
{
    // Fields, properties, dirty tracking, audience masks, and
    // BuildAndConsumeReplicationFrame are generated by DefGenerator from
    // entity_defs/ReplicationFrameEntity.def. See DeltaSyncEmitter.
}

// Pool of four SpanWriters shared across a test — mirrors how the
// CellApp replication pump reuses buffers across all entities per tick
// rather than allocating per call. `Reset()` between calls rewinds
// without releasing the pooled buffer.
internal ref struct FrameBufferSet
{
    public SpanWriter OwnerSnapshot;
    public SpanWriter OtherSnapshot;
    public SpanWriter OwnerDelta;
    public SpanWriter OtherDelta;

    public static FrameBufferSet Rent()
    {
        return new FrameBufferSet
        {
            OwnerSnapshot = new SpanWriter(),
            OtherSnapshot = new SpanWriter(),
            OwnerDelta = new SpanWriter(),
            OtherDelta = new SpanWriter(),
        };
    }

    public void ResetAll()
    {
        OwnerSnapshot.Reset();
        OtherSnapshot.Reset();
        OwnerDelta.Reset();
        OtherDelta.Reset();
    }

    public void Dispose()
    {
        OwnerSnapshot.Dispose();
        OtherSnapshot.Dispose();
        OwnerDelta.Dispose();
        OtherDelta.Dispose();
    }
}

public class ReplicationFrameTests
{
    [Fact]
    public void NoDirtyState_ReturnsFalse()
    {
        var entity = new ReplicationFrameEntity();
        var buf = FrameBufferSet.Rent();
        try
        {
            bool has = entity.BuildAndConsumeReplicationFrame(
                ref buf.OwnerSnapshot, ref buf.OtherSnapshot,
                ref buf.OwnerDelta, ref buf.OtherDelta,
                out bool hasEvent, out bool hasVolatile);
            Assert.False(has);
            Assert.False(hasEvent);
            Assert.False(hasVolatile);
        }
        finally { buf.Dispose(); }
    }

    [Fact]
    public void DirtyOwnClient_OwnerDeltaNonEmpty_OtherDeltaEmpty()
    {
        var entity = new ReplicationFrameEntity();
        entity.Hp = 100;  // own_client scope → owner only

        var buf = FrameBufferSet.Rent();
        try
        {
            bool has = entity.BuildAndConsumeReplicationFrame(
                ref buf.OwnerSnapshot, ref buf.OtherSnapshot,
                ref buf.OwnerDelta, ref buf.OtherDelta,
                out bool hasEvent, out bool hasVolatile);
            Assert.True(has);
            Assert.True(hasEvent);
            Assert.False(hasVolatile);
            Assert.True(buf.OwnerDelta.WrittenSpan.Length > 1);
            AssertEmptyDelta(buf.OtherDelta.WrittenSpan);
        }
        finally { buf.Dispose(); }
    }

    [Fact]
    public void DirtyOtherClients_OtherDeltaNonEmpty_OwnerDeltaEmpty()
    {
        var entity = new ReplicationFrameEntity();
        entity.AnimState = 7;

        var buf = FrameBufferSet.Rent();
        try
        {
            bool has = entity.BuildAndConsumeReplicationFrame(
                ref buf.OwnerSnapshot, ref buf.OtherSnapshot,
                ref buf.OwnerDelta, ref buf.OtherDelta,
                out bool _, out bool _);
            Assert.True(has);
            Assert.True(buf.OtherDelta.WrittenSpan.Length > 1);
            AssertEmptyDelta(buf.OwnerDelta.WrittenSpan);
        }
        finally { buf.Dispose(); }
    }

    [Fact]
    public void DirtyAllClients_BothDeltasNonEmpty()
    {
        var entity = new ReplicationFrameEntity();
        entity.BuffCount = 3;

        var buf = FrameBufferSet.Rent();
        try
        {
            bool has = entity.BuildAndConsumeReplicationFrame(
                ref buf.OwnerSnapshot, ref buf.OtherSnapshot,
                ref buf.OwnerDelta, ref buf.OtherDelta,
                out bool _, out bool _);
            Assert.True(has);
            Assert.True(buf.OwnerDelta.WrittenSpan.Length > 1);
            Assert.True(buf.OtherDelta.WrittenSpan.Length > 1);
        }
        finally { buf.Dispose(); }
    }

    [Fact]
    public void DirtyCellPublicAndOwn_OnlyOwnerDelta_NeverOther()
    {
        // Privacy invariant: CellPublicAndOwn leaks to Owner only.
        var entity = new ReplicationFrameEntity();
        entity.PrivateFlag = 42;

        var buf = FrameBufferSet.Rent();
        try
        {
            bool has = entity.BuildAndConsumeReplicationFrame(
                ref buf.OwnerSnapshot, ref buf.OtherSnapshot,
                ref buf.OwnerDelta, ref buf.OtherDelta,
                out bool _, out bool _);
            Assert.True(has);
            Assert.True(buf.OwnerDelta.WrittenSpan.Length > 1);
            AssertEmptyDelta(buf.OtherDelta.WrittenSpan);
        }
        finally { buf.Dispose(); }
    }

    [Fact]
    public void ConsecutivePropertyChanges_HasEventFlagsSet()
    {
        // Seq allocation moved to the C++ runtime; codegen only emits
        // dirty-bit flags now. Every property mutation must surface
        // hasEvent==true on the next publish.
        var entity = new ReplicationFrameEntity();
        var buf = FrameBufferSet.Rent();
        try
        {
            for (int i = 0; i < 10; i++)
            {
                entity.Hp = i + 1;
                buf.ResetAll();
                bool has = entity.BuildAndConsumeReplicationFrame(
                    ref buf.OwnerSnapshot, ref buf.OtherSnapshot,
                    ref buf.OwnerDelta, ref buf.OtherDelta,
                    out bool hasEvent, out bool _);
                Assert.True(has);
                Assert.True(hasEvent);
            }
        }
        finally { buf.Dispose(); }
    }

    [Fact]
    public void VolatileDirty_SetsHasVolatileFlag_NotHasEvent()
    {
        var entity = new ReplicationFrameEntity();
        entity.MarkVolatileDirty();

        var buf = FrameBufferSet.Rent();
        try
        {
            bool has = entity.BuildAndConsumeReplicationFrame(
                ref buf.OwnerSnapshot, ref buf.OtherSnapshot,
                ref buf.OwnerDelta, ref buf.OtherDelta,
                out bool hasEvent, out bool hasVolatile);
            Assert.True(has);
            Assert.False(hasEvent);
            Assert.True(hasVolatile);
            // Event-stream buffers untouched (writer position stays 0).
            Assert.Equal(0, buf.OwnerSnapshot.WrittenSpan.Length);
            Assert.Equal(0, buf.OtherSnapshot.WrittenSpan.Length);
            Assert.Equal(0, buf.OwnerDelta.WrittenSpan.Length);
            Assert.Equal(0, buf.OtherDelta.WrittenSpan.Length);
        }
        finally { buf.Dispose(); }
    }

    [Fact]
    public void PropertyAndVolatileTogether_BothFlagsSet()
    {
        var entity = new ReplicationFrameEntity();
        entity.Hp = 50;
        entity.MarkVolatileDirty();

        var buf = FrameBufferSet.Rent();
        try
        {
            bool has = entity.BuildAndConsumeReplicationFrame(
                ref buf.OwnerSnapshot, ref buf.OtherSnapshot,
                ref buf.OwnerDelta, ref buf.OtherDelta,
                out bool hasEvent, out bool hasVolatile);
            Assert.True(has);
            Assert.True(hasEvent);
            Assert.True(hasVolatile);
        }
        finally { buf.Dispose(); }
    }

    [Fact]
    public void ConsumeClearsDirty_NextCallWithoutChangeReturnsFalse()
    {
        var entity = new ReplicationFrameEntity();
        entity.Hp = 1;

        var buf = FrameBufferSet.Rent();
        try
        {
            Assert.True(entity.BuildAndConsumeReplicationFrame(
                ref buf.OwnerSnapshot, ref buf.OtherSnapshot,
                ref buf.OwnerDelta, ref buf.OtherDelta,
                out bool _, out bool _));
            buf.ResetAll();
            Assert.False(entity.BuildAndConsumeReplicationFrame(
                ref buf.OwnerSnapshot, ref buf.OtherSnapshot,
                ref buf.OwnerDelta, ref buf.OtherDelta,
                out bool _, out bool _));
        }
        finally { buf.Dispose(); }
    }

    [Fact]
    public void SnapshotIncludesFullOwnerState_EvenWhenDeltaIsSmall()
    {
        var entity = new ReplicationFrameEntity();
        entity.Hp = 500;
        entity.BuffCount = 2;
        entity.PrivateFlag = 9;

        var buf = FrameBufferSet.Rent();
        try
        {
            bool has = entity.BuildAndConsumeReplicationFrame(
                ref buf.OwnerSnapshot, ref buf.OtherSnapshot,
                ref buf.OwnerDelta, ref buf.OtherDelta,
                out bool _, out bool _);
            Assert.True(has);
            // Owner snapshot carries hp + buffCount + privateFlag + baseLinked
            // (4 int32 = 16 bytes; animState is other_clients only so excluded).
            Assert.Equal(16, buf.OwnerSnapshot.WrittenSpan.Length);
            // Other snapshot carries buffCount + animState (2 int32 = 8 bytes).
            Assert.Equal(8, buf.OtherSnapshot.WrittenSpan.Length);
        }
        finally { buf.Dispose(); }
    }

    // Proves buffer reuse across entities: after Reset, a fresh
    // serialisation doesn't carry over stale bytes from the prior call
    // and the underlying pool buffer is not reallocated.
    [Fact]
    public void ResetLetsOneBufferServeMultipleEntities()
    {
        var a = new ReplicationFrameEntity();
        a.Hp = 10;
        var b = new ReplicationFrameEntity();
        b.BuffCount = 99;

        var buf = FrameBufferSet.Rent();
        try
        {
            // Entity A: own-only delta.
            Assert.True(a.BuildAndConsumeReplicationFrame(
                ref buf.OwnerSnapshot, ref buf.OtherSnapshot,
                ref buf.OwnerDelta, ref buf.OtherDelta,
                out bool _, out bool _));
            int a_owner_len = buf.OwnerDelta.WrittenSpan.Length;

            buf.ResetAll();

            // Entity B: all-clients delta, different shape. After Reset,
            // the owner_delta length MUST reflect B only.
            Assert.True(b.BuildAndConsumeReplicationFrame(
                ref buf.OwnerSnapshot, ref buf.OtherSnapshot,
                ref buf.OwnerDelta, ref buf.OtherDelta,
                out bool _, out bool _));
            int b_owner_len = buf.OwnerDelta.WrittenSpan.Length;

            // Both produce valid deltas; sizes may differ but both non-zero.
            Assert.True(a_owner_len > 1);
            Assert.True(b_owner_len > 1);
        }
        finally { buf.Dispose(); }
    }

    private static void AssertEmptyDelta(System.ReadOnlySpan<byte> delta)
    {
        Assert.True(delta.Length <= 1,
                    $"expected empty audience delta (≤1 byte), got {delta.Length} bytes");
        if (delta.Length == 1) Assert.Equal(0, delta[0]);
    }
}
