namespace Atlas.Generators.Interop;

/// <summary>
/// Holds the source text of the [NativeImport] attribute that is injected
/// into the consuming compilation via RegisterPostInitializationOutput.
/// </summary>
internal static class NativeImportAttributeSource
{
    public const string FullyQualifiedName = "Atlas.Interop.NativeImportAttribute";
    public const string HintName = "NativeImportAttribute.g.cs";

    public const string Source = @"// <auto-generated by Atlas.Generators.Interop />
#nullable enable

namespace Atlas.Interop
{
    /// <summary>
    /// Marks a <c>static partial</c> method for automatic P/Invoke generation.
    /// The generator emits a <c>[LibraryImport]</c> declaration and, for
    /// <c>ReadOnlySpan&lt;byte&gt;</c> or <c>string</c> parameters, a wrapper
    /// that converts to <c>byte*</c> + <c>int</c> via <c>fixed</c>.
    /// </summary>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Method,
        AllowMultiple = false,
        Inherited = false)]
    internal sealed class NativeImportAttribute : global::System.Attribute
    {
        /// <param name=""entryPoint"">
        /// The C++ export function name (e.g. <c>""atlas_log_message""</c>).
        /// </param>
        public NativeImportAttribute(string entryPoint)
        {
            EntryPoint = entryPoint;
        }

        /// <summary>C++ export function name.</summary>
        public string EntryPoint { get; }

        /// <summary>
        /// Shared library name for <c>[LibraryImport]</c>.
        /// Default: <c>""atlas_engine""</c>.
        /// </summary>
        public string LibraryName { get; set; } = ""atlas_engine"";
    }
}
";
}
