"""Repository rule to auto-detect the .NET host (nethost) SDK path.

Probes DOTNET_ROOT, standard install locations, and `dotnet --info` to find
the nethost headers and libraries required by atlas_clrscript.
"""

def _find_dotnet_root(ctx):
    """Return the .NET SDK root directory, or fail with a helpful message."""

    # 1. Explicit environment variable (highest priority)
    dotnet_root = ctx.os.environ.get("DOTNET_ROOT", "")
    if dotnet_root:
        return dotnet_root

    # 2. Probe `dotnet --info` to find the install path
    dotnet_cmd = "dotnet"
    if ctx.os.name.startswith("windows"):
        dotnet_cmd = "dotnet.exe"

    result = ctx.execute([dotnet_cmd, "--list-runtimes"], timeout = 10)
    if result.return_code == 0:
        # `dotnet` is on PATH — derive root from its location
        which_result = ctx.execute(["where", dotnet_cmd] if ctx.os.name.startswith("windows") else ["which", dotnet_cmd], timeout = 5)
        if which_result.return_code == 0:
            dotnet_path = which_result.stdout.strip().split("\n")[0].strip()
            # dotnet binary is at <root>/dotnet[.exe]
            root = ""
            if ctx.os.name.startswith("windows"):
                # Normalize backslashes
                dotnet_path = dotnet_path.replace("\\", "/")
                idx = dotnet_path.rfind("/")
                if idx > 0:
                    root = dotnet_path[:idx]
            else:
                idx = dotnet_path.rfind("/")
                if idx > 0:
                    root = dotnet_path[:idx]

            if root:
                return root

    # 3. Well-known default paths
    if ctx.os.name.startswith("windows"):
        candidates = [
            "C:/Program Files/dotnet",
        ]
    else:
        candidates = [
            "/usr/share/dotnet",
            "/usr/lib/dotnet",
            "/usr/local/share/dotnet",
        ]

    for c in candidates:
        if ctx.path(c).exists:
            return c

    fail(
        "Could not locate .NET SDK. Please set the DOTNET_ROOT environment " +
        "variable to your .NET installation directory " +
        "(e.g., 'C:/Program Files/dotnet' or '/usr/share/dotnet').",
    )

def _find_host_pack(ctx, dotnet_root):
    """Find the nethost native pack directory for the current platform.

    Searches for the highest-versioned Microsoft.NETCore.App.Host pack
    that contains the required headers (nethost.h, hostfxr.h, coreclr_delegates.h).
    """

    if ctx.os.name.startswith("windows"):
        rid = "win-x64"
    elif ctx.os.name == "linux":
        rid = "linux-x64"
    elif ctx.os.name == "mac os x":
        # Detect ARM vs Intel
        arch_result = ctx.execute(["uname", "-m"], timeout = 5)
        if arch_result.return_code == 0 and "arm64" in arch_result.stdout:
            rid = "osx-arm64"
        else:
            rid = "osx-x64"
    else:
        fail("Unsupported OS: " + ctx.os.name)

    packs_dir = dotnet_root + "/packs/Microsoft.NETCore.App.Host." + rid

    if not ctx.path(packs_dir).exists:
        fail(
            "Cannot find .NET host pack at: {}\n".format(packs_dir) +
            "Ensure .NET SDK is installed. " +
            "Run 'dotnet --list-runtimes' to verify.",
        )

    # List version directories and pick the latest
    # We need a version that has the native headers
    ls_result = ctx.execute(
        ["cmd", "/c", "dir", "/b", "/o-n", packs_dir.replace("/", "\\")] if ctx.os.name.startswith("windows") else ["ls", "-1v", packs_dir],
        timeout = 5,
    )

    if ls_result.return_code != 0:
        fail("Cannot list .NET host pack versions at: " + packs_dir)

    versions = [v.strip() for v in ls_result.stdout.strip().split("\n") if v.strip()]

    if not versions:
        fail("No .NET host pack versions found at: " + packs_dir)

    # On Windows `dir /o-n` sorts descending, on Linux `ls -1v` sorts ascending
    if not ctx.os.name.startswith("windows"):
        versions = list(reversed(versions))

    for version in versions:
        native_dir = packs_dir + "/" + version + "/runtimes/" + rid + "/native"
        nethost_h = ctx.path(native_dir + "/nethost.h")
        if nethost_h.exists:
            return native_dir, version, rid

    fail(
        "Found .NET host pack at {} but none of the installed versions ".format(packs_dir) +
        "contain the required native headers (nethost.h). " +
        "Versions found: " + ", ".join(versions),
    )

def _dotnet_host_repo_impl(ctx):
    native_dir, version, rid = _find_host_pack(ctx, _find_dotnet_root(ctx))

    is_windows = ctx.os.name.startswith("windows")

    # Symlink the native directory contents into this repo
    ctx.symlink(native_dir, "native")

    # Generate a BUILD file with the appropriate cc_import + cc_library
    if is_windows:
        build_content = """\
# AUTO-GENERATED by dotnet_host_repo — do not edit
# Detected .NET host pack: {version} ({rid})

cc_import(
    name = "dotnet_nethost_import",
    interface_library = "native/nethost.lib",
    shared_library = "native/nethost.dll",
)

cc_library(
    name = "dotnet_nethost",
    hdrs = [
        "native/coreclr_delegates.h",
        "native/hostfxr.h",
        "native/nethost.h",
    ],
    includes = ["native"],
    visibility = ["//visibility:public"],
    deps = [":dotnet_nethost_import"],
)
""".format(version = version, rid = rid)
    else:
        build_content = """\
# AUTO-GENERATED by dotnet_host_repo — do not edit
# Detected .NET host pack: {version} ({rid})

cc_import(
    name = "dotnet_nethost_import",
    shared_library = "native/libnethost.so",
)

cc_library(
    name = "dotnet_nethost",
    hdrs = [
        "native/coreclr_delegates.h",
        "native/hostfxr.h",
        "native/nethost.h",
    ],
    includes = ["native"],
    visibility = ["//visibility:public"],
    deps = [":dotnet_nethost_import"],
)
""".format(version = version, rid = rid)

    ctx.file("BUILD.bazel", build_content)

dotnet_host_repo = repository_rule(
    implementation = _dotnet_host_repo_impl,
    environ = ["DOTNET_ROOT", "PATH"],
    doc = "Auto-detects the .NET SDK installation and exposes nethost headers/libraries.",
)
