using System;
using Atlas.Serialization;

namespace Atlas.Client;

/// <summary>
/// Base class for client-side entities. Game scripts derive from this
/// and implement partial methods generated by Atlas.Generators.Def.
/// </summary>
public abstract class ClientEntity
{
    public uint EntityId { get; internal set; }
    public bool IsDestroyed { get; internal set; }

    public abstract string TypeName { get; }

    /// <summary>Called when the entity is created on the client.</summary>
    protected internal virtual void OnInit() { }

    /// <summary>Called when the entity is destroyed on the client.</summary>
    protected internal virtual void OnDestroy() { }

    // =========================================================================
    // RPC send infrastructure — for sending exposed RPCs to the server.
    // Client has no SendClientRpc (can't send client methods to itself).
    // =========================================================================

    protected internal void SendCellRpc(int rpcId, ReadOnlySpan<byte> payload)
    {
        ClientNativeApi.SendCellRpc(EntityId, (uint)rpcId, payload);
    }

    protected internal void SendBaseRpc(int rpcId, ReadOnlySpan<byte> payload)
    {
        ClientNativeApi.SendBaseRpc(EntityId, (uint)rpcId, payload);
    }
}
