using System;
using Atlas.DataTypes;
using Atlas.Serialization;

namespace Atlas.Client;

/// <summary>
/// Base class for client-side entities. Game scripts derive from this
/// and implement partial methods generated by Atlas.Generators.Def.
/// </summary>
public abstract class ClientEntity
{
    public uint EntityId { get; internal set; }
    public bool IsDestroyed { get; internal set; }

    // Set when an Apply* path threw mid-delivery and left backing fields
    // in an indeterminate state. ClientEntityManager skips subsequent
    // applies on a corrupted entity — a fresh enter (server-side Leave
    // then Enter) is required to reset the state. Use this flag from
    // scripts to suppress UI reads on the entity until it heals.
    public bool IsCorrupted { get; internal set; }

    public abstract string TypeName { get; }

    // event_seq gap observability. The server stamps every
    // kEntityPropertyUpdate envelope with its originating frame's event_seq
    // (see witness.cc::BuildPropertyUpdatePayload). The client records the
    // most recent seq observed; when the next delta's seq jumps by more
    // than 1, the skipped count lands in EventSeqGapsTotal and a line hits
    // Console.Error so world_stress's tap can aggregate gap counts across
    // a script-child fleet.
    public ulong LastEventSeq { get; private set; }
    public ulong EventSeqGapsTotal { get; private set; }

    // Transform state — replicated via the volatile position channel
    // (0xF001 / kEntityPositionUpdate), separate from the replicated
    // property channel. Read freely from script; writes go through
    // ApplyPositionUpdate so the script hook fires consistently.
    public Vector3 Position { get; private set; }
    public Vector3 Direction { get; private set; }
    public bool OnGround { get; private set; }

    /// <summary>Restores entity state received from the server (implemented by source generator).</summary>
    public virtual void Deserialize(ref SpanReader reader) { }

    /// <summary>
    /// Apply an owner-scope snapshot (fields visible to the entity's owning
    /// client: <c>OwnClient</c>, <c>AllClients</c>, <c>CellPublicAndOwn</c>,
    /// <c>BaseAndClient</c>). Paired with the server's
    /// <c>SerializeForOwnerClient</c>. Used by the baseline channel
    /// (<c>0xF002</c>) for the local player's own entity. Writes directly
    /// to backing fields — does NOT fire <c>OnXxxChanged</c> because a
    /// snapshot is an authoritative state reset, not an observed change.
    /// </summary>
    public virtual void ApplyOwnerSnapshot(ref SpanReader reader) { }

    /// <summary>
    /// Apply an other-scope snapshot (fields visible to non-owner
    /// observers: <c>AllClients</c>, <c>OtherClients</c>). Paired with the
    /// server's <c>SerializeForOtherClients</c>. Used by the AoI enter
    /// envelope (<c>kEntityEnter</c>) when a peer joins the local player's
    /// view. Same direct-write semantics as <see cref="ApplyOwnerSnapshot"/>.
    /// </summary>
    public virtual void ApplyOtherSnapshot(ref SpanReader reader) { }

    /// <summary>
    /// Apply an incremental property delta as produced by the server's
    /// <c>SerializeOwnerDelta</c> / <c>SerializeOtherDelta</c>. The wire
    /// body is a dirty-flag bitmap followed by the changed field values;
    /// the generator overrides this per entity, and the base no-op keeps
    /// the dispatcher valid for entities with no replicable properties.
    /// </summary>
    public virtual void ApplyReplicatedDelta(ref SpanReader reader) { }

    /// <summary>
    /// Apply a volatile position/orientation update from the AoI volatile
    /// channel (<c>kEntityPositionUpdate</c> envelope). Writes the three
    /// transform fields and fires <see cref="OnPositionUpdated"/>.
    /// Virtual so a future per-entity generator override (movement filter,
    /// interpolation target, etc.) can replace the straight write.
    /// </summary>
    public virtual void ApplyPositionUpdate(Vector3 pos, Vector3 dir, bool onGround)
    {
        Position = pos;
        Direction = dir;
        OnGround = onGround;
        OnPositionUpdated(pos);
    }

    /// <summary>
    /// Script hook called after every volatile position update.
    /// Deliberately distinct from the property-change callback chain
    /// (<c>OnXxxChanged</c>): position arrives through its own high-
    /// frequency channel and routing it through the per-field callback
    /// path would muddle semantics and inflate dispatch cost.
    /// </summary>
    protected internal virtual void OnPositionUpdated(Vector3 newPos) { }

    /// <summary>
    /// Called by the manager whenever an incoming kEntityPropertyUpdate
    /// envelope's event_seq prefix has been decoded — before the delta body
    /// is applied. Counts and logs gaps; internal so scripts can't desync
    /// the counter by calling it ad-hoc.
    /// </summary>
    internal void NoteIncomingEventSeq(ulong seq)
    {
        // Reliable delta is ordered so seq should only ever move forward.
        // Out-of-order / duplicate deliveries (possible if a snapshot
        // fallback re-stamps a smaller seq than an already-seen one) are
        // silently dropped from gap tracking to avoid underflow noise.
        if (seq <= LastEventSeq) return;

        if (LastEventSeq > 0 && seq > LastEventSeq + 1)
        {
            ulong missed = seq - LastEventSeq - 1;
            EventSeqGapsTotal += missed;
            ClientLog.Warn(
                $"[{TypeName}:{EntityId}] event_seq gap: last={LastEventSeq} got={seq} missed={missed}");
            // Relay to server so BaseApp's baseapp/client_event_seq_gaps_total
            // watcher sees aggregate gap pressure across the fleet. Clamp the
            // per-report delta at uint32 max — a single jump larger than 4 G
            // is already a disaster worth paging on, not silently dropping.
            uint reportDelta = missed > uint.MaxValue ? uint.MaxValue : (uint)missed;
            ClientHost.ReportEventSeqGap(EntityId, reportDelta);
        }
        LastEventSeq = seq;
    }

    /// <summary>Called when the entity is created on the client.</summary>
    protected internal virtual void OnInit() { }

    /// <summary>
    /// Called once after the entity has been fully initialised into the
    /// local player's world — factory creation, initial transform, and
    /// the other-scope snapshot from the AoI <c>kEntityEnter</c> envelope
    /// have all been applied. Scripts override this for setup that needs
    /// the complete starting state (attach visuals, register timers, etc.).
    /// Distinct from <see cref="OnInit"/>, which fires on the bare
    /// instance before any server state is consumed.
    /// </summary>
    protected internal virtual void OnEnterWorld() { }

    /// <summary>Called when the entity is destroyed on the client.</summary>
    protected internal virtual void OnDestroy() { }

    // =========================================================================
    // RPC send infrastructure — for sending exposed RPCs to the server.
    // Client has no SendClientRpc (can't send client methods to itself).
    // =========================================================================

    protected internal void SendCellRpc(int rpcId, ReadOnlySpan<byte> payload)
    {
        ClientHost.SendCellRpc(EntityId, (uint)rpcId, payload);
    }

    protected internal void SendBaseRpc(int rpcId, ReadOnlySpan<byte> payload)
    {
        ClientHost.SendBaseRpc(EntityId, (uint)rpcId, payload);
    }
}
