using Atlas.Entity;

namespace Atlas.BaseSample;

[Entity("Avatar")]
public partial class Avatar : ServerEntity
{
    // Generated by Atlas.Generators.Def from Avatar.def (base_methods, exposed):
    //   public partial void UseItem(int itemId);

    public partial void UseItem(int itemId)
    {
        Log.Info($"[Base] Avatar.UseItem(itemId={itemId}) on entity {EntityId}");

        // Respond to the client with a ClientRpc
        Client.ShowDamage(itemId * 10, EntityId);
    }

    // Generated: public partial void OnPlayerDead();
    public partial void OnPlayerDead()
    {
        Log.Info($"[Base] Avatar.OnPlayerDead on entity {EntityId}");
    }
}
