using System.Linq;
using System.Text;
using Atlas.Generators.Entity.Model;

namespace Atlas.Generators.Entity.Emitters;

/// <summary>
/// Generates scope-filtered delta sync methods for client replication.
/// Owner client receives OwnClient+AllClients fields; other clients receive AllClients only.
/// </summary>
internal static class DeltaSyncEmitter
{
    public static string? Emit(EntityModel model)
    {
        var replicatedFields = model.Fields
            .Where(f => f.IsReplicated && f.IsSupportedType)
            .ToList();

        if (replicatedFields.Count == 0) return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Entity/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial class {model.ClassName}");
        sb.AppendLine("{");

        // Scope constants — matches Atlas.Entity.ReplicationScope enum:
        //   CellPrivate=0, BaseOnly=1, OwnClient=2, AllClients=3
        // Note: C++ entity_type_descriptor.hpp has an extended 8-value enum (OtherClients,
        // CellPublicAndOwn, Base, BaseAndClient). When .def-based definitions are adopted,
        // this filtering must be updated to use explicit scope matching instead of >=.
        sb.AppendLine("    // ReplicationScope: CellPrivate=0, BaseOnly=1, OwnClient=2, AllClients=3");
        sb.AppendLine();

        // SerializeForOwnerClient: OwnClient (2) + AllClients (3) fields
        // With the current 4-value C# enum, >= 2 correctly selects {OwnClient, AllClients}.
        // If the enum is extended to match C++ (8 values), change to explicit matching:
        //   scope == OwnClient || scope == AllClients || scope == CellPublicAndOwn || scope == BaseAndClient
        var ownerFields = replicatedFields.Where(f => f.ReplicationScope >= 2).ToList();
        sb.AppendLine("    public void SerializeForOwnerClient(ref SpanWriter writer)");
        sb.AppendLine("    {");
        foreach (var field in ownerFields)
        {
            sb.AppendLine($"        writer.{field.WriterMethod}({field.FieldName});");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // SerializeForOtherClients: AllClients (3) fields only
        // With the current 4-value C# enum, >= 3 correctly selects {AllClients}.
        // If extended to 8 values, change to: scope == OtherClients || scope == AllClients
        var otherFields = replicatedFields.Where(f => f.ReplicationScope >= 3).ToList();
        sb.AppendLine("    public void SerializeForOtherClients(ref SpanWriter writer)");
        sb.AppendLine("    {");
        foreach (var field in otherFields)
        {
            sb.AppendLine($"        writer.{field.WriterMethod}({field.FieldName});");
        }
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }
}
