using System.Linq;
using System.Text;
using Atlas.Generators.Entity.Model;

namespace Atlas.Generators.Entity.Emitters;

/// <summary>
/// Generates scope-filtered delta sync methods for client replication.
/// Owner client receives OwnClient+AllClients fields; other clients receive AllClients only.
/// </summary>
internal static class DeltaSyncEmitter
{
    public static string? Emit(EntityModel model)
    {
        var replicatedFields = model.Fields
            .Where(f => f.IsReplicated && f.IsSupportedType)
            .ToList();

        if (replicatedFields.Count == 0) return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Entity/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial class {model.ClassName}");
        sb.AppendLine("{");

        // Scope constants for readability
        sb.AppendLine("    // ReplicationScope: CellPrivate=0, BaseOnly=1, OwnClient=2, AllClients=3");
        sb.AppendLine();

        // SerializeForOwnerClient: OwnClient (2) + AllClients (3) fields
        var ownerFields = replicatedFields.Where(f => f.ReplicationScope >= 2).ToList();
        sb.AppendLine("    public void SerializeForOwnerClient(ref SpanWriter writer)");
        sb.AppendLine("    {");
        foreach (var field in ownerFields)
        {
            sb.AppendLine($"        writer.{field.WriterMethod}({field.FieldName});");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // SerializeForOtherClients: AllClients (3) fields only
        var otherFields = replicatedFields.Where(f => f.ReplicationScope >= 3).ToList();
        sb.AppendLine("    public void SerializeForOtherClients(ref SpanWriter writer)");
        sb.AppendLine("    {");
        foreach (var field in otherFields)
        {
            sb.AppendLine($"        writer.{field.WriterMethod}({field.FieldName});");
        }
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }
}
