using System.Collections.Generic;
using System.Linq;
using System.Text;
using Atlas.Generators.Entity.Model;

namespace Atlas.Generators.Entity.Emitters;

internal static class DirtyTrackingEmitter
{
    public static string Emit(EntityModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Entity/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial class {model.ClassName}");
        sb.AppendLine("{");

        var replicatedFields = model.Fields.Where(f => f.IsReplicated && f.IsSupportedType).ToList();

        if (replicatedFields.Count > 0)
        {
            EmitDirtyFlagsEnum(sb, replicatedFields);
            sb.AppendLine();
            sb.AppendLine("    private ReplicatedDirtyFlags _dirtyFlags;");
            sb.AppendLine();
        }

        foreach (var field in model.Fields)
        {
            if (!field.IsSupportedType) continue;
            EmitProperty(sb, field, replicatedFields.Contains(field));
            sb.AppendLine();
        }

        if (replicatedFields.Count > 0)
        {
            sb.AppendLine("    public bool IsDirty => _dirtyFlags != ReplicatedDirtyFlags.None;");
            sb.AppendLine();
            EmitSerializeReplicatedDelta(sb, replicatedFields);
            sb.AppendLine();
            EmitApplyReplicatedDelta(sb, replicatedFields);
            sb.AppendLine();
            sb.AppendLine("    public void ClearDirty() => _dirtyFlags = ReplicatedDirtyFlags.None;");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static (string backingType, string flagSuffix, string writerMethod, string readerMethod, string castPrefix) GetFlagsTypeInfo(int fieldCount)
    {
        if (fieldCount <= 8) return ("byte", "u", "WriteByte", "ReadByte", "(byte)");
        if (fieldCount <= 16) return ("ushort", "u", "WriteUInt16", "ReadUInt16", "(ushort)");
        if (fieldCount <= 32) return ("uint", "u", "WriteUInt32", "ReadUInt32", "(uint)");
        return ("ulong", "UL", "WriteUInt64", "ReadUInt64", "(ulong)");
    }

    private static void EmitDirtyFlagsEnum(StringBuilder sb, List<FieldModel> replicatedFields)
    {
        var (backingType, flagSuffix, _, _, _) = GetFlagsTypeInfo(replicatedFields.Count);
        sb.AppendLine("    [Flags]");
        sb.AppendLine($"    private enum ReplicatedDirtyFlags : {backingType}");
        sb.AppendLine("    {");
        sb.AppendLine("        None = 0,");
        for (int i = 0; i < replicatedFields.Count; i++)
        {
            var comma = i < replicatedFields.Count - 1 ? "," : "";
            sb.AppendLine($"        {replicatedFields[i].PropertyName} = 1{flagSuffix} << {i}{comma}");
        }
        sb.AppendLine("    }");
    }

    private static void EmitProperty(StringBuilder sb, FieldModel field, bool withDirtyTracking)
    {
        sb.AppendLine($"    public {field.TypeFullName} {field.PropertyName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        get => {field.FieldName};");

        if (withDirtyTracking)
        {
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine($"            if ({field.FieldName} != value)");
            sb.AppendLine("            {");
            sb.AppendLine($"                {field.FieldName} = value;");
            sb.AppendLine($"                _dirtyFlags |= ReplicatedDirtyFlags.{field.PropertyName};");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine($"        set => {field.FieldName} = value;");
        }

        sb.AppendLine("    }");
    }

    private static void EmitSerializeReplicatedDelta(StringBuilder sb, List<FieldModel> fields)
    {
        var (_, _, writerMethod, _, castPrefix) = GetFlagsTypeInfo(fields.Count);
        sb.AppendLine("    public void SerializeReplicatedDelta(ref SpanWriter writer)");
        sb.AppendLine("    {");
        sb.AppendLine($"        writer.{writerMethod}({castPrefix}_dirtyFlags);");
        foreach (var field in fields)
        {
            sb.AppendLine($"        if ((_dirtyFlags & ReplicatedDirtyFlags.{field.PropertyName}) != 0)");
            sb.AppendLine($"            writer.{field.WriterMethod}({field.FieldName});");
        }
        sb.AppendLine("    }");
    }

    private static void EmitApplyReplicatedDelta(StringBuilder sb, List<FieldModel> fields)
    {
        var (_, _, _, readerMethod, _) = GetFlagsTypeInfo(fields.Count);
        sb.AppendLine("    public void ApplyReplicatedDelta(ref SpanReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var flags = (ReplicatedDirtyFlags)reader.{readerMethod}();");
        foreach (var field in fields)
        {
            sb.AppendLine($"        if ((flags & ReplicatedDirtyFlags.{field.PropertyName}) != 0)");
            sb.AppendLine($"            {field.FieldName} = reader.{field.ReaderMethod}();");
        }
        sb.AppendLine("    }");
    }
}
