using System.Collections.Generic;
using System.Text;
using Atlas.Generators.Entity.Model;

namespace Atlas.Generators.Entity.Emitters;

internal static class FactoryEmitter
{
    public static string Emit(List<EntityModel> entities)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Entity/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Atlas.Entity;");
        sb.AppendLine();

        sb.AppendLine("namespace Atlas.Entity;");
        sb.AppendLine();

        sb.AppendLine("public static partial class EntityFactory");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Dictionary<string, Func<ServerEntity>> _creators");
        sb.AppendLine("        = new(StringComparer.Ordinal);");
        sb.AppendLine();
        sb.AppendLine("    static EntityFactory()");
        sb.AppendLine("    {");
        foreach (var e in entities)
        {
            var fullName = string.IsNullOrEmpty(e.Namespace)
                ? e.ClassName
                : $"{e.Namespace}.{e.ClassName}";
            sb.AppendLine($"        _creators[\"{e.TypeName}\"] = static () => new {fullName}();");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static ServerEntity? Create(string typeName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _creators.TryGetValue(typeName, out var creator) ? creator() : null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
