using System.Collections.Generic;
using System.Linq;
using System.Text;
using Atlas.Generators.Entity.Model;

namespace Atlas.Generators.Entity.Emitters;

internal static class FactoryEmitter
{
    public static string Emit(List<EntityModel> entities)
    {
        var sorted = entities.OrderBy(e => e.TypeName).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Entity/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Atlas.Entity;");
        sb.AppendLine();

        sb.AppendLine("namespace Atlas.Entity;");
        sb.AppendLine();

        sb.AppendLine("public static partial class EntityFactory");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Dictionary<string, Func<ServerEntity>> _creatorsByName");
        sb.AppendLine("        = new(StringComparer.Ordinal);");
        sb.AppendLine("    private static readonly Dictionary<ushort, Func<ServerEntity>> _creatorsByTypeId");
        sb.AppendLine("        = new();");
        sb.AppendLine();
        sb.AppendLine("    static EntityFactory()");
        sb.AppendLine("    {");
        for (int i = 0; i < sorted.Count; i++)
        {
            var e = sorted[i];
            var fullName = string.IsNullOrEmpty(e.Namespace)
                ? e.ClassName
                : $"{e.Namespace}.{e.ClassName}";
            sb.AppendLine($"        _creatorsByName[\"{e.TypeName}\"] = static () => new {fullName}();");
            sb.AppendLine($"        _creatorsByTypeId[{(ushort)(i + 1)}] = static () => new {fullName}();");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static ServerEntity? Create(string typeName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _creatorsByName.TryGetValue(typeName, out var creator) ? creator() : null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static ServerEntity? CreateByTypeId(ushort typeId)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _creatorsByTypeId.TryGetValue(typeId, out var creator) ? creator() : null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
