using System.Collections.Generic;
using System.Linq;
using System.Text;
using Atlas.Generators.Entity.Model;

namespace Atlas.Generators.Entity.Emitters;

internal static class SerializationEmitter
{
    public static string Emit(EntityModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Entity/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        var fields = model.Fields.Where(f => f.IsSupportedType).ToList();

        sb.AppendLine($"public partial class {model.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public override string TypeName => \"{model.TypeName}\";");
        sb.AppendLine();
        sb.AppendLine("    private const byte kSerializationVersion = 1;");
        sb.AppendLine();

        EmitSerialize(sb, fields);
        sb.AppendLine();
        EmitDeserialize(sb, fields);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitSerialize(StringBuilder sb, List<FieldModel> fields)
    {
        sb.AppendLine("    public override void Serialize(ref SpanWriter writer)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteByte(kSerializationVersion);");
        sb.AppendLine($"        writer.WriteUInt16((ushort){fields.Count});");

        // Write fields into a temp buffer to get the byte length, enabling
        // forward-compatible deserialization (old code can skip new fields).
        sb.AppendLine("        var bodyWriter = new SpanWriter(256);");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        foreach (var field in fields)
            sb.AppendLine($"            bodyWriter.{field.WriterMethod}({field.FieldName});");
        sb.AppendLine("            writer.WriteUInt16((ushort)bodyWriter.Length);");
        sb.AppendLine("            writer.WriteRawBytes(bodyWriter.WrittenSpan);");
        sb.AppendLine("        }");
        sb.AppendLine("        finally { bodyWriter.Dispose(); }");

        sb.AppendLine("    }");
    }

    private static void EmitDeserialize(StringBuilder sb, List<FieldModel> fields)
    {
        sb.AppendLine("    public override void Deserialize(ref SpanReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine("        var version = reader.ReadByte();");
        sb.AppendLine("        var fieldCount = reader.ReadUInt16();");
        sb.AppendLine("        var bodyLength = reader.ReadUInt16();");
        sb.AppendLine("        var bodyStart = reader.Position;");

        for (int i = 0; i < fields.Count; i++)
        {
            var field = fields[i];
            sb.AppendLine($"        if (fieldCount > {i}) {field.FieldName} = reader.{field.ReaderMethod}();");
        }

        // Skip past any trailing bytes from fields added in a newer version
        sb.AppendLine("        var consumed = reader.Position - bodyStart;");
        sb.AppendLine("        if (consumed < bodyLength)");
        sb.AppendLine("            reader.Advance(bodyLength - consumed);");

        sb.AppendLine("    }");
    }
}
