using System.Collections.Generic;
using System.Linq;
using System.Text;
using Atlas.Generators.Entity.Model;

namespace Atlas.Generators.Entity.Emitters;

/// <summary>
/// Generates EntityTypeRegistry.RegisterAll() that serializes entity type descriptors
/// and calls NativeApi.RegisterEntityType() at startup.
/// </summary>
internal static class TypeRegistryEmitter
{
    public static string Emit(List<EntityModel> entities)
    {
        var sorted = entities.OrderBy(e => e.TypeName).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Entity/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine("using Atlas.Core;");
        sb.AppendLine();
        sb.AppendLine("namespace Atlas.Entity;");
        sb.AppendLine();
        sb.AppendLine("internal static class EntityTypeRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static void RegisterAll()");
        sb.AppendLine("    {");
        for (int i = 0; i < sorted.Count; i++)
        {
            sb.AppendLine($"        Register_{sorted[i].ClassName}({(ushort)(i + 1)});");
        }
        sb.AppendLine("    }");

        for (int i = 0; i < sorted.Count; i++)
        {
            sb.AppendLine();
            EmitRegisterMethod(sb, sorted[i], (ushort)(i + 1));
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitRegisterMethod(StringBuilder sb, EntityModel model, ushort typeId)
    {
        sb.AppendLine($"    private static void Register_{model.ClassName}(ushort typeId)");
        sb.AppendLine("    {");
        sb.AppendLine("        var writer = new SpanWriter(512);");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            writer.WriteString(\"{model.TypeName}\");");
        sb.AppendLine("            writer.WriteUInt16(typeId);");

        var hasCell = model.Fields.Any(f => f.IsReplicated);
        var hasClient = model.Fields.Any(f => f.IsReplicated && f.ReplicationScope >= 2);
        sb.AppendLine($"            writer.WriteBool({(hasCell ? "true" : "false")});");
        sb.AppendLine($"            writer.WriteBool({(hasClient ? "true" : "false")});");

        var annotatedFields = model.Fields.Where(f => f.IsSupportedType).ToList();
        sb.AppendLine($"            writer.WritePackedUInt32({(uint)annotatedFields.Count});");

        for (int i = 0; i < annotatedFields.Count; i++)
        {
            var f = annotatedFields[i];
            sb.AppendLine($"            writer.WriteString(\"{f.PropertyName}\");");
            sb.AppendLine($"            writer.WriteByte({f.DataTypeByte});");
            sb.AppendLine($"            writer.WriteByte({f.ReplicationScope});");
            sb.AppendLine($"            writer.WriteBool({(f.IsPersistent ? "true" : "false")});");
            sb.AppendLine($"            writer.WriteByte({f.DetailLevel});");
            sb.AppendLine($"            writer.WriteUInt16({(ushort)i});");
        }

        // RPC count placeholder (will be filled by RPC generator or set to 0)
        sb.AppendLine("            writer.WritePackedUInt32(0);");

        // Compression settings: [uint8 internal] [uint8 external]
        // Both use the same EntityAttribute.Compression value for now.
        sb.AppendLine($"            writer.WriteByte({model.Compression});");
        sb.AppendLine($"            writer.WriteByte({model.Compression});");
        sb.AppendLine();
        sb.AppendLine("            NativeApi.RegisterEntityType(writer.WrittenSpan);");
        sb.AppendLine("        }");
        sb.AppendLine("        finally");
        sb.AppendLine("        {");
        sb.AppendLine("            writer.Dispose();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }
}
