using System.Text;

namespace Atlas.Generators.Def.Emitters;

// Single ModuleInitializer enforces registration order across emitters.
internal static class BootstrapEmitter
{
    public static string Emit(bool hasStructs, bool hasComponents, bool hasEntities,
                              bool hasDispatcher, ProcessContext ctx)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Atlas.Def;");
        sb.AppendLine();
        sb.AppendLine("internal static class DefBootstrap");
        sb.AppendLine("{");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void RegisterAll()");
        sb.AppendLine("    {");
        if (hasStructs)
            sb.AppendLine("        DefStructRegistry.RegisterAllStructs();");
        if (hasComponents)
            sb.AppendLine("        DefComponentRegistry.RegisterAllComponents();");
        if (hasEntities)
        {
            sb.AppendLine("        DefEntityTypeRegistry.RegisterAll();");
            sb.AppendLine("        DefEntityFactoryRegistrations.RegisterAll();");
        }
        if (hasDispatcher)
            sb.AppendLine("        Atlas.Rpc.DefRpcDispatcher.RegisterDefDispatchers();");
        // Server stores for PrepareLogin compare; client stamps into LoginRequest.
        // Try/catch tolerates the out-of-process test environment.
        if (hasStructs || hasEntities)
        {
            var bridge = ctx == ProcessContext.Client
                ? "Atlas.Client.ClientEntityRegistryBridge"
                : "Atlas.Core.EntityRegistryBridge";
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            {bridge}.SetEntityDefDigest(Atlas.Rpc.EntityDefDigest.Bytes);");
            sb.AppendLine("        }");
            sb.AppendLine("        catch (System.DllNotFoundException) { }");
            sb.AppendLine("        catch (System.InvalidOperationException) { }");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
