using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

// Generates DefComponentRegistry.RegisterAllComponents() + BuildAll(visit)
// that walks each standalone synced ComponentDefModel and feeds its wire
// layout to the C++ EntityDefRegistry::RegisterComponent reader. Pairs
// with StructRegistryEmitter so the offline DefDump tool can extract
// every descriptor surface into entity_defs.bin without needing a live
// C# runtime.
internal static class ComponentRegistryEmitter
{
    public static string Emit(List<ComponentDefModel> components, ProcessContext ctx)
    {
        var synced = components.Where(c => c.Locality == ComponentLocality.Synced
                                            && c.ComponentTypeId > 0).ToList();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();
        sb.AppendLine("namespace Atlas.Def;");
        sb.AppendLine();
        sb.AppendLine("public static class DefComponentRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    internal static void RegisterAllComponents()");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        foreach (var c in synced)
        {
            sb.AppendLine($"            Register_{c.TypeName}();");
        }
        sb.AppendLine("        }");
        sb.AppendLine("        catch (System.DllNotFoundException) { }");
        sb.AppendLine("        catch (System.InvalidOperationException) { }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static void BuildAll(System.Action<byte[]> visit)");
        sb.AppendLine("    {");
        foreach (var c in synced)
        {
            sb.AppendLine("        {");
            sb.AppendLine("            var w = new SpanWriter(256);");
            sb.AppendLine($"            try {{ Build_{c.TypeName}(ref w); visit(w.WrittenSpan.ToArray()); }}");
            sb.AppendLine("            finally { w.Dispose(); }");
            sb.AppendLine("        }");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        foreach (var c in synced)
        {
            EmitRegisterComponentMethod(sb, c, ctx);
            sb.AppendLine();
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitRegisterComponentMethod(StringBuilder sb, ComponentDefModel c,
                                                     ProcessContext ctx)
    {
        sb.AppendLine($"    private static void Register_{c.TypeName}()");
        sb.AppendLine("    {");
        sb.AppendLine("        var writer = new SpanWriter(256);");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            Build_{c.TypeName}(ref writer);");
        if (ctx == ProcessContext.Client)
            sb.AppendLine("            Atlas.Client.ClientEntityRegistryBridge.RegisterComponent(writer.WrittenSpan);");
        else
            sb.AppendLine("            Atlas.Core.EntityRegistryBridge.RegisterComponent(writer.WrittenSpan);");
        sb.AppendLine("        }");
        sb.AppendLine("        finally { writer.Dispose(); }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    private static void Build_{c.TypeName}(ref SpanWriter writer)");
        sb.AppendLine("    {");
        sb.AppendLine($"        writer.WriteUInt16((ushort){c.ComponentTypeId});");
        sb.AppendLine($"        writer.WriteString(\"{c.TypeName}\");");
        sb.AppendLine($"        writer.WriteString(\"{c.BaseTypeName ?? ""}\");");
        sb.AppendLine($"        writer.WriteByte({(byte)c.Locality});");

        // Component property records share the entity property wire shape,
        // so RegisterComponent + RegisterType both dispatch through C++
        // ReadPropertyRecord. Property index is the component-local
        // hierarchy-flat position (PropIdxBase + i).
        var props = c.Properties;
        sb.AppendLine($"        writer.WritePackedUInt32({(uint)props.Count});");
        for (int i = 0; i < props.Count; i++)
        {
            var prop = props[i];
            var topKind = TypeRegistryEmitter.ResolveTopLevelKind(prop);
            sb.AppendLine($"        writer.WriteString(\"{prop.Name}\");");
            sb.AppendLine($"        writer.WriteByte({(byte)topKind});");
            sb.AppendLine($"        writer.WriteByte({(byte)prop.Scope});");
            sb.AppendLine($"        writer.WriteBool({(prop.Persistent ? "true" : "false")});");
            sb.AppendLine($"        writer.WriteByte(5);");  // detail_level default
            sb.AppendLine($"        writer.WriteUInt16({(ushort)(c.PropIdxBase + i)});");
            sb.AppendLine($"        writer.WriteBool(false);");  // identifier
            sb.AppendLine($"        writer.WriteBool({(prop.Reliable ? "true" : "false")});");

            if (prop.TypeRef is not null && TypeRegistryEmitter.IsContainer(topKind))
            {
                TypeRegistryEmitter.EmitDataTypeRefBody(sb, prop.TypeRef);
                sb.AppendLine($"        writer.WritePackedUInt32({prop.MaxSize});");
            }
        }
        sb.AppendLine("    }");
    }
}
