using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

// Emits one `partial class` per Component declaration. Backing fields
// and property setters live in the generated half; the user partial
// (if any) hosts methods. Components land in `Atlas.Components` so
// DefLinker's TypeName uniqueness gives a single canonical type per
// generated name.
//
// Inheritance: derived classes extend their base by C# `:` syntax,
// and only emit own-property fields. propIdx is hierarchy-flat —
// derived's first prop = base's PropIdxBase + base.Properties.Count.
//
// `sealed` is applied only when no other component lists this type as
// `extends="..."`. Bases stay non-sealed so the derived can compile.
//
// Per-audience delta serializers (WriteOwnerDelta / WriteOtherDelta) are
// emitted on EVERY component class — both base and leaf — and each
// iterates the FULL flattened property list because dirty bits are
// hierarchy-flat. Backing fields are `protected` so a derived class's
// serializer can read inherited fields directly across assemblies.
//
// Client ctx variant: no dirty tracking, no audience-delta writers; just
// backing fields + plain setters + ApplyDelta override that consumes the
// per-component wire payload produced by the server's WriteXxxDelta.
internal static class ComponentEmitter
{
    public const string ComponentNamespace = "Atlas.Components";

    public static string Emit(ComponentDefModel c, bool isLeaf, ProcessContext ctx)
    {
        bool isClient = ctx == ProcessContext.Client;
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        if (!isClient)
            sb.AppendLine("using Atlas.Entity.Components;");
        sb.AppendLine("using Atlas.Serialization;");
        // Atlas.Def is where StructEmitter lands generated structs;
        // RPC stubs and property setters reference them unqualified.
        sb.AppendLine("using Atlas.Def;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ComponentNamespace};");
        sb.AppendLine();

        // Server: Atlas.Entity.Components.ReplicatedComponent (Atlas.Runtime).
        // Client: Atlas.Components.ClientReplicatedComponent (Atlas.Client) —
        // same-namespace resolution; no `using` needed since codegen output
        // is also in Atlas.Components.
        var classModifier = isLeaf ? "sealed " : "";
        string baseClass;
        if (c.BaseTypeName != null)
            baseClass = $"global::{ComponentNamespace}.{c.BaseTypeName}";
        else if (isClient)
            baseClass = "ClientReplicatedComponent";
        else
            baseClass = "ReplicatedComponent";
        sb.AppendLine($"public {classModifier}partial class {c.TypeName} : {baseClass}");
        sb.AppendLine("{");

        // Own-property backing fields + setters. Container props use lazy-
        // cached ObservableList/Dict (same pattern as entity properties)
        // so script-side mutations route through MarkDirty closures and
        // the entity-bitmap notification chain stays intact.
        var fieldVisibility = isLeaf ? "private" : "protected";
        for (int i = 0; i < c.Properties.Count; ++i)
        {
            var prop = c.Properties[i];
            var propIdx = c.PropIdxBase + i;
            EmitPropertyMember(sb, prop, propIdx, isClient, fieldVisibility);
        }
        sb.AppendLine();

        // Change-callback partials — scalar + struct only. Containers
        // mutate per-element so a wholesale (old → new) callback is
        // meaningless; the per-op hook is a future roadmap item.
        foreach (var prop in c.Properties)
        {
            if (PropertyCodec.IsList(prop) || PropertyCodec.IsDict(prop)) continue;
            var csType = PropCsType(prop);
            var propName = DefTypeHelper.ToPropertyName(prop.Name);
            sb.AppendLine($"    partial void On{propName}Changed({csType} oldValue, {csType} newValue);");
        }
        sb.AppendLine();

        // Component RPC stubs. Same role logic as entity-level (Send /
        // Receive / Forbidden). The send-side helper on the component
        // base composes rpc_id from (slot, direction, entity TypeId,
        // methodIdx) at runtime — methodIdx is the only piece baked into
        // the generated stub, so a single component class instance
        // attached to different entity types still routes correctly.
        EmitRpcStubs(sb, c.ClientMethods, "client_methods", ctx);
        EmitRpcStubs(sb, c.CellMethods,   "cell_methods",   ctx);
        EmitRpcStubs(sb, c.BaseMethods,   "base_methods",   ctx);

        var flat = FlattenChain(c);
        if (flat.Count > 0)
        {
            if (isClient)
            {
                EmitClientApplyDelta(sb, flat);
            }
            else
            {
                // Server: audience masks + per-audience writers. Walk the
                // inheritance chain so a leaf's mask covers its inherited
                // props too — _dirtyFlags is one ulong shared across the
                // whole hierarchy.
                EmitAudienceMasks(sb, flat);
                sb.AppendLine();
                EmitAudiencePredicates(sb);
                sb.AppendLine();
                EmitAudienceDelta(sb, flat, "WriteOwnerDelta",
                                  "OwnerVisibleScalarMask", "OwnerVisibleContainerMask",
                                  IsOwnerVisible);
                sb.AppendLine();
                EmitAudienceDelta(sb, flat, "WriteOtherDelta",
                                  "OtherVisibleScalarMask", "OtherVisibleContainerMask",
                                  IsOtherVisible);
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // Walks the base chain bottom-up (most-base first), emits each level's
    // properties tagged with their hierarchy-flat propIdx. Order matches
    // the wire layout produced by setters: base props before own props.
    private static List<(PropertyDefModel Prop, int PropIdx)> FlattenChain(ComponentDefModel c)
    {
        var chain = new List<ComponentDefModel>();
        for (var cur = c; cur != null; cur = cur.Base) chain.Add(cur);
        chain.Reverse();
        var result = new List<(PropertyDefModel, int)>();
        foreach (var level in chain)
        {
            for (int i = 0; i < level.Properties.Count; ++i)
                result.Add((level.Properties[i], level.PropIdxBase + i));
        }
        return result;
    }

    // Mask constants are emitted as bare ulong literals (one bit per
    // propIdx). Components don't have a generated `ReplicatedDirtyFlags`
    // enum like entities — _dirtyFlags is just a ulong on the base class.
    private static void EmitAudienceMasks(StringBuilder sb,
                                          List<(PropertyDefModel Prop, int PropIdx)> flat)
    {
        ulong Mask(System.Func<PropertyDefModel, bool> pred)
        {
            ulong m = 0;
            foreach (var (p, idx) in flat)
                if (pred(p)) m |= 1UL << idx;
            return m;
        }
        bool IsScalar(PropertyDefModel p) => !PropertyCodec.IsList(p) && !PropertyCodec.IsDict(p);
        bool IsContainer(PropertyDefModel p) => PropertyCodec.IsList(p) || PropertyCodec.IsDict(p);

        var ownerScalar    = Mask(p => IsOwnerVisible(p.Scope) && IsScalar(p));
        var ownerContainer = Mask(p => IsOwnerVisible(p.Scope) && IsContainer(p));
        var otherScalar    = Mask(p => IsOtherVisible(p.Scope) && IsScalar(p));
        var otherContainer = Mask(p => IsOtherVisible(p.Scope) && IsContainer(p));

        sb.AppendLine($"    private const ulong OwnerVisibleScalarMask    = 0x{ownerScalar:X16}UL;");
        sb.AppendLine($"    private const ulong OwnerVisibleContainerMask = 0x{ownerContainer:X16}UL;");
        sb.AppendLine($"    private const ulong OtherVisibleScalarMask    = 0x{otherScalar:X16}UL;");
        sb.AppendLine($"    private const ulong OtherVisibleContainerMask = 0x{otherContainer:X16}UL;");
        sb.AppendLine($"    private const ulong OwnerVisibleMask = OwnerVisibleScalarMask | OwnerVisibleContainerMask;");
        sb.AppendLine($"    private const ulong OtherVisibleMask = OtherVisibleScalarMask | OtherVisibleContainerMask;");
    }

    private static void EmitAudiencePredicates(StringBuilder sb)
    {
        sb.AppendLine("    public override bool HasOwnerDirty() => (_dirtyFlags & OwnerVisibleMask) != 0UL;");
        sb.AppendLine("    public override bool HasOtherDirty() => (_dirtyFlags & OtherVisibleMask) != 0UL;");
    }

    // Per-audience delta wire shape (mirrors entity delta exactly so the
    // client decoder can reuse the same parser):
    //   [u8 sectionMask]  bit0 = scalar, bit1 = container
    //   if bit0: [u64 scalarFlags][scalar values...]
    //   if bit1: [u64 containerFlags][container ops...]
    // Always ulong because component _dirtyFlags is ulong; if a future
    // bit-pack pass wants smaller widths, do it everywhere — entity, component, wire.
    private static void EmitAudienceDelta(StringBuilder sb,
                                          List<(PropertyDefModel Prop, int PropIdx)> flat,
                                          string methodName,
                                          string scalarMaskName,
                                          string containerMaskName,
                                          System.Func<PropertyScope, bool> audiencePred)
    {
        sb.AppendLine($"    public override void {methodName}(ref SpanWriter writer)");
        sb.AppendLine("    {");
        sb.AppendLine($"        ulong scalarFlags    = _dirtyFlags & {scalarMaskName};");
        sb.AppendLine($"        ulong containerFlags = _dirtyFlags & {containerMaskName};");
        sb.AppendLine("        byte sectionMask = 0;");
        sb.AppendLine("        if (scalarFlags    != 0UL) sectionMask |= 0x01;");
        sb.AppendLine("        if (containerFlags != 0UL) sectionMask |= 0x02;");
        sb.AppendLine("        writer.WriteByte(sectionMask);");
        sb.AppendLine();

        sb.AppendLine("        if (scalarFlags != 0UL)");
        sb.AppendLine("        {");
        sb.AppendLine("            writer.WriteUInt64(scalarFlags);");
        foreach (var (prop, idx) in flat)
        {
            if (!audiencePred(prop.Scope)) continue;
            if (PropertyCodec.IsList(prop) || PropertyCodec.IsDict(prop)) continue;
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            sb.AppendLine($"            if ((scalarFlags & (1UL << {idx})) != 0UL)");
            sb.AppendLine($"                {PropertyCodec.WriteExpr(prop, "writer", fieldName)};");
        }
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        if (containerFlags != 0UL)");
        sb.AppendLine("        {");
        sb.AppendLine("            writer.WriteUInt64(containerFlags);");
        foreach (var (prop, idx) in flat)
        {
            if (!audiencePred(prop.Scope)) continue;
            if (!PropertyCodec.IsList(prop) && !PropertyCodec.IsDict(prop)) continue;
            sb.AppendLine($"            if ((containerFlags & (1UL << {idx})) != 0UL)");
            sb.AppendLine("            {");
            if (PropertyCodec.IsList(prop))
                PropertyCodec.EmitListOpLogWrite(sb, prop, "writer", "                ");
            else
                PropertyCodec.EmitDictOpLogWrite(sb, prop, "writer", "                ");
            sb.AppendLine("            }");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    // Client-side decoder. Reads sectionMask + flags + values; for each
    // changed scalar prop fires OnXxxChanged so script callbacks observe
    // the transition. Containers are written via PropertyCodec helpers
    // identical to the entity-level read path so wire compat is automatic.
    //
    // The flat list iterates EVERY property (visible to either audience)
    // because the wire sectionMask + flags carry the full per-audience
    // selection — if the bit isn't set, the value isn't read. Skipping
    // by audience here would desync the cursor.
    private static void EmitClientApplyDelta(StringBuilder sb,
                                              List<(PropertyDefModel Prop, int PropIdx)> flat)
    {
        sb.AppendLine("    public override void ApplyDelta(ref SpanReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine("        byte sectionMask = reader.ReadByte();");
        sb.AppendLine("        if ((sectionMask & 0x01) != 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            ulong scalarFlags = reader.ReadUInt64();");
        foreach (var (prop, idx) in flat)
        {
            if (PropertyCodec.IsList(prop) || PropertyCodec.IsDict(prop)) continue;
            var propName = DefTypeHelper.ToPropertyName(prop.Name);
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            sb.AppendLine($"            if ((scalarFlags & (1UL << {idx})) != 0UL)");
            sb.AppendLine("            {");
            sb.AppendLine($"                var old{propName} = {fieldName};");
            sb.AppendLine($"                {fieldName} = {PropertyCodec.ReadExpr(prop, "reader")};");
            sb.AppendLine($"                On{propName}Changed(old{propName}, {fieldName});");
            sb.AppendLine("            }");
        }
        sb.AppendLine("        }");
        sb.AppendLine("        if ((sectionMask & 0x02) != 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            ulong containerFlags = reader.ReadUInt64();");
        foreach (var (prop, idx) in flat)
        {
            if (!PropertyCodec.IsList(prop) && !PropertyCodec.IsDict(prop)) continue;
            sb.AppendLine($"            if ((containerFlags & (1UL << {idx})) != 0UL)");
            if (PropertyCodec.IsList(prop))
                PropertyCodec.EmitListOpLogRead(sb, prop, "reader", "            ");
            else
                PropertyCodec.EmitDictOpLogRead(sb, prop, "reader", "            ");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static bool IsOwnerVisible(PropertyScope scope) => scope.IsOwnClientVisible();
    private static bool IsOtherVisible(PropertyScope scope) => scope.IsOtherClientsVisible();

    // C# type for a property — Observable wrappers for containers,
    // generated struct name for structs, scalar mapping otherwise.
    private static string PropCsType(PropertyDefModel prop)
    {
        if (prop.TypeRef is null) return DefTypeHelper.ToCSharpType(prop.Type);
        return prop.TypeRef.Kind switch
        {
            PropertyDataKind.Struct => prop.TypeRef.StructName!,
            PropertyDataKind.List =>
                $"global::Atlas.Observable.ObservableList<{PropertyCodec.CSharpTypeFor(prop.TypeRef.Elem!)}>",
            PropertyDataKind.Dict =>
                $"global::Atlas.Observable.ObservableDict<{PropertyCodec.CSharpTypeFor(prop.TypeRef.Key!)}, {PropertyCodec.CSharpTypeFor(prop.TypeRef.Elem!)}>",
            _ => DefTypeHelper.ToCSharpType(prop.Type),
        };
    }

    // Backing-field declaration + public setter for one property. Three
    // shapes:
    //   scalar  →  private T _x;         public T X { get; set with MarkDirty }
    //   struct  →  private S _x;         public S X { get; set with MarkDirty }
    //              (whole-struct sync — field-level MutRef is a follow-up)
    //   list    →  private OL? __xList;  public OL X => __xList ??= new(closure)
    //   dict    →  private OD? __xDict;  public OD X => __xDict ??= new(closure)
    private static void EmitPropertyMember(StringBuilder sb, PropertyDefModel prop,
                                           int propIdx, bool isClient, string fieldVisibility)
    {
        var propName = DefTypeHelper.ToPropertyName(prop.Name);
        var csType = PropCsType(prop);

        if (PropertyCodec.IsList(prop) || PropertyCodec.IsDict(prop))
        {
            // Lazy-cached observable. The closure on the server captures
            // MarkDirty(propIdx); the client gets an inert no-op so
            // prediction-side script writes don't fire fake events.
            var backing = PropertyCodec.IsList(prop)
                ? $"__{prop.Name}List"
                : $"__{prop.Name}Dict";
            sb.AppendLine($"    {fieldVisibility} {csType}? {backing};");
            var closure = isClient ? "() => {}" : $"() => MarkDirty({propIdx})";
            sb.AppendLine($"    public {csType} {propName} => {backing} ??= new({closure});");
            sb.AppendLine();
            return;
        }

        // Scalar / struct: a plain backing field + property with custom
        // setter. Struct uses whole-sync (no MutRef yet) — assignment
        // re-ships the full struct body on the next frame.
        var fieldName = DefTypeHelper.ToFieldName(prop.Name);
        if (DefTypeHelper.NeedsFieldInitializer(prop.Type))
            sb.AppendLine($"    {fieldVisibility} {csType} {fieldName} = {DefTypeHelper.DefaultValue(prop.Type)};");
        else
            sb.AppendLine($"    {fieldVisibility} {csType} {fieldName};");

        sb.AppendLine($"    public {csType} {propName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        get => {fieldName};");
        if (isClient)
        {
            sb.AppendLine($"        set => {fieldName} = value;");
        }
        else if (PropertyCodec.IsStruct(prop))
        {
            // Skip equality short-circuit for structs — comparing two
            // value-type instances is cheap enough but the codegen would
            // need IEquatable<T>; just always mark dirty on assign.
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine($"            {fieldName} = value;");
            sb.AppendLine($"            MarkDirty(propIdx: {propIdx});");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine($"            if ({fieldName} != value)");
            sb.AppendLine("            {");
            sb.AppendLine($"                {fieldName} = value;");
            sb.AppendLine($"                MarkDirty(propIdx: {propIdx});");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitRpcStubs(StringBuilder sb, List<MethodDefModel> methods,
                                      string section, ProcessContext ctx)
    {
        if (methods.Count == 0) return;
        var sorted = methods.OrderBy(m => m.Name).ToList();
        for (int i = 0; i < sorted.Count; i++)
        {
            var method = sorted[i];
            var role = RpcRoleHelper.GetRole(section, ctx, method.Exposed);
            int methodIdx = i + 1;
            EmitRpcMethod(sb, method, role, methodIdx, section, ctx);
        }
    }

    private static void EmitRpcMethod(StringBuilder sb, MethodDefModel method, RpcRole role,
                                       int methodIdx, string section, ProcessContext ctx)
    {
        var paramList = RpcArgCodec.BuildParamList(method.Args);
        sb.AppendLine();

        switch (role)
        {
            case RpcRole.Receive:
                sb.AppendLine($"    public partial void {method.Name}({paramList});");
                break;

            case RpcRole.Send:
                // Client: SendClientRpc unavailable (clients don't call
                // client_methods on themselves). Client-side send for
                // client_methods is unreachable, so don't emit it; the
                // dispatch role table already routes that combination
                // through Receive on the client side.
                if (ctx == ProcessContext.Client && section == "client_methods")
                {
                    // Defensive: shouldn't happen given the role helper,
                    // but be loud if it ever does.
                    sb.AppendLine($"    // {method.Name}: client_methods send role on client is invalid");
                    break;
                }
                sb.AppendLine($"    // Send stub for {section}.{method.Name}");
                sb.AppendLine($"    public void {method.Name}({paramList})");
                sb.AppendLine("    {");
                EmitSerializeAndSend(sb, method, methodIdx, section);
                sb.AppendLine("    }");
                break;

            case RpcRole.Forbidden:
                sb.AppendLine($"    public void {method.Name}({paramList})");
                sb.AppendLine("    {");
                sb.AppendLine($"        throw new System.InvalidOperationException(");
                sb.AppendLine($"            \"{method.Name} is not exposed to this process context.\");");
                sb.AppendLine("    }");
                break;
        }
    }

    private static void EmitSerializeAndSend(StringBuilder sb, MethodDefModel method,
                                              int methodIdx, string section)
    {
        var sendHelper = section switch
        {
            "client_methods" => "SendClientRpc",
            "cell_methods"   => "SendCellRpc",
            "base_methods"   => "SendBaseRpc",
            _                => "SendCellRpc",
        };
        if (method.Args.Count == 0)
        {
            sb.AppendLine($"        {sendHelper}({methodIdx}, System.ReadOnlySpan<byte>.Empty);");
            return;
        }
        sb.AppendLine("        var writer = new SpanWriter(64);");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        foreach (var arg in method.Args)
            RpcArgCodec.EmitWrite(sb, arg, "writer", "            ");
        sb.AppendLine($"            {sendHelper}({methodIdx}, writer.WrittenSpan);");
        sb.AppendLine("        }");
        sb.AppendLine("        finally { writer.Dispose(); }");
    }
}
