using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

/// <summary>
/// Generates scope-filtered delta sync methods from .def property definitions.
/// Uses the 8-value PropertyScope enum for precise scope filtering.
/// </summary>
internal static class DeltaSyncEmitter
{
    public static string? Emit(EntityDefModel def, string className, string namespaceName,
                               ProcessContext ctx)
    {
        // ATLAS_DEF008: a replicable `position` is excluded from the entire
        // replication pipeline (no enum bit, no delta, no snapshot) —
        // position rides the volatile channel via ClientEntity base.
        // ctx gating keeps the delta pipeline to props whose backing field
        // lives on THIS process (base vs cell); otherwise codegen references
        // fields that don't exist.
        var replicableProps = def.Properties
            .Where(p => p.Scope.IsClientVisible() && !p.IsReservedPosition &&
                        IsOnThisSide(p.Scope, ctx))
            .ToList();
        if (replicableProps.Count == 0) return null;

        // Client path: snapshot deserializers only (no dirty tracking, no
        // outbound serializers). Wire format mirrors the server's
        // SerializeForOwner/OtherClient: raw fields in declaration order
        // filtered by scope predicate — identical iteration both sides.
        if (ctx == ProcessContext.Client) return EmitClientSnapshotApplyMethods(
            def, className, namespaceName, replicableProps);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");

        // Audience masks partition dirty flags for the replication pump.
        // Owner mask covers props visible to the owning client (OwnClient,
        // AllClients, CellPublicAndOwn, BaseAndClient); Other mask covers
        // observer-visible props (AllClients, OtherClients). CellPublicAndOwn
        // stays owner-only — revealing it to non-owners is a privacy bug.
        EmitAudienceMasks(sb, replicableProps);
        sb.AppendLine();

        // ApplyReplicatedDelta — decodes the wire delta (flag byte(s) +
        // conditional field reads). Wire-compatible with the per-audience
        // SerializeOwnerDelta / SerializeOtherDelta emitted below.
        EmitApplyReplicatedDelta(sb, replicableProps);
        sb.AppendLine();

        // SerializeForOwnerClient — fields visible to owner client
        var ownerFields = replicableProps.Where(p => IsOwnerVisible(p.Scope)).ToList();
        if (ownerFields.Count > 0)
        {
            EmitScopeSerialize(sb, ownerFields, "SerializeForOwnerClient");
            sb.AppendLine();
        }

        // SerializeForOtherClients — fields visible to non-owner clients
        var otherFields = replicableProps.Where(p => IsOtherVisible(p.Scope)).ToList();
        if (otherFields.Count > 0)
        {
            EmitScopeSerialize(sb, otherFields, "SerializeForOtherClients");
            sb.AppendLine();
        }

        // Per-audience delta serializers. Reliability is a transport-layer
        // concern (picked at BaseApp send path), not a serialization split.
        EmitAudienceDeltaSerializer(sb, replicableProps, "SerializeOwnerDelta",
                                    "OwnerVisibleMask", p => IsOwnerVisible(p.Scope));
        sb.AppendLine();
        EmitAudienceDeltaSerializer(sb, replicableProps, "SerializeOtherDelta",
                                    "OtherVisibleMask", p => IsOtherVisible(p.Scope));
        sb.AppendLine();

        // Frame counters live in this generated partial so non-replicable
        // entities don't carry them.
        sb.AppendLine("    private ulong _eventSeq;");
        sb.AppendLine("    private ulong _volatileSeq;");
        sb.AppendLine();

        // BuildAndConsumeReplicationFrame — per-tick entry point for the
        // CellApp replication pump. Returns false when no dirty state, so
        // the caller skips both the allocation and the NativeApi hop.
        EmitBuildAndConsume(sb, ownerFields.Count > 0, otherFields.Count > 0);

        sb.AppendLine("}");
        return sb.ToString();
    }

    // Client-ctx variant. Emits only ApplyOwnerSnapshot / ApplyOtherSnapshot
    // — symmetric counterparts of the cell-side SerializeForOwner/OtherClient.
    // Base-scope client-visible props (BaseAndClient) stay out: they arrive
    // via ApplyReplicatedDelta on the delta channel, not in the snapshot.
    // Keeping base-scope out preserves lockstep between cell's serializer
    // and client's deserializer.
    private static string? EmitClientSnapshotApplyMethods(EntityDefModel def, string className,
                                                           string namespaceName,
                                                           List<PropertyDefModel> replicableProps)
    {
        var ownerFields = replicableProps
            .Where(p => IsOwnerVisible(p.Scope) && p.Scope.IsCell()).ToList();
        var otherFields = replicableProps
            .Where(p => IsOtherVisible(p.Scope) && p.Scope.IsCell()).ToList();
        if (ownerFields.Count == 0 && otherFields.Count == 0) return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");

        if (ownerFields.Count > 0)
        {
            EmitScopeApply(sb, ownerFields, "ApplyOwnerSnapshot");
            sb.AppendLine();
        }
        if (otherFields.Count > 0)
        {
            EmitScopeApply(sb, otherFields, "ApplyOtherSnapshot");
            sb.AppendLine();
        }

        // ApplyReplicatedDelta — decode-time scope-agnostic; the server's
        // audience mask guarantees only visible bits are ever set, so
        // iterating every replicable prop is safe. Changed fields fire
        // OnXxxChanged so scripts observe the transition.
        EmitClientApplyReplicatedDelta(sb, replicableProps);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitClientApplyReplicatedDelta(StringBuilder sb,
                                                        List<PropertyDefModel> replicableProps)
    {
        var (_, _, _, readerMethod, _) = GetFlagsTypeInfo(replicableProps.Count);
        sb.AppendLine("    public override void ApplyReplicatedDelta(ref SpanReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var flags = (ReplicatedDirtyFlags)reader.{readerMethod}();");
        foreach (var prop in replicableProps)
        {
            var propName = DefTypeHelper.ToPropertyName(prop.Name);
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            var readMethod = DefTypeHelper.ReadMethod(prop.Type);
            sb.AppendLine($"        if ((flags & ReplicatedDirtyFlags.{propName}) != 0)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var old{propName} = {fieldName};");
            sb.AppendLine($"            {fieldName} = reader.{readMethod}();");
            sb.AppendLine($"            On{propName}Changed(old{propName}, {fieldName});");
            sb.AppendLine("        }");
        }
        sb.AppendLine("    }");
    }

    private static void EmitScopeApply(StringBuilder sb, List<PropertyDefModel> props,
                                       string methodName)
    {
        // Direct-to-backing-field writes: a snapshot is an authoritative
        // state reset, not an observed change, so property-change callbacks
        // (OnXxxChanged, emitted by PropertiesEmitter) MUST NOT fire here.
        // Setter callbacks on the delta path live in a separate method.
        sb.AppendLine($"    public override void {methodName}(ref SpanReader reader)");
        sb.AppendLine("    {");
        foreach (var prop in props)
        {
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            var readMethod = DefTypeHelper.ReadMethod(prop.Type);
            sb.AppendLine($"        {fieldName} = reader.{readMethod}();");
        }
        sb.AppendLine("    }");
    }

    private static void EmitAudienceMasks(StringBuilder sb, List<PropertyDefModel> props)
    {
        string MaskExpr(System.Func<PropertyScope, bool> pred)
        {
            var names = props.Where(p => pred(p.Scope))
                             .Select(p => "ReplicatedDirtyFlags." + DefTypeHelper.ToPropertyName(p.Name))
                             .ToList();
            return names.Count == 0 ? "ReplicatedDirtyFlags.None" : string.Join(" | ", names);
        }

        sb.AppendLine($"    private const ReplicatedDirtyFlags OwnerVisibleMask = {MaskExpr(IsOwnerVisible)};");
        sb.AppendLine($"    private const ReplicatedDirtyFlags OtherVisibleMask = {MaskExpr(IsOtherVisible)};");
    }

    private static void EmitAudienceDeltaSerializer(StringBuilder sb, List<PropertyDefModel> props,
                                                    string methodName, string maskName,
                                                    System.Func<PropertyDefModel, bool> audiencePred)
    {
        var (_, _, writerMethod, _, castPrefix) = GetFlagsTypeInfo(props.Count);
        sb.AppendLine($"    public void {methodName}(ref SpanWriter writer)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var flags = _dirtyFlags & {maskName};");
        sb.AppendLine($"        writer.{writerMethod}({castPrefix}flags);");
        foreach (var prop in props)
        {
            // Only audience-visible props can have their flag set after the
            // mask, so skip the rest at codegen time.
            if (!audiencePred(prop)) continue;
            var propName = DefTypeHelper.ToPropertyName(prop.Name);
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            var writeMethod = DefTypeHelper.WriteMethod(prop.Type);
            sb.AppendLine($"        if ((flags & ReplicatedDirtyFlags.{propName}) != 0)");
            sb.AppendLine($"            writer.{writeMethod}({fieldName});");
        }
        sb.AppendLine("    }");
    }

    private static void EmitBuildAndConsume(StringBuilder sb, bool hasOwnerSnapshot,
                                            bool hasOtherSnapshot)
    {
        // Zero-alloc API: caller owns the four SpanWriters (pool-rented,
        // Reset() between entities). Returns (eventSeq, volatileSeq) via
        // out params; avoids per-tick byte[] churn on high-fanout pumps.
        sb.AppendLine("    public override bool BuildAndConsumeReplicationFrame(");
        sb.AppendLine("        ref SpanWriter ownerSnapshot, ref SpanWriter otherSnapshot,");
        sb.AppendLine("        ref SpanWriter ownerDelta, ref SpanWriter otherDelta,");
        sb.AppendLine("        out ulong eventSeq, out ulong volatileSeq)");
        sb.AppendLine("    {");
        sb.AppendLine("        bool hasEvent = (_dirtyFlags & (OwnerVisibleMask | OtherVisibleMask)) != ReplicatedDirtyFlags.None;");
        sb.AppendLine("        bool hasVolatile = VolatileDirtyCore;");
        sb.AppendLine("        if (!hasEvent && !hasVolatile)");
        sb.AppendLine("        {");
        sb.AppendLine("            eventSeq = 0; volatileSeq = 0;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (hasEvent)");
        sb.AppendLine("        {");
        sb.AppendLine("            _eventSeq++;");
        if (hasOwnerSnapshot)
            sb.AppendLine("            SerializeForOwnerClient(ref ownerSnapshot);");
        if (hasOtherSnapshot)
            sb.AppendLine("            SerializeForOtherClients(ref otherSnapshot);");
        sb.AppendLine("            SerializeOwnerDelta(ref ownerDelta);");
        sb.AppendLine("            SerializeOtherDelta(ref otherDelta);");
        sb.AppendLine("            _dirtyFlags = ReplicatedDirtyFlags.None;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (hasVolatile)");
        sb.AppendLine("        {");
        sb.AppendLine("            _volatileSeq++;");
        sb.AppendLine("            VolatileDirtyCore = false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        eventSeq = hasEvent ? _eventSeq : 0UL;");
        sb.AppendLine("        volatileSeq = hasVolatile ? _volatileSeq : 0UL;");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
    }

    private static void EmitApplyReplicatedDelta(StringBuilder sb, List<PropertyDefModel> props)
    {
        var (_, _, _, readerMethod, _) = GetFlagsTypeInfo(props.Count);
        sb.AppendLine("    public void ApplyReplicatedDelta(ref SpanReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var flags = (ReplicatedDirtyFlags)reader.{readerMethod}();");
        foreach (var prop in props)
        {
            var propName = DefTypeHelper.ToPropertyName(prop.Name);
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            var readMethod = DefTypeHelper.ReadMethod(prop.Type);
            sb.AppendLine($"        if ((flags & ReplicatedDirtyFlags.{propName}) != 0)");
            sb.AppendLine($"            {fieldName} = reader.{readMethod}();");
        }
        sb.AppendLine("    }");
    }

    private static void EmitScopeSerialize(StringBuilder sb, List<PropertyDefModel> props,
                                            string methodName)
    {
        // SerializeForOwnerClient / SerializeForOtherClients are virtual on ServerEntity
        // so the baseline pump can invoke them polymorphically on any entity.
        sb.AppendLine($"    public override void {methodName}(ref SpanWriter writer)");
        sb.AppendLine("    {");
        foreach (var prop in props)
        {
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            var writeMethod = DefTypeHelper.WriteMethod(prop.Type);
            sb.AppendLine($"        writer.{writeMethod}({fieldName});");
        }
        sb.AppendLine("    }");
    }

    // Delegate to the shared PropertyScopeExtensions helpers so every caller
    // (emitters, DEF008 detection, runtime) resolves scope membership
    // against the same rulebook.
    private static bool IsOwnerVisible(PropertyScope scope) => scope.IsOwnClientVisible();
    private static bool IsOtherVisible(PropertyScope scope) => scope.IsOtherClientsVisible();

    // Decide whether a replicable scope belongs on this process's generated
    // class. Client always sees every replicable property (from its
    // observer-side projection); Server (legacy fallback) also sees
    // everything; Base owns BaseAndClient; Cell owns the rest.
    private static bool IsOnThisSide(PropertyScope scope, ProcessContext ctx) => ctx switch
    {
        ProcessContext.Base => scope.IsBase(),
        ProcessContext.Cell => scope.IsCell(),
        _ => true,  // Client, Server — emit everything the caller has already filtered
    };

    private static (string BackingType, string FlagSuffix, string WriterMethod, string ReaderMethod, string CastPrefix) GetFlagsTypeInfo(int fieldCount)
    {
        if (fieldCount <= 8) return ("byte", "u", "WriteByte", "ReadByte", "(byte)");
        if (fieldCount <= 16) return ("ushort", "u", "WriteUInt16", "ReadUInt16", "(ushort)");
        if (fieldCount <= 32) return ("uint", "u", "WriteUInt32", "ReadUInt32", "(uint)");
        return ("ulong", "UL", "WriteUInt64", "ReadUInt64", "(ulong)");
    }
}
