using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

/// <summary>
/// Generates scope-filtered delta sync methods from .def property definitions.
/// Uses the 8-value PropertyScope enum for precise scope filtering.
/// </summary>
internal static class DeltaSyncEmitter
{
    public static string? Emit(EntityDefModel def, string className, string namespaceName,
                               ProcessContext ctx)
    {
        // ATLAS_DEF008: a replicable `position` is flagged IsReservedPosition
        // in the parser and must not appear anywhere in the replication
        // pipeline — no enum bit, no delta serializer/deserializer, no
        // snapshot read/write. Position rides the volatile channel
        // exclusively, handled by ClientEntity base.
        //
        // ctx gating mirrors the invariant enforced in
        // PropertiesEmitter.GetPropertiesForContext — a replicable scope
        // is "cell-side" (OwnClient / AllClients / OtherClients /
        // CellPublicAndOwn) or "base-side" (BaseAndClient). The delta
        // pipeline must see only props whose backing field actually lives
        // on THIS process, otherwise the generator emits references to
        // fields that don't exist and the build fails.
        var replicableProps = def.Properties
            .Where(p => p.Scope.IsClientVisible() && !p.IsReservedPosition &&
                        IsOnThisSide(p.Scope, ctx))
            .ToList();
        if (replicableProps.Count == 0) return null;

        // Client path: no dirty-tracking or outbound serializers. We emit
        // scope-subset snapshot *deserializers* (paired to the server's
        // SerializeForOwnerClient / SerializeForOtherClients) so that AoI
        // enter and baseline payloads can be reconstructed without the
        // version+fieldCount+bodyLength framing used by full-state
        // Serialize/Deserialize. Wire format: raw fields in declaration
        // order, filtered by scope predicate — identical iteration
        // produces identical wire on both sides.
        if (ctx == ProcessContext.Client) return EmitClientSnapshotApplyMethods(
            def, className, namespaceName, replicableProps);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");

        // Static masks partitioning the dirty flags by client audience. These are
        // what the CellApp replication pump needs: Owner side receives props
        // visible to the entity's owning client (OwnClient, AllClients,
        // CellPublicAndOwn, BaseAndClient); the Other side receives props
        // visible to observers (AllClients, OtherClients). CellPublicAndOwn
        // intentionally appears ONLY in the owner mask — revealing a
        // CellPublicAndOwn field to non-owners is a privacy bug.
        EmitAudienceMasks(sb, replicableProps);
        sb.AppendLine();

        // The CellApp replication pump drives SerializeOwnerDelta /
        // SerializeOtherDelta (below) via BuildAndConsumeReplicationFrame
        // and publish_replication_frame. Reliability is a transport concern
        // picked at the BaseApp send path (ReplicatedReliableDeltaFromCell
        // vs ReplicatedDeltaFromCell), not a serialization split.

        // ApplyReplicatedDelta — apply delta from wire. Still emitted:
        // SerializeOtherDelta's output is wire-compatible with this decoder
        // (same flag-prefix + conditional field writes), and the client's
        // kEntityPropertyUpdate handler dispatches through here.
        EmitApplyReplicatedDelta(sb, replicableProps);
        sb.AppendLine();

        // SerializeForOwnerClient — fields visible to owner client
        var ownerFields = replicableProps.Where(p => IsOwnerVisible(p.Scope)).ToList();
        if (ownerFields.Count > 0)
        {
            EmitScopeSerialize(sb, ownerFields, "SerializeForOwnerClient");
            sb.AppendLine();
        }

        // SerializeForOtherClients — fields visible to non-owner clients
        var otherFields = replicableProps.Where(p => IsOtherVisible(p.Scope)).ToList();
        if (otherFields.Count > 0)
        {
            EmitScopeSerialize(sb, otherFields, "SerializeForOtherClients");
            sb.AppendLine();
        }

        // Per-audience delta serializers — what CellApp sends to observers when
        // a property changes. Distinct from the reliable/unreliable split: any
        // property can appear in either owner or other delta depending on
        // scope, and reliability is a transport-layer concern.
        EmitAudienceDeltaSerializer(sb, replicableProps, "SerializeOwnerDelta",
                                    "OwnerVisibleMask", p => IsOwnerVisible(p.Scope));
        sb.AppendLine();
        EmitAudienceDeltaSerializer(sb, replicableProps, "SerializeOtherDelta",
                                    "OtherVisibleMask", p => IsOtherVisible(p.Scope));
        sb.AppendLine();

        // The frame counters live alongside the dirty flag state in this
        // generated partial so non-replicable entities don't carry them.
        sb.AppendLine("    private ulong _eventSeq;");
        sb.AppendLine("    private ulong _volatileSeq;");
        sb.AppendLine();

        // BuildAndConsumeReplicationFrame — the per-tick entry point the
        // CellApp replication pump calls. Returns null on fast path (no dirty
        // state at all) so the caller can skip both the allocation and the
        // NativeApi hop.
        EmitBuildAndConsume(sb, ownerFields.Count > 0, otherFields.Count > 0);

        sb.AppendLine("}");
        return sb.ToString();
    }

    // Client-ctx sibling of the Server Emit path. Produces only
    // ApplyOwnerSnapshot / ApplyOtherSnapshot — the exact symmetric
    // counterparts of the CELL-side SerializeForOwnerClient /
    // SerializeForOtherClients. Base-scope client-visible props
    // (BaseAndClient) deliberately don't participate in this snapshot
    // pair — base-side properties arrive on the delta channel
    // (ApplyReplicatedDelta) via set_<propname>, not bundled into the
    // createCellPlayer snapshot. Keeping base-scope out of
    // ApplyOwnerSnapshot preserves lockstep between cell's serializer
    // and client's deserializer as enforced by
    // ClientContext_ScopeApplyOrder_MirrorsServerScopeSerialize.
    // No dirty flags, no framing, no event/volatile seq counters on the
    // client.
    private static string? EmitClientSnapshotApplyMethods(EntityDefModel def, string className,
                                                           string namespaceName,
                                                           List<PropertyDefModel> replicableProps)
    {
        var ownerFields = replicableProps
            .Where(p => IsOwnerVisible(p.Scope) && p.Scope.IsCell()).ToList();
        var otherFields = replicableProps
            .Where(p => IsOtherVisible(p.Scope) && p.Scope.IsCell()).ToList();
        if (ownerFields.Count == 0 && otherFields.Count == 0) return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");

        if (ownerFields.Count > 0)
        {
            EmitScopeApply(sb, ownerFields, "ApplyOwnerSnapshot");
            sb.AppendLine();
        }
        if (otherFields.Count > 0)
        {
            EmitScopeApply(sb, otherFields, "ApplyOtherSnapshot");
            sb.AppendLine();
        }

        // ApplyReplicatedDelta — scope-agnostic at decode time. The server
        // audience mask guarantees only bits for scope-visible fields are
        // ever set in `flags`, so iterating every replicable prop is safe:
        // non-audience bits can't fire the inner read. Every field that
        // actually changed fires OnXxxChanged so scripts observe the
        // transition. ReplicatedDirtyFlags is emitted by PropertiesEmitter
        // on the client side too (dirty-backing field is not).
        EmitClientApplyReplicatedDelta(sb, replicableProps);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitClientApplyReplicatedDelta(StringBuilder sb,
                                                        List<PropertyDefModel> replicableProps)
    {
        var (_, _, _, readerMethod, _) = GetFlagsTypeInfo(replicableProps.Count);
        sb.AppendLine("    public override void ApplyReplicatedDelta(ref SpanReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var flags = (ReplicatedDirtyFlags)reader.{readerMethod}();");
        foreach (var prop in replicableProps)
        {
            var propName = DefTypeHelper.ToPropertyName(prop.Name);
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            var readMethod = DefTypeHelper.ReadMethod(prop.Type);
            sb.AppendLine($"        if ((flags & ReplicatedDirtyFlags.{propName}) != 0)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var old{propName} = {fieldName};");
            sb.AppendLine($"            {fieldName} = reader.{readMethod}();");
            sb.AppendLine($"            On{propName}Changed(old{propName}, {fieldName});");
            sb.AppendLine("        }");
        }
        sb.AppendLine("    }");
    }

    private static void EmitScopeApply(StringBuilder sb, List<PropertyDefModel> props,
                                       string methodName)
    {
        // Direct-to-backing-field writes: a snapshot is an authoritative
        // state reset, not an observed change, so property-change callbacks
        // (OnXxxChanged, emitted by PropertiesEmitter) MUST NOT fire here.
        // Setter callbacks on the delta path live in a separate method.
        sb.AppendLine($"    public override void {methodName}(ref SpanReader reader)");
        sb.AppendLine("    {");
        foreach (var prop in props)
        {
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            var readMethod = DefTypeHelper.ReadMethod(prop.Type);
            sb.AppendLine($"        {fieldName} = reader.{readMethod}();");
        }
        sb.AppendLine("    }");
    }

    private static void EmitAudienceMasks(StringBuilder sb, List<PropertyDefModel> props)
    {
        string MaskExpr(System.Func<PropertyScope, bool> pred)
        {
            var names = props.Where(p => pred(p.Scope))
                             .Select(p => "ReplicatedDirtyFlags." + DefTypeHelper.ToPropertyName(p.Name))
                             .ToList();
            return names.Count == 0 ? "ReplicatedDirtyFlags.None" : string.Join(" | ", names);
        }

        sb.AppendLine($"    private const ReplicatedDirtyFlags OwnerVisibleMask = {MaskExpr(IsOwnerVisible)};");
        sb.AppendLine($"    private const ReplicatedDirtyFlags OtherVisibleMask = {MaskExpr(IsOtherVisible)};");
    }

    private static void EmitAudienceDeltaSerializer(StringBuilder sb, List<PropertyDefModel> props,
                                                    string methodName, string maskName,
                                                    System.Func<PropertyDefModel, bool> audiencePred)
    {
        var (_, _, writerMethod, _, castPrefix) = GetFlagsTypeInfo(props.Count);
        sb.AppendLine($"    public void {methodName}(ref SpanWriter writer)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var flags = _dirtyFlags & {maskName};");
        sb.AppendLine($"        writer.{writerMethod}({castPrefix}flags);");
        foreach (var prop in props)
        {
            // Only audience-visible props can have their flag set after the
            // mask, so skip the rest at codegen time.
            if (!audiencePred(prop)) continue;
            var propName = DefTypeHelper.ToPropertyName(prop.Name);
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            var writeMethod = DefTypeHelper.WriteMethod(prop.Type);
            sb.AppendLine($"        if ((flags & ReplicatedDirtyFlags.{propName}) != 0)");
            sb.AppendLine($"            writer.{writeMethod}({fieldName});");
        }
        sb.AppendLine("    }");
    }

    private static void EmitBuildAndConsume(StringBuilder sb, bool hasOwnerSnapshot,
                                            bool hasOtherSnapshot)
    {
        // Zero-alloc API: caller owns the four SpanWriters (typically
        // pool-rented once per tick and Reset() between entities). We
        // serialize in-place and return (eventSeq, volatileSeq) through
        // out params. Avoids per-tick byte[] churn that the allocating
        // form caused on high-fanout CellApp pumps.
        sb.AppendLine("    public override bool BuildAndConsumeReplicationFrame(");
        sb.AppendLine("        ref SpanWriter ownerSnapshot, ref SpanWriter otherSnapshot,");
        sb.AppendLine("        ref SpanWriter ownerDelta, ref SpanWriter otherDelta,");
        sb.AppendLine("        out ulong eventSeq, out ulong volatileSeq)");
        sb.AppendLine("    {");
        sb.AppendLine("        bool hasEvent = (_dirtyFlags & (OwnerVisibleMask | OtherVisibleMask)) != ReplicatedDirtyFlags.None;");
        sb.AppendLine("        bool hasVolatile = VolatileDirtyCore;");
        sb.AppendLine("        if (!hasEvent && !hasVolatile)");
        sb.AppendLine("        {");
        sb.AppendLine("            eventSeq = 0; volatileSeq = 0;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (hasEvent)");
        sb.AppendLine("        {");
        sb.AppendLine("            _eventSeq++;");
        if (hasOwnerSnapshot)
            sb.AppendLine("            SerializeForOwnerClient(ref ownerSnapshot);");
        if (hasOtherSnapshot)
            sb.AppendLine("            SerializeForOtherClients(ref otherSnapshot);");
        sb.AppendLine("            SerializeOwnerDelta(ref ownerDelta);");
        sb.AppendLine("            SerializeOtherDelta(ref otherDelta);");
        sb.AppendLine("            _dirtyFlags = ReplicatedDirtyFlags.None;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (hasVolatile)");
        sb.AppendLine("        {");
        sb.AppendLine("            _volatileSeq++;");
        sb.AppendLine("            VolatileDirtyCore = false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        eventSeq = hasEvent ? _eventSeq : 0UL;");
        sb.AppendLine("        volatileSeq = hasVolatile ? _volatileSeq : 0UL;");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
    }

    private static void EmitApplyReplicatedDelta(StringBuilder sb, List<PropertyDefModel> props)
    {
        var (_, _, _, readerMethod, _) = GetFlagsTypeInfo(props.Count);
        sb.AppendLine("    public void ApplyReplicatedDelta(ref SpanReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var flags = (ReplicatedDirtyFlags)reader.{readerMethod}();");
        foreach (var prop in props)
        {
            var propName = DefTypeHelper.ToPropertyName(prop.Name);
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            var readMethod = DefTypeHelper.ReadMethod(prop.Type);
            sb.AppendLine($"        if ((flags & ReplicatedDirtyFlags.{propName}) != 0)");
            sb.AppendLine($"            {fieldName} = reader.{readMethod}();");
        }
        sb.AppendLine("    }");
    }

    private static void EmitScopeSerialize(StringBuilder sb, List<PropertyDefModel> props,
                                            string methodName)
    {
        // SerializeForOwnerClient / SerializeForOtherClients are virtual on ServerEntity
        // so the baseline pump can invoke them polymorphically on any entity.
        sb.AppendLine($"    public override void {methodName}(ref SpanWriter writer)");
        sb.AppendLine("    {");
        foreach (var prop in props)
        {
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            var writeMethod = DefTypeHelper.WriteMethod(prop.Type);
            sb.AppendLine($"        writer.{writeMethod}({fieldName});");
        }
        sb.AppendLine("    }");
    }

    // Delegate to the shared PropertyScopeExtensions helpers so every caller
    // (emitters, DEF008 detection, runtime) resolves scope membership
    // against the same rulebook.
    private static bool IsOwnerVisible(PropertyScope scope) => scope.IsOwnClientVisible();
    private static bool IsOtherVisible(PropertyScope scope) => scope.IsOtherClientsVisible();

    // Decide whether a replicable scope belongs on this process's generated
    // class. Client always sees every replicable property (from its
    // observer-side projection); Server (legacy fallback) also sees
    // everything; Base owns BaseAndClient; Cell owns the rest.
    private static bool IsOnThisSide(PropertyScope scope, ProcessContext ctx) => ctx switch
    {
        ProcessContext.Base => scope.IsBase(),
        ProcessContext.Cell => scope.IsCell(),
        _ => true,  // Client, Server — emit everything the caller has already filtered
    };

    private static (string BackingType, string FlagSuffix, string WriterMethod, string ReaderMethod, string CastPrefix) GetFlagsTypeInfo(int fieldCount)
    {
        if (fieldCount <= 8) return ("byte", "u", "WriteByte", "ReadByte", "(byte)");
        if (fieldCount <= 16) return ("ushort", "u", "WriteUInt16", "ReadUInt16", "(ushort)");
        if (fieldCount <= 32) return ("uint", "u", "WriteUInt32", "ReadUInt32", "(uint)");
        return ("ulong", "UL", "WriteUInt64", "ReadUInt64", "(ulong)");
    }
}
