using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

// Hashes the entity-def surface that affects RPC routing and replication
// layout, so a client / server with diverged .def files refuses to handshake
// instead of silently misrouting RPCs at runtime. Inputs are normalized in
// stable order — manifest type_id for entities, struct id for structs,
// declaration order for properties / methods / fields.
internal static class DigestEmitter
{
    public const string Header = "ATLAS_DEF_DIGEST_v1";

    public static string Emit(IEnumerable<EntityDefModel> defs,
                              List<StructDefModel> structs,
                              List<ComponentDefModel> standaloneComponents,
                              Dictionary<string, ushort> typeIndexMap)
    {
        var canonical = BuildCanonical(defs, structs, standaloneComponents, typeIndexMap);
        byte[] hashBytes;
        using (var sha = SHA256.Create())
        {
            hashBytes = sha.ComputeHash(Encoding.UTF8.GetBytes(canonical));
        }
        var hex = new StringBuilder(hashBytes.Length * 2);
        foreach (var b in hashBytes) hex.Append(b.ToString("X2"));

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Atlas.Rpc;");
        sb.AppendLine();
        sb.AppendLine("public static class EntityDefDigest");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string Sha256Hex = \"{hex}\";");
        sb.AppendLine();
        sb.AppendLine("    private static readonly byte[] s_bytes = new byte[]");
        sb.AppendLine("    {");
        for (int i = 0; i < hashBytes.Length; i += 8)
        {
            sb.Append("        ");
            for (int j = i; j < hashBytes.Length && j < i + 8; j++)
                sb.Append($"0x{hashBytes[j]:X2}, ");
            sb.AppendLine();
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static System.ReadOnlySpan<byte> Bytes => s_bytes;");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string BuildCanonical(IEnumerable<EntityDefModel> defs,
                                         List<StructDefModel> structs,
                                         List<ComponentDefModel> standaloneComponents,
                                         Dictionary<string, ushort> typeIndexMap)
    {
        var sb = new StringBuilder();
        sb.Append(Header).Append('\n');

        sb.Append("STRUCTS\n");
        foreach (var s in structs.OrderBy(s => s.Id))
        {
            sb.Append("S|").Append(s.Id).Append('|').Append(s.Name).Append('|')
              .Append(s.SyncMode).Append('\n');
            for (int i = 0; i < s.Fields.Count; i++)
            {
                var f = s.Fields[i];
                sb.Append("F|").Append(i).Append('|').Append(f.Name).Append('|');
                AppendTypeRef(sb, f.Type);
                sb.Append('\n');
            }
        }

        sb.Append("ENTITIES\n");
        var ordered = defs.Where(d => typeIndexMap.ContainsKey(d.Name))
                          .OrderBy(d => typeIndexMap[d.Name]);
        foreach (var def in ordered)
        {
            ushort typeId = typeIndexMap[def.Name];
            sb.Append("E|").Append(def.Name).Append('|').Append(typeId).Append('|')
              .Append(def.HasCell ? '1' : '0').Append('|')
              .Append(def.HasClient ? '1' : '0').Append('\n');
            AppendProperties(sb, def.Properties);
            AppendMethods(sb, "client", def.ClientMethods);
            AppendMethods(sb, "cell", def.CellMethods);
            AppendMethods(sb, "base", def.BaseMethods);
            foreach (var c in def.Components.OrderBy(c => c.SlotIdx))
            {
                sb.Append("C|").Append(c.SlotIdx).Append('|').Append(c.TypeName).Append('|')
                  .Append(c.Scope).Append('|').Append(c.Locality).Append('\n');
            }
        }

        sb.Append("COMPONENTS\n");
        foreach (var c in standaloneComponents.OrderBy(c => c.TypeName, StringComparer.Ordinal))
        {
            sb.Append("K|").Append(c.TypeName).Append('|').Append(c.Locality).Append('\n');
            AppendProperties(sb, c.Properties);
            AppendMethods(sb, "client", c.ClientMethods);
            AppendMethods(sb, "cell", c.CellMethods);
            AppendMethods(sb, "base", c.BaseMethods);
        }

        return sb.ToString();
    }

    private static void AppendProperties(StringBuilder sb, List<PropertyDefModel> props)
    {
        for (int i = 0; i < props.Count; i++)
        {
            var p = props[i];
            sb.Append("P|").Append(i).Append('|').Append(p.Name).Append('|')
              .Append(p.Scope).Append('|')
              .Append(p.Persistent ? '1' : '0').Append('|')
              .Append(p.Reliable ? '1' : '0').Append('|');
            if (p.TypeRef != null)
                AppendTypeRef(sb, p.TypeRef);
            else
                sb.Append(p.Type);
            sb.Append('\n');
        }
    }

    private static void AppendMethods(StringBuilder sb, string dirTag, List<MethodDefModel> methods)
    {
        for (int i = 0; i < methods.Count; i++)
        {
            var m = methods[i];
            sb.Append("M|").Append(dirTag).Append('|').Append(i).Append('|').Append(m.Name)
              .Append('|').Append(m.Exposed).Append('|');
            for (int j = 0; j < m.Args.Count; j++)
            {
                if (j > 0) sb.Append(',');
                if (m.Args[j].TypeRef != null) AppendTypeRef(sb, m.Args[j].TypeRef!);
                else sb.Append(m.Args[j].Type);
            }
            sb.Append('|');
            if (m.HasReply && m.ReplyTypeRef != null)
                AppendTypeRef(sb, m.ReplyTypeRef);
            sb.Append('\n');
        }
    }

    private static void AppendTypeRef(StringBuilder sb, DataTypeRefModel t)
    {
        switch (t.Kind)
        {
            case PropertyDataKind.List:
                sb.Append("list[");
                if (t.Elem != null) AppendTypeRef(sb, t.Elem);
                sb.Append(']');
                break;
            case PropertyDataKind.Dict:
                sb.Append("dict[");
                if (t.Key != null) AppendTypeRef(sb, t.Key);
                sb.Append(',');
                if (t.Elem != null) AppendTypeRef(sb, t.Elem);
                sb.Append(']');
                break;
            case PropertyDataKind.Struct:
                sb.Append("struct{").Append(t.StructName ?? "?").Append(':')
                  .Append(t.StructId).Append('}');
                break;
            default:
                sb.Append(t.Kind);
                break;
        }
    }
}
