using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

internal static class DispatcherEmitter
{
    /// <summary>
    /// Emit RPC dispatchers. Only generates dispatch methods for the Receive direction
    /// in the current process context.
    /// </summary>
    public static string Emit(List<(EntityDefModel Def, string ClassName, string Namespace)> entities,
                              ProcessContext ctx, Dictionary<string, ushort> typeIndexMap,
                              string baseClass)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();
        sb.AppendLine("namespace Atlas.Rpc;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class DefRpcDispatcher");
        sb.AppendLine("{");

        // Determine which directions have Receive methods
        var directions = GetReceiveDirections(ctx);

        foreach (var (direction, dirName, section) in directions)
        {
            EmitTopLevelDispatch(sb, entities, ctx, typeIndexMap, direction, dirName, section, baseClass);
        }

        // Per-entity dispatch methods
        foreach (var (def, className, ns) in entities)
        {
            if (!typeIndexMap.TryGetValue(def.Name, out var typeIndex))
                continue;
            var fullName = string.IsNullOrEmpty(ns) ? className : $"{ns}.{className}";

            foreach (var (direction, dirName, section) in directions)
            {
                var methods = GetMethodsForSection(def, section);
                EmitEntityDispatch(sb, fullName, className, methods, typeIndex, direction, dirName);
            }
        }

        // Module initializer to register dispatchers
        sb.AppendLine();
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void RegisterDefDispatchers()");
        sb.AppendLine("    {");
        if (ctx == ProcessContext.Client)
        {
            // Client uses Atlas.Client.ClientCallbacks
            foreach (var (direction, dirName, _) in directions)
            {
                if (dirName == "ClientRpc")
                    sb.AppendLine($"        Atlas.Client.ClientCallbacks.ClientRpcDispatcher = Dispatch{dirName};");
            }
        }
        else
        {
            // Server uses Atlas.Core.RpcBridge
            foreach (var (direction, dirName, _) in directions)
            {
                sb.AppendLine($"        Atlas.Core.RpcBridge.Dispatchers[{direction}] = Dispatch{dirName};");
            }
        }
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitTopLevelDispatch(StringBuilder sb,
        List<(EntityDefModel Def, string ClassName, string Namespace)> entities,
        ProcessContext ctx, Dictionary<string, ushort> typeIndexMap,
        byte direction, string dirName, string section, string baseClass)
    {
        sb.AppendLine();
        sb.AppendLine($"    public static void Dispatch{dirName}({baseClass} target, int rpcId, ref SpanReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (target)");
        sb.AppendLine("        {");
        foreach (var (def, className, ns) in entities)
        {
            var methods = GetMethodsForSection(def, section);
            if (methods.Count == 0) continue;
            var fullName = string.IsNullOrEmpty(ns) ? className : $"{ns}.{className}";
            sb.AppendLine($"            case {fullName} t: Dispatch_{className}_{dirName}(t, rpcId, ref reader); break;");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void EmitEntityDispatch(StringBuilder sb, string fullName, string className,
        List<MethodDefModel> methods, ushort typeIndex, byte direction, string dirName)
    {
        if (methods.Count == 0) return;

        sb.AppendLine();
        sb.AppendLine($"    private static void Dispatch_{className}_{dirName}({fullName} target, int rpcId, ref SpanReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (rpcId)");
        sb.AppendLine("        {");

        var sorted = methods.OrderBy(m => m.Name).ToList();
        for (int i = 0; i < sorted.Count; i++)
        {
            var method = sorted[i];
            int id = (direction << 22) | (typeIndex << 8) | (i + 1);
            sb.AppendLine($"            case 0x{id:X6}:");
            sb.AppendLine("            {");
            foreach (var arg in method.Args)
            {
                sb.AppendLine($"                var {arg.Name} = reader.{DefTypeHelper.ReadMethod(arg.Type)}();");
            }
            var args = string.Join(", ", method.Args.Select(a => a.Name));
            sb.AppendLine($"                target.{method.Name}({args});");
            sb.AppendLine("                break;");
            sb.AppendLine("            }");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static List<MethodDefModel> GetMethodsForSection(EntityDefModel def, string section)
    {
        return section switch
        {
            "client_methods" => def.ClientMethods,
            "cell_methods" => def.CellMethods,
            "base_methods" => def.BaseMethods,
            _ => new List<MethodDefModel>(),
        };
    }

    private static List<(byte Direction, string Name, string Section)> GetReceiveDirections(ProcessContext ctx)
    {
        var result = new List<(byte, string, string)>();
        switch (ctx)
        {
            case ProcessContext.Base:
            case ProcessContext.Server:
                result.Add((0x03, "BaseRpc", "base_methods"));
                break;
            case ProcessContext.Cell:
                result.Add((0x02, "CellRpc", "cell_methods"));
                break;
            case ProcessContext.Client:
                result.Add((0x00, "ClientRpc", "client_methods"));
                break;
        }
        return result;
    }
}
