using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

internal static class DispatcherEmitter
{
    /// <summary>
    /// Emit RPC dispatchers. Only generates dispatch methods for the Receive direction
    /// in the current process context.
    /// </summary>
    public static string Emit(List<(EntityDefModel Def, string ClassName, string Namespace)> entities,
                              ProcessContext ctx, Dictionary<string, ushort> typeIndexMap,
                              string baseClass,
                              List<ComponentDefModel>? allComponents = null)
    {
        allComponents ??= new List<ComponentDefModel>();
        // Component-side receive: only Synced classes show up on the wire.
        var syncedComponents = allComponents
            .Where(c => c.Locality == ComponentLocality.Synced)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Atlas.Coro;");
        sb.AppendLine("using Atlas.Coro.Rpc;");
        sb.AppendLine("using Atlas.Runtime.Coro;");
        sb.AppendLine("using Atlas.Serialization;");
        // Lets struct args (RPC params with TypeRef.Kind==Struct) resolve
        // unqualified — StructEmitter places them in Atlas.Def.
        sb.AppendLine("using Atlas.Def;");
        sb.AppendLine();
        sb.AppendLine("namespace Atlas.Rpc;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class DefRpcDispatcher");
        sb.AppendLine("{");

        // Determine which directions have Receive methods
        var directions = GetReceiveDirections(ctx);

        foreach (var (direction, dirName, section) in directions)
        {
            EmitTopLevelDispatch(sb, entities, syncedComponents, typeIndexMap, direction,
                                 dirName, section, baseClass, ctx);
        }

        // Per-entity dispatch methods
        foreach (var (def, className, ns) in entities)
        {
            if (!typeIndexMap.TryGetValue(def.Name, out var typeIndex))
                continue;
            var fullName = string.IsNullOrEmpty(ns) ? className : $"{ns}.{className}";

            foreach (var (direction, dirName, section) in directions)
            {
                var methods = GetMethodsForSection(def, section);
                EmitEntityDispatch(sb, fullName, className, methods, typeIndex, direction, dirName,
                                   ctx);
            }
        }

        // Per-component dispatch methods. Component RPCs route via
        // (slot, methodIdx); typeIndex is the entity's, but the dispatcher
        // body switches on `methodIdx` and casts to the component class so
        // a single component type used by multiple entities still works.
        foreach (var c in syncedComponents)
        {
            foreach (var (direction, dirName, section) in directions)
            {
                var methods = GetComponentMethodsForSection(c, section);
                EmitComponentDispatch(sb, c.TypeName, methods, direction, dirName, ctx);
            }
        }

        // Module initializer to register dispatchers
        sb.AppendLine();
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void RegisterDefDispatchers()");
        sb.AppendLine("    {");
        if (ctx == ProcessContext.Client)
        {
            // Client uses Atlas.Client.ClientCallbacks
            foreach (var (direction, dirName, _) in directions)
            {
                if (dirName == "ClientRpc")
                    sb.AppendLine($"        Atlas.Client.ClientCallbacks.ClientRpcDispatcher = Dispatch{dirName};");
            }
        }
        else
        {
            // Server uses Atlas.Core.RpcBridge
            foreach (var (direction, dirName, _) in directions)
            {
                sb.AppendLine($"        Atlas.Core.RpcBridge.Dispatchers[{direction}] = Dispatch{dirName};");
            }
        }
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    // Server dispatchers receive a reply-channel handle (Channel* recast).
    // Client never replies, so its dispatcher uses the legacy 3-arg shape.
    private static void EmitTopLevelDispatch(StringBuilder sb,
        List<(EntityDefModel Def, string ClassName, string Namespace)> entities,
        List<ComponentDefModel> syncedComponents,
        Dictionary<string, ushort> typeIndexMap,
        byte direction, string dirName, string section, string baseClass,
        ProcessContext ctx)
    {
        bool serverSide = ctx != ProcessContext.Client;
        var sigParams = serverSide
            ? $"{baseClass} target, int rpcId, IntPtr replyChannel, ref SpanReader reader"
            : $"{baseClass} target, int rpcId, ref SpanReader reader";
        var forwardArgs = serverSide ? "rpcId, replyChannel, ref reader" : "rpcId, ref reader";

        sb.AppendLine();
        sb.AppendLine($"    public static void Dispatch{dirName}({sigParams})");
        sb.AppendLine("    {");
        sb.AppendLine("        int slot = (rpcId >> 24) & 0x7F;");
        sb.AppendLine("        if (slot == 0)");
        sb.AppendLine("        {");

        sb.AppendLine("            switch (target)");
        sb.AppendLine("            {");
        int emittedEntityCases = 0;
        foreach (var (def, className, ns) in entities)
        {
            var methods = GetMethodsForSection(def, section);
            if (methods.Count == 0) continue;
            var fullName = string.IsNullOrEmpty(ns) ? className : $"{ns}.{className}";
            sb.AppendLine($"                case {fullName} t: Dispatch_{className}_{dirName}(t, {forwardArgs}); break;");
            emittedEntityCases++;
        }
        if (emittedEntityCases == 0)
            sb.AppendLine("                default: _ = rpcId; _ = reader; break;");
        else
            sb.AppendLine("                default: break;");
        sb.AppendLine("            }");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");

        var componentsWithMethods = syncedComponents
            .Where(c => GetComponentMethodsForSection(c, section).Count > 0)
            .ToList();
        if (componentsWithMethods.Count > 0)
        {
            sb.AppendLine("        var components = target._replicated;");
            sb.AppendLine("        if (components == null || slot >= components.Length) return;");
            sb.AppendLine("        var comp = components[slot];");
            sb.AppendLine("        if (comp == null) return;");
            sb.AppendLine("        switch (comp)");
            sb.AppendLine("        {");
            foreach (var c in componentsWithMethods)
            {
                var fq = $"global::{ComponentEmitter.ComponentNamespace}.{c.TypeName}";
                sb.AppendLine($"            case {fq} cc: Dispatch_{c.TypeName}_{dirName}(cc, {forwardArgs}); break;");
            }
            sb.AppendLine("            default: break;");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine("        _ = rpcId; _ = reader;");
            if (serverSide) sb.AppendLine("        _ = replyChannel;");
        }
        sb.AppendLine("    }");
    }

    private static void EmitEntityDispatch(StringBuilder sb, string fullName, string className,
        List<MethodDefModel> methods, ushort typeIndex, byte direction, string dirName,
        ProcessContext ctx)
    {
        if (methods.Count == 0) return;

        bool serverSide = ctx != ProcessContext.Client;
        var sig = serverSide
            ? $"{fullName} target, int rpcId, IntPtr replyChannel, ref SpanReader reader"
            : $"{fullName} target, int rpcId, ref SpanReader reader";

        // Static reply serializers — emitted once per reply-method per
        // dispatcher type, closure-free by construction.
        if (serverSide)
        {
            for (int i = 0; i < methods.Count; i++)
            {
                if (!methods[i].HasReply) continue;
                EmitReplySerializerField(sb, methods[i], className);
            }
        }

        sb.AppendLine();
        sb.AppendLine($"    private static void Dispatch_{className}_{dirName}({sig})");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (rpcId)");
        sb.AppendLine("        {");

        var sorted = methods.OrderBy(m => m.Name).ToList();
        for (int i = 0; i < sorted.Count; i++)
        {
            var method = sorted[i];
            int baseId = RpcIdEncoder.Encode(slot: 0, direction, typeIndex, i + 1);
            if (serverSide && method.HasReply)
                EmitReplyCase(sb, method, baseId, "target", className);
            else
                EmitFireAndForgetCase(sb, method, baseId);
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void EmitFireAndForgetCase(StringBuilder sb, MethodDefModel method, int id)
    {
        sb.AppendLine($"            case 0x{id:X6}:");
        sb.AppendLine("            {");
        var argLocals = new List<string>(method.Args.Count);
        foreach (var arg in method.Args)
            argLocals.Add(RpcArgCodec.EmitRead(sb, arg, "reader", "                "));
        sb.AppendLine($"                target.{method.Name}({string.Join(", ", argLocals)});");
        sb.AppendLine("                break;");
        sb.AppendLine("            }");
    }

    private static void EmitReplyCase(StringBuilder sb, MethodDefModel method, int baseId,
                                      string targetExpr, string typeName)
    {
        var idWithBit = unchecked((uint)baseId) | RpcIdEncoder.kReplyBit;
        sb.AppendLine($"            case unchecked((int)0x{idWithBit:X8}):");
        sb.AppendLine("            {");
        sb.AppendLine("                uint requestId = reader.ReadUInt32();");
        var argLocals = new List<string>(method.Args.Count);
        foreach (var arg in method.Args)
            argLocals.Add(RpcArgCodec.EmitRead(sb, arg, "reader", "                "));
        sb.AppendLine($"                var __task = {targetExpr}.{method.Name}({string.Join(", ", argLocals)});");
        sb.AppendLine($"                EntityRpcReplyHelpers.SendReplyOnComplete(__task, replyChannel, requestId,");
        sb.AppendLine($"                    s_{typeName}_{method.Name}ReplySerializer);");
        sb.AppendLine("                break;");
        sb.AppendLine("            }");
    }

    private static void EmitReplySerializerField(StringBuilder sb, MethodDefModel method,
                                                 string ownerName)
    {
        var replyType = PropertyCodec.CSharpTypeForStructField(method.ReplyTypeRef!);
        sb.AppendLine();
        sb.AppendLine($"    private static readonly EntityRpcReplyHelpers.ReplySerializer<{replyType}> s_{ownerName}_{method.Name}ReplySerializer =");
        sb.AppendLine($"        static (ref SpanWriter w, {replyType} value) =>");
        sb.AppendLine("        {");
        var names = new PropertyCodec.NameGen();
        PropertyCodec.EmitElementWrite(sb, method.ReplyTypeRef!, "w", "value", "            ", names);
        sb.AppendLine("        };");
    }

    // Component-level dispatch: switches on methodIdx (low 8 bits of rpc_id)
    // because the typeIndex bits are the entity's, not the component's, and
    // would vary across the (entity, slot) combinations a single component
    // class can occupy.
    private static void EmitComponentDispatch(StringBuilder sb, string componentTypeName,
        List<MethodDefModel> methods, byte direction, string dirName, ProcessContext ctx)
    {
        if (methods.Count == 0) return;

        bool serverSide = ctx != ProcessContext.Client;
        var fq = $"global::{ComponentEmitter.ComponentNamespace}.{componentTypeName}";
        var sig = serverSide
            ? $"{fq} target, int rpcId, IntPtr replyChannel, ref SpanReader reader"
            : $"{fq} target, int rpcId, ref SpanReader reader";

        if (serverSide)
        {
            for (int i = 0; i < methods.Count; i++)
            {
                if (!methods[i].HasReply) continue;
                EmitReplySerializerField(sb, methods[i], componentTypeName);
            }
        }

        sb.AppendLine();
        sb.AppendLine($"    private static void Dispatch_{componentTypeName}_{dirName}({sig})");
        sb.AppendLine("    {");
        sb.AppendLine("        int methodIdx = rpcId & 0xFF;");
        sb.AppendLine("        switch (methodIdx)");
        sb.AppendLine("        {");

        var sorted = methods.OrderBy(m => m.Name).ToList();
        for (int i = 0; i < sorted.Count; i++)
        {
            var method = sorted[i];
            sb.AppendLine($"            case {i + 1}:");
            sb.AppendLine("            {");
            if (serverSide && method.HasReply)
            {
                sb.AppendLine("                uint requestId = reader.ReadUInt32();");
                var argLocals = new List<string>(method.Args.Count);
                foreach (var arg in method.Args)
                    argLocals.Add(RpcArgCodec.EmitRead(sb, arg, "reader", "                "));
                sb.AppendLine($"                var __task = target.{method.Name}({string.Join(", ", argLocals)});");
                sb.AppendLine($"                EntityRpcReplyHelpers.SendReplyOnComplete(__task, replyChannel, requestId,");
                sb.AppendLine($"                    s_{componentTypeName}_{method.Name}ReplySerializer);");
                sb.AppendLine("                break;");
            }
            else
            {
                var argLocals = new List<string>(method.Args.Count);
                foreach (var arg in method.Args)
                    argLocals.Add(RpcArgCodec.EmitRead(sb, arg, "reader", "                "));
                sb.AppendLine($"                target.{method.Name}({string.Join(", ", argLocals)});");
                sb.AppendLine("                break;");
            }
            sb.AppendLine("            }");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static List<MethodDefModel> GetMethodsForSection(EntityDefModel def, string section)
    {
        return section switch
        {
            "client_methods" => def.ClientMethods,
            "cell_methods" => def.CellMethods,
            "base_methods" => def.BaseMethods,
            _ => new List<MethodDefModel>(),
        };
    }

    private static List<MethodDefModel> GetComponentMethodsForSection(ComponentDefModel c, string section)
    {
        return section switch
        {
            "client_methods" => c.ClientMethods,
            "cell_methods" => c.CellMethods,
            "base_methods" => c.BaseMethods,
            _ => new List<MethodDefModel>(),
        };
    }

    private static List<(byte Direction, string Name, string Section)> GetReceiveDirections(ProcessContext ctx)
    {
        var result = new List<(byte, string, string)>();
        switch (ctx)
        {
            case ProcessContext.Base:
            case ProcessContext.Server:
                result.Add((0x03, "BaseRpc", "base_methods"));
                break;
            case ProcessContext.Cell:
                result.Add((0x02, "CellRpc", "cell_methods"));
                break;
            case ProcessContext.Client:
                result.Add((0x00, "ClientRpc", "client_methods"));
                break;
        }
        return result;
    }
}
