using System.Text;

namespace Atlas.Generators.Def.Emitters;

// Canonical file prologue for any .g.cs the generator emits. Centralised
// so a new emitter can't forget the Atlas.Def using — when an emitter
// references a generated struct without it, the user sees CS0103 in the
// generated code instead of an obvious diagnostic.
internal static class EmitterHeader
{
    // Writes the four prologue lines + an optional `namespace X;` line +
    // a trailing blank line. Leaves the caller positioned to emit a
    // class/struct declaration directly.
    public static void Write(StringBuilder sb, string? namespaceName = null)
    {
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine($"using {StructEmitter.StructNamespace};");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }
    }
}
