using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

// Emits the entity-side partial that wires the Component slot table:
//   * SyncedSlotCount override (declared component count)
//   * ResolveSyncedSlot(Type) — Type → slot lookup with O(N) chain;
//     N is small per design, so unrolled `if`s outpace any dispatch
//     table at this scale and keep the JIT happy.
//   * Typed accessor per Synced slot — `entity.Combat` returns
//     `CombatComponent?` so scripts read state with zero boxing.
//   * Local-component accessor — `entity.Ai` returns ServerLocal type
//     queried by Type.
//   * Per-audience helpers used by the replication pump:
//       HasOwnerDirtyComponent / HasOtherDirtyComponent — pre-scan
//       so the entity's sectionMask byte can advertise bit 2.
//       WriteOwnerComponentSection / WriteOtherComponentSection —
//       count + per-slot dispatch into each component's WriteXxxDelta.
//       ClearDirtyComponents — runs after BOTH audiences have been
//       written so each component is reset for the next tick.
internal static class EntityComponentAccessorEmitter
{
    public static string? Emit(EntityDefModel def, string className, string namespaceName,
                               ProcessContext ctx)
    {
        if (def.Components.Count == 0) return null;

        bool isClient = ctx == ProcessContext.Client;
        // Client doesn't host ServerLocal components, server doesn't host
        // ClientLocal — drop accessors that don't apply to this side.
        var allowedLocalities = isClient
            ? new[] { ComponentLocality.Synced, ComponentLocality.ClientLocal }
            : new[] { ComponentLocality.Synced, ComponentLocality.ServerLocal };

        var syncedComponents = def.Components
            .Where(c => c.Locality == ComponentLocality.Synced)
            .ToList();
        var syncedCount = syncedComponents.Count;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine($"using {ComponentEmitter.ComponentNamespace};");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }
        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");

        sb.AppendLine($"    protected override int SyncedSlotCount => {syncedCount};");
        sb.AppendLine();
        sb.AppendLine("    protected override int ResolveSyncedSlot(Type componentType)");
        sb.AppendLine("    {");
        foreach (var c in def.Components)
        {
            if (c.Locality != ComponentLocality.Synced) continue;
            sb.AppendLine($"        if (componentType == typeof(global::{ComponentEmitter.ComponentNamespace}.{c.TypeName})) return {c.SlotIdx};");
        }
        sb.AppendLine("        return -1;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Typed accessors. Synced slots return null until AddComponent
        // activates them; non-lazy components are typically added by
        // the entity's OnInit, so script code rarely sees null.
        foreach (var c in def.Components)
        {
            if (System.Array.IndexOf(allowedLocalities, c.Locality) < 0) continue;
            var slotName = DefTypeHelper.ToPropertyName(c.SlotName);
            if (c.Locality == ComponentLocality.Synced)
            {
                sb.AppendLine($"    public global::{ComponentEmitter.ComponentNamespace}.{c.TypeName}? {slotName} => GetSyncedComponent<global::{ComponentEmitter.ComponentNamespace}.{c.TypeName}>();");
            }
            else  // ServerLocal on server, ClientLocal on client — both go through GetLocalComponent
            {
                sb.AppendLine($"    public global::{ComponentEmitter.ComponentNamespace}.{c.TypeName}? {slotName} => GetLocalComponent<global::{ComponentEmitter.ComponentNamespace}.{c.TypeName}>();");
            }
        }
        sb.AppendLine();

        if (syncedCount > 0)
        {
            if (isClient)
            {
                // Client: dispatch each per-slot delta into the matching
                // component instance's ApplyDelta. We trust matched defs —
                // unknown slot id means version skew and is fatal because
                // we can't safely skip without a per-component byte length.
                EmitClientApplyComponentSection(sb, syncedComponents);
            }
            else
            {
                // Server: replication-pump helpers. _dirtyComponents == 0
                // is the fast path — no scan, just say "nothing to do".
                // Otherwise iterate declared synced slots only; foreign
                // slot ids should never appear in this entity's bitmap.
                EmitAudiencePredicate(sb, syncedComponents, "HasOwnerDirtyComponent",
                                      "HasOwnerDirty");
                sb.AppendLine();
                EmitAudiencePredicate(sb, syncedComponents, "HasOtherDirtyComponent",
                                      "HasOtherDirty");
                sb.AppendLine();
                EmitComponentSectionWriter(sb, syncedComponents, "WriteOwnerComponentSection",
                                           "HasOwnerDirty", "WriteOwnerDelta");
                sb.AppendLine();
                EmitComponentSectionWriter(sb, syncedComponents, "WriteOtherComponentSection",
                                           "HasOtherDirty", "WriteOtherDelta");
                sb.AppendLine();
                EmitClearDirtyComponents(sb, syncedComponents);
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // Client-side component-section reader. Wire layout is the inverse of
    // EmitComponentSectionWriter: [PackedInt count][per: u8 slot + body].
    private static void EmitClientApplyComponentSection(StringBuilder sb,
                                                         System.Collections.Generic.List<ComponentDefModel> synced)
    {
        sb.AppendLine("    private void ApplyComponentSection(ref SpanReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine("        uint count = reader.ReadPackedUInt32();");
        sb.AppendLine("        for (uint i = 0; i < count; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            int slot = reader.ReadByte();");
        // Lazy-allocate _replicated on first delta arrival so synced
        // components can populate without a prior AddComponent call.
        sb.AppendLine($"            _replicated ??= new global::Atlas.Components.ClientReplicatedComponent?[{synced.Count + 1}];");
        sb.AppendLine("            switch (slot)");
        sb.AppendLine("            {");
        foreach (var c in synced)
        {
            var typeFq = $"global::{ComponentEmitter.ComponentNamespace}.{c.TypeName}";
            sb.AppendLine($"                case {c.SlotIdx}:");
            sb.AppendLine("                {");
            // Auto-attach on first delta — matches the server's behaviour
            // where AddComponent runs in OnInit. Without this, a fresh
            // observer entering AoI would have nothing to apply to.
            sb.AppendLine($"                    if (_replicated[{c.SlotIdx}] is not {typeFq} c{c.SlotIdx})");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        c{c.SlotIdx} = new {typeFq}();");
            sb.AppendLine($"                        c{c.SlotIdx}.__Bind(this, {c.SlotIdx});");
            sb.AppendLine($"                        _replicated[{c.SlotIdx}] = c{c.SlotIdx};");
            sb.AppendLine($"                        c{c.SlotIdx}.OnAttached();");
            sb.AppendLine("                    }");
            sb.AppendLine($"                    c{c.SlotIdx}.ApplyDelta(ref reader);");
            sb.AppendLine("                    break;");
            sb.AppendLine("                }");
        }
        sb.AppendLine("                default:");
        sb.AppendLine("                    // Unknown slot: matched defs make this unreachable. Bail");
        sb.AppendLine("                    // out so subsequent components don't get mis-parsed; the");
        sb.AppendLine("                    // entity manager surfaces a desync warning on the next");
        sb.AppendLine("                    // event_seq gap.");
        sb.AppendLine("                    return;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    // Pre-scan a single audience: returns true on first dirty slot whose
    // component has audience-visible bits. Lets the entity-level
    // SerializeOwnerDelta / SerializeOtherDelta decide whether to set
    // sectionMask bit 2 BEFORE writing the byte.
    private static void EmitAudiencePredicate(StringBuilder sb,
                                               System.Collections.Generic.List<ComponentDefModel> synced,
                                               string methodName,
                                               string componentPredicate)
    {
        sb.AppendLine($"    private bool {methodName}()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_dirtyComponents == 0UL || _replicated == null) return false;");
        foreach (var c in synced)
        {
            sb.AppendLine($"        if ((_dirtyComponents & (1UL << {c.SlotIdx})) != 0UL " +
                          $"&& _replicated[{c.SlotIdx}] is global::{ComponentEmitter.ComponentNamespace}.{c.TypeName} c{c.SlotIdx} " +
                          $"&& c{c.SlotIdx}.{componentPredicate}()) return true;");
        }
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
    }

    // Wire layout produced here:
    //   [PackedInt count]
    //   for each dirty slot with audience-visible bits:
    //     [u8 slot_idx]
    //     [per-component delta]   // emitted by component.WriteXxxDelta
    private static void EmitComponentSectionWriter(StringBuilder sb,
                                                    System.Collections.Generic.List<ComponentDefModel> synced,
                                                    string methodName,
                                                    string componentPredicate,
                                                    string componentWriter)
    {
        sb.AppendLine($"    private void {methodName}(ref SpanWriter writer)");
        sb.AppendLine("    {");
        sb.AppendLine("        // Two passes: count first so the wire carries an exact dirty");
        sb.AppendLine("        // count, then write. _replicated is non-null because the");
        sb.AppendLine("        // caller already established at least one dirty bit exists.");
        sb.AppendLine("        uint count = 0;");
        foreach (var c in synced)
        {
            sb.AppendLine($"        if ((_dirtyComponents & (1UL << {c.SlotIdx})) != 0UL " +
                          $"&& _replicated![{c.SlotIdx}] is global::{ComponentEmitter.ComponentNamespace}.{c.TypeName} a{c.SlotIdx} " +
                          $"&& a{c.SlotIdx}.{componentPredicate}()) count++;");
        }
        sb.AppendLine("        writer.WritePackedUInt32(count);");
        foreach (var c in synced)
        {
            sb.AppendLine($"        if ((_dirtyComponents & (1UL << {c.SlotIdx})) != 0UL " +
                          $"&& _replicated![{c.SlotIdx}] is global::{ComponentEmitter.ComponentNamespace}.{c.TypeName} b{c.SlotIdx} " +
                          $"&& b{c.SlotIdx}.{componentPredicate}())");
            sb.AppendLine("        {");
            sb.AppendLine($"            writer.WriteByte((byte){c.SlotIdx});");
            sb.AppendLine($"            b{c.SlotIdx}.{componentWriter}(ref writer);");
            sb.AppendLine("        }");
        }
        sb.AppendLine("    }");
    }

    // Runs ONCE per tick after both audiences have been written. Each
    // component's _dirtyFlags must persist across the owner→other
    // sequence, so this can't live inside a single audience writer.
    private static void EmitClearDirtyComponents(StringBuilder sb,
                                                  System.Collections.Generic.List<ComponentDefModel> synced)
    {
        sb.AppendLine("    private void ClearDirtyComponents()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_dirtyComponents == 0UL || _replicated == null) return;");
        foreach (var c in synced)
        {
            sb.AppendLine($"        if ((_dirtyComponents & (1UL << {c.SlotIdx})) != 0UL && _replicated[{c.SlotIdx}] is {{ }} c{c.SlotIdx}) c{c.SlotIdx}.ClearDirty();");
        }
        sb.AppendLine("        _dirtyComponents = 0UL;");
        sb.AppendLine("    }");
    }
}
