using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

internal static class FactoryEmitter
{
    public static string Emit(
        List<(EntityDefModel Def, string ClassName, string Namespace)> entities,
        Dictionary<string, ushort> typeIndexMap,
        ProcessContext ctx)
    {
        var sorted = entities.OrderBy(e => e.Def.Name).ToList();
        var registered = new HashSet<string>(sorted.Select(e => e.Def.Name), System.StringComparer.Ordinal);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Atlas.Def;");
        sb.AppendLine();
        sb.AppendLine("internal static class DefEntityFactoryRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    internal static void RegisterAll()");
        sb.AppendLine("    {");
        if (ctx == ProcessContext.Client)
        {
            sb.AppendLine("        RegisterInto(Atlas.Client.ClientEntityFactory.DefaultRegistry);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    internal static void RegisterInto(Atlas.Client.ClientEntityFactoryRegistry registry)");
            sb.AppendLine("    {");
        }

        foreach (var (def, className, ns) in sorted)
        {
            if (!typeIndexMap.TryGetValue(def.Name, out var typeId))
                continue;
            var fullName = string.IsNullOrEmpty(ns) ? className : $"{ns}.{className}";
            if (ctx == ProcessContext.Client)
            {
                sb.AppendLine(
                    $"        registry.Register({typeId}, static () => new {fullName}());");
            }
            else
            {
                sb.AppendLine(
                    $"        Atlas.Entity.EntityFactory.Register("
                    + $"\"{def.Name}\", {typeId}, static () => new {fullName}());");
            }
        }

        // Server emits type-id-only entries for spawnable types without a
        // local class; client only instantiates registered owned types.
        if (ctx != ProcessContext.Client)
        {
            foreach (var kvp in typeIndexMap.OrderBy(kv => kv.Key))
            {
                if (registered.Contains(kvp.Key)) continue;
                sb.AppendLine(
                    $"        Atlas.Entity.EntityFactory.RegisterTypeId("
                    + $"\"{kvp.Key}\", {kvp.Value});");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
