using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

/// <summary>
/// Generates EntityFactory with Create(typeName) and CreateByTypeId(typeId) methods.
/// </summary>
internal static class FactoryEmitter
{
    public static string Emit(
        List<(EntityDefModel Def, string ClassName, string Namespace)> entities,
        Dictionary<string, ushort> typeIndexMap,
        ProcessContext ctx)
    {
        var sorted = entities.OrderBy(e => e.Def.Name).ToList();

        var baseClass = ctx == ProcessContext.Client
            ? "Atlas.Client.ClientEntity"
            : "Atlas.Entity.ServerEntity";

        var factoryNs = ctx == ProcessContext.Client
            ? "Atlas.Client"
            : "Atlas.Entity";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        sb.AppendLine($"namespace {factoryNs};");
        sb.AppendLine();

        sb.AppendLine($"public static partial class EntityFactory");
        sb.AppendLine("{");
        sb.AppendLine($"    private static readonly Dictionary<string, Func<{baseClass}>> _creatorsByName");
        sb.AppendLine("        = new(StringComparer.Ordinal);");
        sb.AppendLine($"    private static readonly Dictionary<ushort, Func<{baseClass}>> _creatorsByTypeId");
        sb.AppendLine("        = new();");
        sb.AppendLine();
        sb.AppendLine("    static EntityFactory()");
        sb.AppendLine("    {");
        foreach (var (def, className, ns) in sorted)
        {
            if (!typeIndexMap.TryGetValue(def.Name, out var typeId))
                continue;
            var fullName = string.IsNullOrEmpty(ns) ? className : $"{ns}.{className}";
            sb.AppendLine($"        _creatorsByName[\"{def.Name}\"] = static () => new {fullName}();");
            sb.AppendLine($"        _creatorsByTypeId[{typeId}] = static () => new {fullName}();");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {baseClass}? Create(string typeName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _creatorsByName.TryGetValue(typeName, out var creator) ? creator() : null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {baseClass}? CreateByTypeId(ushort typeId)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _creatorsByTypeId.TryGetValue(typeId, out var creator) ? creator() : null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
