using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

/// <summary>
/// Emits a <c>[ModuleInitializer]</c>-decorated helper class that registers
/// entity creators with the singleton factory living in Atlas.Runtime /
/// Atlas.Client. The earlier design emitted a <c>partial class EntityFactory</c>
/// expecting cross-assembly partial merging, which doesn't exist — the
/// generated class was a distinct type that neither NativeCallbacks nor
/// ClientCallbacks could see.
/// </summary>
internal static class FactoryEmitter
{
    public static string Emit(
        List<(EntityDefModel Def, string ClassName, string Namespace)> entities,
        Dictionary<string, ushort> typeIndexMap,
        ProcessContext ctx)
    {
        var sorted = entities.OrderBy(e => e.Def.Name).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Atlas.Def;");
        sb.AppendLine();
        sb.AppendLine("internal static class DefEntityFactoryRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    internal static void RegisterAll()");
        sb.AppendLine("    {");

        foreach (var (def, className, ns) in sorted)
        {
            if (!typeIndexMap.TryGetValue(def.Name, out var typeId))
                continue;
            var fullName = string.IsNullOrEmpty(ns) ? className : $"{ns}.{className}";
            if (ctx == ProcessContext.Client)
            {
                sb.AppendLine(
                    $"        Atlas.Client.ClientEntityFactory.Register("
                    + $"{typeId}, static () => new {fullName}());");
            }
            else
            {
                sb.AppendLine(
                    $"        Atlas.Entity.EntityFactory.Register("
                    + $"\"{def.Name}\", {typeId}, static () => new {fullName}());");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
