using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

internal static class MailboxEmitter
{
    public static string Emit(EntityDefModel def, string className, string namespaceName,
                              string baseClass, ProcessContext ctx,
                              Dictionary<string, ushort> typeIndexMap)
    {
        if (!typeIndexMap.TryGetValue(def.Name, out var typeIndex))
            return "";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Atlas.Core;");
        sb.AppendLine("using Atlas.Coro;");
        sb.AppendLine("using Atlas.Coro.Rpc;");
        sb.AppendLine("using Atlas.Protocol;");
        sb.AppendLine("using Atlas.Serialization;");
        // Generated structs land in Atlas.Def — the import lets struct
        // args appear unqualified in the mailbox method signatures.
        sb.AppendLine("using Atlas.Def;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        bool emitClientMailbox = ShouldEmitClientMailbox(ctx);
        bool emitBaseMailbox = ShouldEmitBaseMailbox(ctx);
        bool emitCellMailbox = ShouldEmitCellMailbox(ctx);

        if (emitClientMailbox && def.ClientMethods.Count > 0)
            EmitMailboxStruct(sb, def, className, def.ClientMethods, typeIndex, 0x00,
                              "Client", "SendClientRpc");

        if (emitBaseMailbox && def.BaseMethods.Count > 0)
        {
            var exposedOnly = ctx == ProcessContext.Client;
            EmitMailboxStruct(sb, def, className, def.BaseMethods, typeIndex, 0x03,
                              "Base", "SendBaseRpc", exposedOnly);
        }

        if (emitCellMailbox && def.CellMethods.Count > 0)
        {
            var exposedOnly = ctx == ProcessContext.Client;
            EmitMailboxStruct(sb, def, className, def.CellMethods, typeIndex, 0x02,
                              "Cell", "SendCellRpc", exposedOnly);
        }

        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");
        if (emitClientMailbox && def.ClientMethods.Count > 0)
        {
            sb.AppendLine($"    public {className}ClientMailbox Client => new(this, RpcTarget.Owner);");
            sb.AppendLine($"    public {className}ClientMailbox OtherClients => new(this, RpcTarget.Others);");
            sb.AppendLine($"    public {className}ClientMailbox AllClients => new(this, RpcTarget.All);");
        }
        if (emitBaseMailbox && def.BaseMethods.Count > 0)
            sb.AppendLine($"    public {className}BaseMailbox Base => new(this);");
        if (emitCellMailbox && def.CellMethods.Count > 0)
            sb.AppendLine($"    public {className}CellMailbox Cell => new(this);");
        sb.AppendLine();
        if (emitClientMailbox && def.ClientMethods.Count > 0)
            sb.AppendLine("    internal void InternalSendClientRpc(int rpcId, RpcTarget target, ReadOnlySpan<byte> payload) => SendClientRpc(rpcId, target, payload);");
        if (emitBaseMailbox || emitCellMailbox)
        {
            sb.AppendLine("    internal void InternalSendBaseRpc(int rpcId, ReadOnlySpan<byte> payload) => SendBaseRpc(rpcId, payload);");
            sb.AppendLine("    internal void InternalSendCellRpc(int rpcId, ReadOnlySpan<byte> payload) => SendCellRpc(rpcId, payload);");
        }
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitMailboxStruct(StringBuilder sb, EntityDefModel def, string className,
        List<MethodDefModel> methods, ushort typeIndex, byte direction,
        string mailboxKind, string sendMethod, bool exposedOnly = false)
    {
        var structName = $"{className}{mailboxKind}Mailbox";
        var isClientMailbox = mailboxKind == "Client";
        sb.AppendLine($"public readonly struct {structName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {className} _entity;");
        if (isClientMailbox)
        {
            sb.AppendLine("    private readonly RpcTarget _target;");
            sb.AppendLine($"    internal {structName}({className} entity, RpcTarget target) {{ _entity = entity; _target = target; }}");
        }
        else
        {
            sb.AppendLine($"    internal {structName}({className} entity) => _entity = entity;");
        }

        var sorted = methods.OrderBy(m => m.Name).ToList();

        // Static reply deserializers — one per method-with-reply, defined
        // up-front so the per-call body has no closure / no allocation.
        for (int i = 0; i < sorted.Count; i++)
        {
            var method = sorted[i];
            if (exposedOnly && method.Exposed == ExposedScope.None) continue;
            if (!method.HasReply) continue;
            EmitReplyDeserializerField(sb, method);
        }

        for (int i = 0; i < sorted.Count; i++)
        {
            var method = sorted[i];
            if (exposedOnly && method.Exposed == ExposedScope.None)
                continue;

            int rpcId = RpcIdEncoder.Encode(slot: 0, direction, typeIndex, i + 1);
            sb.AppendLine();
            if (method.HasReply)
                EmitReplyMethod(sb, method, rpcId, sendMethod, isClientMailbox);
            else
                EmitFireAndForgetMethod(sb, method, rpcId, sendMethod, isClientMailbox);
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitFireAndForgetMethod(StringBuilder sb, MethodDefModel method,
                                                int rpcId, string sendMethod, bool isClientMailbox)
    {
        var paramList = RpcArgCodec.BuildParamList(method.Args);
        var sendArgs = isClientMailbox ? "_target, " : "";
        sb.AppendLine($"    public void {method.Name}({paramList})");
        sb.AppendLine("    {");
        if (method.Args.Count == 0)
        {
            sb.AppendLine($"        _entity.Internal{sendMethod}(0x{rpcId:X6}, {sendArgs}ReadOnlySpan<byte>.Empty);");
        }
        else
        {
            sb.AppendLine("        var writer = new SpanWriter(256);");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            foreach (var arg in method.Args)
                RpcArgCodec.EmitWrite(sb, arg, "writer", "            ");
            sb.AppendLine($"            _entity.Internal{sendMethod}(0x{rpcId:X6}, {sendArgs}writer.WrittenSpan);");
            sb.AppendLine("        }");
            sb.AppendLine("        finally { writer.Dispose(); }");
        }
        sb.AppendLine("    }");
    }

    private static void EmitReplyMethod(StringBuilder sb, MethodDefModel method,
                                        int rpcId, string sendMethod, bool isClientMailbox)
    {
        // Reply-style RPCs are not used on the Client mailbox path —
        // P9 (DEF018) rejects reply= on client_methods. Defensive: keep
        // the same rpcId-with-reply-bit shape so future changes won't
        // accidentally diverge.
        var sendArgs = isClientMailbox ? "_target, " : "";
        var paramList = RpcArgCodec.BuildParamList(method.Args);
        var ctParam = paramList.Length > 0 ? ", " : "";
        var replyType = PropertyCodec.CSharpTypeForStructField(method.ReplyTypeRef!);
        var rpcIdWithReplyBit = unchecked((uint)rpcId) | RpcIdEncoder.kReplyBit;

        sb.AppendLine($"    public AtlasTask<RpcReply<{replyType}>> {method.Name}({paramList}{ctParam}AtlasCancellationToken ct = default, int timeoutMs = AtlasRpc.DefaultTimeoutMs)");
        sb.AppendLine("    {");
        sb.AppendLine("        var requestId = AtlasRpc.NextRequestId();");
        sb.AppendLine($"        var src = AtlasRpcSource<RpcReply<{replyType}>>.Rent();");
        sb.AppendLine($"        src.Start(AtlasRpcRegistryHost.Current, MessageIds.EntityRpcReply, requestId,");
        sb.AppendLine($"            s_{method.Name}Deserializer, RpcReplyHelpers.For<{replyType}>(), timeoutMs, ct);");
        sb.AppendLine("        var writer = new SpanWriter(256);");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            writer.WriteUInt32(requestId);");
        foreach (var arg in method.Args)
            RpcArgCodec.EmitWrite(sb, arg, "writer", "            ");
        sb.AppendLine($"            _entity.Internal{sendMethod}(unchecked((int)0x{rpcIdWithReplyBit:X8}), {sendArgs}writer.WrittenSpan);");
        sb.AppendLine("        }");
        sb.AppendLine("        finally { writer.Dispose(); }");
        sb.AppendLine("        return src.Task;");
        sb.AppendLine("    }");
    }

    private static void EmitReplyDeserializerField(StringBuilder sb, MethodDefModel method)
    {
        var replyType = PropertyCodec.CSharpTypeForStructField(method.ReplyTypeRef!);
        sb.AppendLine($"    private static readonly AtlasRpcSource<RpcReply<{replyType}>>.SpanDeserializer s_{method.Name}Deserializer =");
        sb.AppendLine("        static (ref SpanReader r) =>");
        sb.AppendLine("        {");
        var names = new PropertyCodec.NameGen();
        var local = PropertyCodec.EmitElementRead(sb, method.ReplyTypeRef!, "r",
                                                  "            ", names, plainContainers: true);
        sb.AppendLine($"            return RpcReply<{replyType}>.Ok({local});");
        sb.AppendLine("        };");
    }

    private static bool ShouldEmitClientMailbox(ProcessContext ctx)
        => ctx != ProcessContext.Client;

    private static bool ShouldEmitBaseMailbox(ProcessContext ctx)
        => ctx == ProcessContext.Cell || ctx == ProcessContext.Client;

    private static bool ShouldEmitCellMailbox(ProcessContext ctx)
        => ctx == ProcessContext.Base || ctx == ProcessContext.Client || ctx == ProcessContext.Server;
}
