using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

internal static class MailboxEmitter
{
    public static string Emit(EntityDefModel def, string className, string namespaceName,
                              string baseClass, ProcessContext ctx,
                              Dictionary<string, ushort> typeIndexMap)
    {
        if (!typeIndexMap.TryGetValue(def.Name, out var typeIndex))
            return "";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Atlas.Core;");
        sb.AppendLine("using Atlas.Serialization;");
        // Generated structs land in Atlas.Def — the import lets struct
        // args appear unqualified in the mailbox method signatures.
        sb.AppendLine("using Atlas.Def;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        // Determine which mailboxes to generate
        bool emitClientMailbox = ShouldEmitClientMailbox(ctx);
        bool emitBaseMailbox = ShouldEmitBaseMailbox(ctx);
        bool emitCellMailbox = ShouldEmitCellMailbox(ctx);

        // Client mailbox (for calling client_methods)
        if (emitClientMailbox && def.ClientMethods.Count > 0)
            EmitMailboxStruct(sb, def, className, def.ClientMethods, typeIndex, 0x00,
                              "Client", "SendClientRpc");

        // Base mailbox (for calling exposed base_methods from client)
        if (emitBaseMailbox && def.BaseMethods.Count > 0)
        {
            var exposedOnly = ctx == ProcessContext.Client;
            EmitMailboxStruct(sb, def, className, def.BaseMethods, typeIndex, 0x03,
                              "Base", "SendBaseRpc", exposedOnly);
        }

        // Cell mailbox (for calling exposed cell_methods from client)
        if (emitCellMailbox && def.CellMethods.Count > 0)
        {
            var exposedOnly = ctx == ProcessContext.Client;
            EmitMailboxStruct(sb, def, className, def.CellMethods, typeIndex, 0x02,
                              "Cell", "SendCellRpc", exposedOnly);
        }

        // Partial class with mailbox property accessors and internal RPC forwarding
        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");
        if (emitClientMailbox && def.ClientMethods.Count > 0)
        {
            sb.AppendLine($"    public {className}ClientMailbox Client => new(this, RpcTarget.Owner);");
            sb.AppendLine($"    public {className}ClientMailbox OtherClients => new(this, RpcTarget.Others);");
            sb.AppendLine($"    public {className}ClientMailbox AllClients => new(this, RpcTarget.All);");
        }
        if (emitBaseMailbox && def.BaseMethods.Count > 0)
            sb.AppendLine($"    public {className}BaseMailbox Base => new(this);");
        if (emitCellMailbox && def.CellMethods.Count > 0)
            sb.AppendLine($"    public {className}CellMailbox Cell => new(this);");
        sb.AppendLine();
        sb.AppendLine("    // Internal forwarding methods — mailbox structs call these");
        sb.AppendLine("    // because SendXxxRpc is protected internal on the base class.");
        if (emitClientMailbox && def.ClientMethods.Count > 0)
            sb.AppendLine("    internal void InternalSendClientRpc(int rpcId, RpcTarget target, ReadOnlySpan<byte> payload) => SendClientRpc(rpcId, target, payload);");
        if (emitBaseMailbox || emitCellMailbox)
        {
            sb.AppendLine("    internal void InternalSendBaseRpc(int rpcId, ReadOnlySpan<byte> payload) => SendBaseRpc(rpcId, payload);");
            sb.AppendLine("    internal void InternalSendCellRpc(int rpcId, ReadOnlySpan<byte> payload) => SendCellRpc(rpcId, payload);");
        }
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitMailboxStruct(StringBuilder sb, EntityDefModel def, string className,
        List<MethodDefModel> methods, ushort typeIndex, byte direction,
        string mailboxKind, string sendMethod, bool exposedOnly = false)
    {
        var structName = $"{className}{mailboxKind}Mailbox";
        var isClientMailbox = mailboxKind == "Client";
        sb.AppendLine($"public readonly struct {structName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {className} _entity;");
        if (isClientMailbox)
        {
            sb.AppendLine("    private readonly RpcTarget _target;");
            sb.AppendLine($"    internal {structName}({className} entity, RpcTarget target) {{ _entity = entity; _target = target; }}");
        }
        else
        {
            sb.AppendLine($"    internal {structName}({className} entity) => _entity = entity;");
        }

        var sorted = methods.OrderBy(m => m.Name).ToList();
        for (int i = 0; i < sorted.Count; i++)
        {
            var method = sorted[i];
            if (exposedOnly && method.Exposed == ExposedScope.None)
                continue;

            int rpcId = RpcIdEncoder.Encode(slot: 0, direction, typeIndex, i + 1);
            var paramList = RpcArgCodec.BuildParamList(method.Args);
            var sendArgs = isClientMailbox ? "_target, " : "";

            sb.AppendLine();
            sb.AppendLine($"    public void {method.Name}({paramList})");
            sb.AppendLine("    {");
            if (method.Args.Count == 0)
            {
                sb.AppendLine($"        _entity.Internal{sendMethod}(0x{rpcId:X6}, {sendArgs}ReadOnlySpan<byte>.Empty);");
            }
            else
            {
                sb.AppendLine("        var writer = new SpanWriter(256);");
                sb.AppendLine("        try");
                sb.AppendLine("        {");
                foreach (var arg in method.Args)
                    RpcArgCodec.EmitWrite(sb, arg, "writer", "            ");
                sb.AppendLine($"            _entity.Internal{sendMethod}(0x{rpcId:X6}, {sendArgs}writer.WrittenSpan);");
                sb.AppendLine("        }");
                sb.AppendLine("        finally { writer.Dispose(); }");
            }
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string BuildParamList(List<ArgDefModel> args)
    {
        if (args.Count == 0) return "";
        var parts = new string[args.Count];
        for (int i = 0; i < args.Count; i++)
            parts[i] = $"{DefTypeHelper.ToCSharpType(args[i].Type)} {args[i].Name}";
        return string.Join(", ", parts);
    }

    private static bool ShouldEmitClientMailbox(ProcessContext ctx)
        => ctx != ProcessContext.Client;

    private static bool ShouldEmitBaseMailbox(ProcessContext ctx)
        => ctx == ProcessContext.Cell || ctx == ProcessContext.Client;

    private static bool ShouldEmitCellMailbox(ProcessContext ctx)
        => ctx == ProcessContext.Base || ctx == ProcessContext.Client || ctx == ProcessContext.Server;
}
