using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

/// <summary>
/// Generates backing fields, public properties with dirty tracking, DirtyFlags enum,
/// and change callback hooks from .def property definitions.
/// </summary>
internal static class PropertiesEmitter
{
    public static string? Emit(EntityDefModel def, string className, string namespaceName,
                               ProcessContext ctx)
    {
        if (def.Properties.Count == 0) return null;

        // ATLAS_DEF008 dropped up front (spans every ctx): `position` in a
        // replicable scope is a ghost of the ClientEntity base class's
        // Position + the volatile channel, never a real field.
        var replicableProps = def.Properties
            .Where(p => p.Scope.IsClientVisible() && !p.IsReservedPosition)
            .ToList();

        // Backing fields live only on the side that OWNS the value
        // (IsBase or IsCell, mutually exclusive; Client mirrors every
        // visible prop; Server legacy fallback emits everything). This is
        // the M2 split that lets the base stop serialising stale zeros
        // for cell-scope properties.
        var props = GetPropertiesForContext(def.Properties, ctx)
            .Where(p => !p.IsReservedPosition).ToList();
        if (props.Count == 0 && replicableProps.Count == 0) return null;

        // The ReplicatedDirtyFlags enum MUST enumerate the full IsClientVisible
        // set in stable declaration order on every side — bit N has to denote
        // the same property on the sender, receiver, and any intermediate
        // observer, otherwise the 0xF003 wire flags byte is uninterpretable
        // across the base/cell split. Backing fields filter by ctx, enum
        // doesn't. The matching iteration rule on the serializers lives in
        // DeltaSyncEmitter (emitters skip any prop whose field is missing
        // on this side, so the unused bit positions stay zero in practice).
        var enumReplicableProps = replicableProps;
        var emitDirtyBacking = ctx != ProcessContext.Client && enumReplicableProps.Count > 0;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");

        if (enumReplicableProps.Count > 0)
        {
            EmitDirtyFlagsEnum(sb, enumReplicableProps);
            sb.AppendLine();
            if (emitDirtyBacking)
            {
                sb.AppendLine("    private ReplicatedDirtyFlags _dirtyFlags;");
                sb.AppendLine();
            }
        }

        // Backing fields
        foreach (var prop in props)
        {
            var csType = DefTypeHelper.ToCSharpType(prop.Type);
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            if (DefTypeHelper.NeedsFieldInitializer(prop.Type))
                sb.AppendLine($"    private {csType} {fieldName} = {DefTypeHelper.DefaultValue(prop.Type)};");
            else
                sb.AppendLine($"    private {csType} {fieldName};");
        }
        sb.AppendLine();

        // Change callback partial methods
        foreach (var prop in props)
        {
            var csType = DefTypeHelper.ToCSharpType(prop.Type);
            var propName = DefTypeHelper.ToPropertyName(prop.Name);
            sb.AppendLine($"    partial void On{propName}Changed({csType} oldValue, {csType} newValue);");
        }
        sb.AppendLine();

        // Properties. Two setter shapes:
        //   * Server replicable → dirty-bit + OnXxxChanged
        //   * Everything else   → bare assignment (no callback)
        //
        // The client setter intentionally does NOT fire OnXxxChanged — only
        // wire deltas do (via DeltaSyncEmitter's ApplyReplicatedDelta).
        // Clients observe authoritative server state; a local write is an
        // edge case (prediction, test fixtures, scratch UI state) that
        // shouldn't masquerade as an observed transition.
        foreach (var prop in props)
        {
            bool trackDirty = emitDirtyBacking && enumReplicableProps.Contains(prop);
            EmitProperty(sb, prop, trackDirty);
            sb.AppendLine();
        }

        // IsDirty / ClearDirty reference _dirtyFlags — emit only when the
        // backing field exists (server side).
        if (emitDirtyBacking)
        {
            sb.AppendLine("    public bool IsDirty => _dirtyFlags != ReplicatedDirtyFlags.None;");
            sb.AppendLine();
            sb.AppendLine("    public void ClearDirty() => _dirtyFlags = ReplicatedDirtyFlags.None;");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitDirtyFlagsEnum(StringBuilder sb, List<PropertyDefModel> props)
    {
        var (backingType, _) = GetFlagsTypeInfo(props.Count);
        sb.AppendLine("    [Flags]");
        sb.AppendLine($"    private enum ReplicatedDirtyFlags : {backingType}");
        sb.AppendLine("    {");
        sb.AppendLine("        None = 0,");
        for (int i = 0; i < props.Count; i++)
        {
            var comma = i < props.Count - 1 ? "," : "";
            var propName = DefTypeHelper.ToPropertyName(props[i].Name);
            // Use explicit numeric values to avoid uint-to-byte implicit conversion errors
            var flagValue = 1UL << i;
            sb.AppendLine($"        {propName} = {flagValue}{comma}");
        }
        sb.AppendLine("    }");
    }

    private static void EmitProperty(StringBuilder sb, PropertyDefModel prop, bool trackDirty)
    {
        var csType = DefTypeHelper.ToCSharpType(prop.Type);
        var fieldName = DefTypeHelper.ToFieldName(prop.Name);
        var propName = DefTypeHelper.ToPropertyName(prop.Name);

        sb.AppendLine($"    public {csType} {propName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        get => {fieldName};");

        if (trackDirty)
        {
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine($"            if ({fieldName} != value)");
            sb.AppendLine("            {");
            sb.AppendLine($"                var old = {fieldName};");
            sb.AppendLine($"                {fieldName} = value;");
            sb.AppendLine($"                _dirtyFlags |= ReplicatedDirtyFlags.{propName};");
            sb.AppendLine($"                On{propName}Changed(old, value);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine($"        set => {fieldName} = value;");
        }

        sb.AppendLine("    }");
    }

    /// <summary>
    /// Returns the subset of <paramref name="allProps"/> whose backing field
    /// lives on the given process side. Data lives on either base or cell
    /// but never both: Base only holds DATA_BASE scoped properties; Cell
    /// holds everything else (cell-scope plus client-visible cell-scope).
    /// Client is orthogonal — it keeps a projection of whatever it can
    /// observe from either side. Server is the
    /// legacy single-process fallback (no ATLAS_BASE/ATLAS_CELL compile
    /// symbol) and keeps the pre-refactor behaviour of emitting everything
    /// so existing server-mode samples don't regress.
    /// </summary>
    private static List<PropertyDefModel> GetPropertiesForContext(
        List<PropertyDefModel> allProps, ProcessContext ctx)
    {
        return ctx switch
        {
            ProcessContext.Base => allProps.Where(p => p.Scope.IsBase()).ToList(),
            ProcessContext.Cell => allProps.Where(p => p.Scope.IsCell()).ToList(),
            ProcessContext.Client => allProps.Where(p => p.Scope.IsClientVisible()).ToList(),
            _ => allProps,
        };
    }

    private static bool IsReplicable(PropertyScope scope) => scope.IsClientVisible();

    private static (string BackingType, string FlagSuffix) GetFlagsTypeInfo(int fieldCount)
    {
        if (fieldCount <= 8) return ("byte", "u");
        if (fieldCount <= 16) return ("ushort", "u");
        if (fieldCount <= 32) return ("uint", "u");
        return ("ulong", "UL");
    }
}
