using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

/// <summary>
/// Generates backing fields, public properties with dirty tracking, DirtyFlags enum,
/// and change callback hooks from .def property definitions.
/// </summary>
internal static class PropertiesEmitter
{
    public static string? Emit(EntityDefModel def, string className, string namespaceName,
                               ProcessContext ctx)
    {
        if (def.Properties.Count == 0) return null;

        // Filter properties based on process context
        var props = GetPropertiesForContext(def.Properties, ctx);
        if (props.Count == 0) return null;

        // Enum emission vs backing-field emission are decoupled:
        //   * The enum is needed whenever the class has replicable props, on
        //     EITHER side — the server uses it for dirty tracking, the client
        //     uses it for delta-bitmap decode in ApplyReplicatedDelta
        //     (DeltaSyncEmitter Client branch, Phase B1).
        //   * The `_dirtyFlags` backing field is server-side only: the
        //     client has no write-side state and never sets dirty bits.
        var enumReplicableProps = props.Where(p => IsReplicable(p.Scope)).ToList();
        var emitDirtyBacking = ctx != ProcessContext.Client && enumReplicableProps.Count > 0;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");

        if (enumReplicableProps.Count > 0)
        {
            EmitDirtyFlagsEnum(sb, enumReplicableProps);
            sb.AppendLine();
            if (emitDirtyBacking)
            {
                sb.AppendLine("    private ReplicatedDirtyFlags _dirtyFlags;");
                sb.AppendLine();
            }
        }

        // Backing fields
        foreach (var prop in props)
        {
            var csType = DefTypeHelper.ToCSharpType(prop.Type);
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            if (DefTypeHelper.NeedsFieldInitializer(prop.Type))
                sb.AppendLine($"    private {csType} {fieldName} = {DefTypeHelper.DefaultValue(prop.Type)};");
            else
                sb.AppendLine($"    private {csType} {fieldName};");
        }
        sb.AppendLine();

        // Change callback partial methods
        foreach (var prop in props)
        {
            var csType = DefTypeHelper.ToCSharpType(prop.Type);
            var propName = DefTypeHelper.ToPropertyName(prop.Name);
            sb.AppendLine($"    partial void On{propName}Changed({csType} oldValue, {csType} newValue);");
        }
        sb.AppendLine();

        // Properties. Two setter shapes:
        //   * Server replicable → dirty-bit + OnXxxChanged
        //   * Everything else   → bare assignment (no callback)
        //
        // The client setter intentionally does NOT fire OnXxxChanged — only
        // wire deltas do (via DeltaSyncEmitter's ApplyReplicatedDelta).
        // Aligning with BigWorld's simple_client_entity.cpp::propertyEvent:
        // set_<propname> script callbacks fire only on network-received
        // changes, not on local Python assignment. Clients observe
        // authoritative server state; a local write is an edge case
        // (prediction, test fixtures, scratch UI state) that shouldn't
        // masquerade as an observed transition.
        foreach (var prop in props)
        {
            bool trackDirty = emitDirtyBacking && enumReplicableProps.Contains(prop);
            EmitProperty(sb, prop, trackDirty);
            sb.AppendLine();
        }

        // IsDirty / ClearDirty reference _dirtyFlags — emit only when the
        // backing field exists (server side).
        if (emitDirtyBacking)
        {
            sb.AppendLine("    public bool IsDirty => _dirtyFlags != ReplicatedDirtyFlags.None;");
            sb.AppendLine();
            sb.AppendLine("    public void ClearDirty() => _dirtyFlags = ReplicatedDirtyFlags.None;");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitDirtyFlagsEnum(StringBuilder sb, List<PropertyDefModel> props)
    {
        var (backingType, _) = GetFlagsTypeInfo(props.Count);
        sb.AppendLine("    [Flags]");
        sb.AppendLine($"    private enum ReplicatedDirtyFlags : {backingType}");
        sb.AppendLine("    {");
        sb.AppendLine("        None = 0,");
        for (int i = 0; i < props.Count; i++)
        {
            var comma = i < props.Count - 1 ? "," : "";
            var propName = DefTypeHelper.ToPropertyName(props[i].Name);
            // Use explicit numeric values to avoid uint-to-byte implicit conversion errors
            var flagValue = 1UL << i;
            sb.AppendLine($"        {propName} = {flagValue}{comma}");
        }
        sb.AppendLine("    }");
    }

    private static void EmitProperty(StringBuilder sb, PropertyDefModel prop, bool trackDirty)
    {
        var csType = DefTypeHelper.ToCSharpType(prop.Type);
        var fieldName = DefTypeHelper.ToFieldName(prop.Name);
        var propName = DefTypeHelper.ToPropertyName(prop.Name);

        sb.AppendLine($"    public {csType} {propName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        get => {fieldName};");

        if (trackDirty)
        {
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine($"            if ({fieldName} != value)");
            sb.AppendLine("            {");
            sb.AppendLine($"                var old = {fieldName};");
            sb.AppendLine($"                {fieldName} = value;");
            sb.AppendLine($"                _dirtyFlags |= ReplicatedDirtyFlags.{propName};");
            sb.AppendLine($"                On{propName}Changed(old, value);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine($"        set => {fieldName} = value;");
        }

        sb.AppendLine("    }");
    }

    /// <summary>
    /// Returns properties visible in the given process context.
    /// Server/Base/Cell see all properties; Client sees only scope >= OwnClient.
    /// </summary>
    private static List<PropertyDefModel> GetPropertiesForContext(
        List<PropertyDefModel> allProps, ProcessContext ctx)
    {
        if (ctx != ProcessContext.Client) return allProps;

        return allProps.Where(p => IsClientVisible(p.Scope)).ToList();
    }

    private static bool IsClientVisible(PropertyScope scope)
    {
        return scope switch
        {
            PropertyScope.OwnClient => true,
            PropertyScope.AllClients => true,
            PropertyScope.OtherClients => true,
            PropertyScope.CellPublicAndOwn => true,
            PropertyScope.BaseAndClient => true,
            _ => false,
        };
    }

    private static bool IsReplicable(PropertyScope scope)
    {
        return scope switch
        {
            PropertyScope.OwnClient => true,
            PropertyScope.AllClients => true,
            PropertyScope.OtherClients => true,
            PropertyScope.CellPublicAndOwn => true,
            PropertyScope.BaseAndClient => true,
            _ => false,
        };
    }

    private static (string BackingType, string FlagSuffix) GetFlagsTypeInfo(int fieldCount)
    {
        if (fieldCount <= 8) return ("byte", "u");
        if (fieldCount <= 16) return ("ushort", "u");
        if (fieldCount <= 32) return ("uint", "u");
        return ("ulong", "UL");
    }
}
