using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

/// <summary>
/// Generates backing fields, public properties with dirty tracking, DirtyFlags enum,
/// and change callback hooks from .def property definitions.
/// </summary>
internal static class PropertiesEmitter
{
    public static string? Emit(EntityDefModel def, string className, string namespaceName,
                               ProcessContext ctx)
    {
        if (def.Properties.Count == 0) return null;

        // Filter properties based on process context
        var props = GetPropertiesForContext(def.Properties, ctx);
        if (props.Count == 0) return null;

        // Determine which properties are replicable (need dirty tracking)
        var replicableProps = ctx != ProcessContext.Client
            ? props.Where(p => IsReplicable(p.Scope)).ToList()
            : new List<PropertyDefModel>(); // Client doesn't track dirty

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");

        // Dirty flags enum (only for replicable properties on server side)
        if (replicableProps.Count > 0)
        {
            EmitDirtyFlagsEnum(sb, replicableProps);
            sb.AppendLine();
            sb.AppendLine("    private ReplicatedDirtyFlags _dirtyFlags;");
            sb.AppendLine();
        }

        // Backing fields
        foreach (var prop in props)
        {
            var csType = DefTypeHelper.ToCSharpType(prop.Type);
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            if (DefTypeHelper.NeedsFieldInitializer(prop.Type))
                sb.AppendLine($"    private {csType} {fieldName} = {DefTypeHelper.DefaultValue(prop.Type)};");
            else
                sb.AppendLine($"    private {csType} {fieldName};");
        }
        sb.AppendLine();

        // Change callback partial methods
        foreach (var prop in props)
        {
            var csType = DefTypeHelper.ToCSharpType(prop.Type);
            var propName = DefTypeHelper.ToPropertyName(prop.Name);
            sb.AppendLine($"    partial void On{propName}Changed({csType} oldValue, {csType} newValue);");
        }
        sb.AppendLine();

        // Properties with dirty tracking
        foreach (var prop in props)
        {
            bool withDirtyTracking = replicableProps.Contains(prop);
            EmitProperty(sb, prop, withDirtyTracking);
            sb.AppendLine();
        }

        // IsDirty / ClearDirty / SerializeReplicatedDelta / ApplyReplicatedDelta
        if (replicableProps.Count > 0)
        {
            sb.AppendLine("    public bool IsDirty => _dirtyFlags != ReplicatedDirtyFlags.None;");
            sb.AppendLine();
            sb.AppendLine("    public void ClearDirty() => _dirtyFlags = ReplicatedDirtyFlags.None;");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitDirtyFlagsEnum(StringBuilder sb, List<PropertyDefModel> props)
    {
        var (backingType, _) = GetFlagsTypeInfo(props.Count);
        sb.AppendLine("    [Flags]");
        sb.AppendLine($"    private enum ReplicatedDirtyFlags : {backingType}");
        sb.AppendLine("    {");
        sb.AppendLine("        None = 0,");
        for (int i = 0; i < props.Count; i++)
        {
            var comma = i < props.Count - 1 ? "," : "";
            var propName = DefTypeHelper.ToPropertyName(props[i].Name);
            // Use explicit numeric values to avoid uint-to-byte implicit conversion errors
            var flagValue = 1UL << i;
            sb.AppendLine($"        {propName} = {flagValue}{comma}");
        }
        sb.AppendLine("    }");
    }

    private static void EmitProperty(StringBuilder sb, PropertyDefModel prop, bool withDirtyTracking)
    {
        var csType = DefTypeHelper.ToCSharpType(prop.Type);
        var fieldName = DefTypeHelper.ToFieldName(prop.Name);
        var propName = DefTypeHelper.ToPropertyName(prop.Name);

        sb.AppendLine($"    public {csType} {propName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        get => {fieldName};");

        if (withDirtyTracking)
        {
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine($"            if ({fieldName} != value)");
            sb.AppendLine("            {");
            sb.AppendLine($"                var old = {fieldName};");
            sb.AppendLine($"                {fieldName} = value;");
            sb.AppendLine($"                _dirtyFlags |= ReplicatedDirtyFlags.{propName};");
            sb.AppendLine($"                On{propName}Changed(old, value);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine($"        set => {fieldName} = value;");
        }

        sb.AppendLine("    }");
    }

    /// <summary>
    /// Returns properties visible in the given process context.
    /// Server/Base/Cell see all properties; Client sees only scope >= OwnClient.
    /// </summary>
    private static List<PropertyDefModel> GetPropertiesForContext(
        List<PropertyDefModel> allProps, ProcessContext ctx)
    {
        if (ctx != ProcessContext.Client) return allProps;

        return allProps.Where(p => IsClientVisible(p.Scope)).ToList();
    }

    private static bool IsClientVisible(PropertyScope scope)
    {
        return scope switch
        {
            PropertyScope.OwnClient => true,
            PropertyScope.AllClients => true,
            PropertyScope.OtherClients => true,
            PropertyScope.CellPublicAndOwn => true,
            PropertyScope.BaseAndClient => true,
            _ => false,
        };
    }

    private static bool IsReplicable(PropertyScope scope)
    {
        return scope switch
        {
            PropertyScope.OwnClient => true,
            PropertyScope.AllClients => true,
            PropertyScope.OtherClients => true,
            PropertyScope.CellPublicAndOwn => true,
            PropertyScope.BaseAndClient => true,
            _ => false,
        };
    }

    private static (string BackingType, string FlagSuffix) GetFlagsTypeInfo(int fieldCount)
    {
        if (fieldCount <= 8) return ("byte", "u");
        if (fieldCount <= 16) return ("ushort", "u");
        if (fieldCount <= 32) return ("uint", "u");
        return ("ulong", "UL");
    }
}
