using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

internal static class RpcIdEmitter
{
    /// <summary>
    /// Emit a static class with RPC ID constants. These are identical across all process contexts.
    /// </summary>
    public static string Emit(List<EntityDefModel> defs, Dictionary<string, ushort> typeIndexMap)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Atlas.Rpc;");
        sb.AppendLine();
        sb.AppendLine("public static class RpcIds");
        sb.AppendLine("{");

        foreach (var def in defs.OrderBy(d => d.Name))
        {
            if (!typeIndexMap.TryGetValue(def.Name, out var typeIndex))
                continue;

            EmitMethodIds(sb, def.Name, def.ClientMethods, typeIndex, 0x00, "ClientRpc");
            EmitMethodIds(sb, def.Name, def.CellMethods, typeIndex, 0x02, "CellRpc");
            EmitMethodIds(sb, def.Name, def.BaseMethods, typeIndex, 0x03, "BaseRpc");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMethodIds(StringBuilder sb, string entityName,
        List<MethodDefModel> methods, ushort typeIndex, byte direction, string comment)
    {
        if (methods.Count == 0) return;

        sb.AppendLine($"    // {entityName} {comment}");
        var sorted = methods.OrderBy(m => m.Name).ToList();
        for (int i = 0; i < sorted.Count; i++)
        {
            int id = (direction << 22) | (typeIndex << 8) | (i + 1);
            sb.AppendLine($"    public const int {entityName}_{sorted[i].Name} = 0x{id:X6};");
        }
    }
}
