using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

internal static class RpcStubEmitter
{
    public static string Emit(EntityDefModel def, string className, string namespaceName,
                              string baseClass, ProcessContext ctx,
                              Dictionary<string, ushort> typeIndexMap)
    {
        if (!typeIndexMap.TryGetValue(def.Name, out var typeIndex))
            return "";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Atlas.Core;");
        sb.AppendLine("using Atlas.Serialization;");
        // Lets struct args (TypeRef.Kind == Struct) resolve unqualified;
        // StructEmitter places generated structs in Atlas.Def.
        sb.AppendLine("using Atlas.Def;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }
        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");

        // Client methods
        EmitMethods(sb, def.ClientMethods, "client_methods", ctx, typeIndex, 0x00);

        // Cell methods
        EmitMethods(sb, def.CellMethods, "cell_methods", ctx, typeIndex, 0x02);

        // Base methods
        EmitMethods(sb, def.BaseMethods, "base_methods", ctx, typeIndex, 0x03);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMethods(StringBuilder sb, List<MethodDefModel> methods,
        string section, ProcessContext ctx, ushort typeIndex, byte direction)
    {
        var sorted = methods.OrderBy(m => m.Name).ToList();
        for (int i = 0; i < sorted.Count; i++)
        {
            var method = sorted[i];
            var role = RpcRoleHelper.GetRole(section, ctx, method.Exposed);
            int rpcId = RpcIdEncoder.Encode(slot: 0, direction, typeIndex, i + 1);
            EmitMethod(sb, method, role, rpcId, section);
        }
    }

    private static void EmitMethod(StringBuilder sb, MethodDefModel method, RpcRole role,
                                    int rpcId, string section)
    {
        var paramList = RpcArgCodec.BuildParamList(method.Args);
        sb.AppendLine();

        switch (role)
        {
            case RpcRole.Receive:
                sb.AppendLine($"    public partial void {method.Name}({paramList});");
                break;

            case RpcRole.Send:
                sb.AppendLine($"    // Send stub for {section}.{method.Name}");
                sb.AppendLine($"    public void {method.Name}({paramList})");
                sb.AppendLine("    {");
                EmitSerializeAndSend(sb, method, rpcId, section);
                sb.AppendLine("    }");
                break;

            case RpcRole.Forbidden:
                sb.AppendLine($"    public void {method.Name}({paramList})");
                sb.AppendLine("    {");
                sb.AppendLine($"        throw new InvalidOperationException(");
                sb.AppendLine($"            \"{method.Name} is not exposed to this process context.\");");
                sb.AppendLine("    }");
                break;
        }
    }

    private static void EmitSerializeAndSend(StringBuilder sb, MethodDefModel method,
                                              int rpcId, string section)
    {
        // Direct entity-level stubs default to Owner scope; scripts that need
        // broadcast should use the mailbox accessors (entity.AllClients,
        // entity.OtherClients) emitted by MailboxEmitter.
        var sendArgs = section == "client_methods" ? "RpcTarget.Owner, " : "";
        if (method.Args.Count == 0)
        {
            sb.AppendLine($"        {SendMethod(section)}(0x{rpcId:X6}, {sendArgs}ReadOnlySpan<byte>.Empty);");
            return;
        }
        sb.AppendLine("        var writer = new SpanWriter(256);");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        foreach (var arg in method.Args)
            RpcArgCodec.EmitWrite(sb, arg, "writer", "            ");
        sb.AppendLine($"            {SendMethod(section)}(0x{rpcId:X6}, {sendArgs}writer.WrittenSpan);");
        sb.AppendLine("        }");
        sb.AppendLine("        finally { writer.Dispose(); }");
    }

    private static string SendMethod(string section)
    {
        return section switch
        {
            "client_methods" => "SendClientRpc",
            "cell_methods" => "SendCellRpc",
            "base_methods" => "SendBaseRpc",
            _ => "SendClientRpc",
        };
    }
}
