using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

/// <summary>
/// Generates Serialize/Deserialize methods and TypeName override from .def property definitions.
/// Uses version + fieldCount + bodyLength format for forward/backward compatibility.
/// </summary>
internal static class SerializationEmitter
{
    public static string Emit(EntityDefModel def, string className, string namespaceName,
                              ProcessContext ctx)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    public override string TypeName => \"{def.Name}\";");
        sb.AppendLine();
        sb.AppendLine("    private const byte kSerializationVersion = 1;");
        sb.AppendLine();

        // ATLAS_DEF008: reserved-position properties are skipped everywhere.
        // PropertiesEmitter doesn't emit a backing field for them, so
        // referencing `_position` here would not compile.
        //
        // The base/cell split gives us TWO independent "full state" wire
        // formats:
        //   * Base.Serialize writes base-persistent fields (goes to DBApp
        //     via GetEntityData → dbapp::WriteEntity) — DATA_BASE only.
        //   * Cell.Serialize writes cell-authoritative fields (goes to the
        //     offload bundle and to BaseApp as cellBackupData opaque bytes)
        //     — CELL_DATA only.
        // Each blob is decoded in its matching ctx only; base never
        // deserialises cell fields and vice versa. Client projects whatever
        // it can observe regardless of which side authored it.
        //
        // Cross-side persistence: BaseApp stitches base bytes +
        // cell_backup_data_ into the persistent blob, so cell-scope
        // persistent="true" properties survive the DB round-trip even
        // though Cell.Serialize emits cell-only bytes.
        var sideProps = GetPropertiesForContext(def.Properties, ctx)
            .Where(p => !p.IsReservedPosition).ToList();

        // Server/Base/Cell: generate Serialize (full state). Client never
        // originates state so it gets no Serialize.
        if (ctx != ProcessContext.Client)
        {
            EmitSerialize(sb, sideProps);
            sb.AppendLine();
        }

        // Deserialize reads the matching wire format — same scope partition
        // as the writer above. Client's side filter is built into
        // GetPropertiesForContext (keeps only IsClientVisible), so the
        // "read-and-discard" branch inside EmitDeserialize is now dead code
        // for Client ctx (every prop in sideProps has a field on the client
        // too). Retained as a harmless passthrough until wire-format layer
        // is simplified in a later commit.
        EmitDeserialize(sb, sideProps, ctx);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitSerialize(StringBuilder sb, List<PropertyDefModel> props)
    {
        sb.AppendLine("    public override void Serialize(ref SpanWriter writer)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteByte(kSerializationVersion);");
        sb.AppendLine($"        writer.WriteUInt16((ushort){props.Count});");
        sb.AppendLine("        var bodyWriter = new SpanWriter(256);");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        foreach (var prop in props)
        {
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            var writeMethod = DefTypeHelper.WriteMethod(prop.Type);
            sb.AppendLine($"            bodyWriter.{writeMethod}({fieldName});");
        }
        sb.AppendLine("            writer.WriteUInt16((ushort)bodyWriter.Length);");
        sb.AppendLine("            writer.WriteRawBytes(bodyWriter.WrittenSpan);");
        sb.AppendLine("        }");
        sb.AppendLine("        finally { bodyWriter.Dispose(); }");
        sb.AppendLine("    }");
    }

    private static void EmitDeserialize(StringBuilder sb, List<PropertyDefModel> props, ProcessContext ctx)
    {
        sb.AppendLine("    public override void Deserialize(ref SpanReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine("        var version = reader.ReadByte();");
        sb.AppendLine("        var fieldCount = reader.ReadUInt16();");
        sb.AppendLine("        var bodyLength = reader.ReadUInt16();");
        sb.AppendLine("        var bodyStart = reader.Position;");

        for (int i = 0; i < props.Count; i++)
        {
            var readMethod = DefTypeHelper.ReadMethod(props[i].Type);
            bool hasField = ctx != ProcessContext.Client || IsClientVisible(props[i].Scope);

            if (hasField)
            {
                var fieldName = DefTypeHelper.ToFieldName(props[i].Name);
                sb.AppendLine($"        if (fieldCount > {i}) {fieldName} = reader.{readMethod}();");
            }
            else
            {
                // Read and discard — field doesn't exist in client context
                sb.AppendLine($"        if (fieldCount > {i}) _ = reader.{readMethod}();");
            }
        }

        sb.AppendLine("        var consumed = reader.Position - bodyStart;");
        sb.AppendLine("        if (consumed < bodyLength)");
        sb.AppendLine("            reader.Advance(bodyLength - consumed);");
        sb.AppendLine("    }");
    }

    private static bool IsClientVisible(PropertyScope scope) => scope.IsClientVisible();

    // Matches PropertiesEmitter.GetPropertiesForContext — the two must agree
    // or Serialize refers to fields that don't exist in the generated class.
    private static List<PropertyDefModel> GetPropertiesForContext(
        List<PropertyDefModel> allProps, ProcessContext ctx)
    {
        return ctx switch
        {
            ProcessContext.Base => allProps.Where(p => p.Scope.IsBase()).ToList(),
            ProcessContext.Cell => allProps.Where(p => p.Scope.IsCell()).ToList(),
            ProcessContext.Client => allProps.Where(p => p.Scope.IsClientVisible()).ToList(),
            _ => allProps,
        };
    }
}
