using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

/// <summary>
/// Generates Serialize/Deserialize methods and TypeName override from .def property definitions.
/// Uses version + fieldCount + bodyLength format for forward/backward compatibility.
/// </summary>
internal static class SerializationEmitter
{
    public static string Emit(EntityDefModel def, string className, string namespaceName,
                              ProcessContext ctx)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    public override string TypeName => \"{def.Name}\";");
        sb.AppendLine();
        sb.AppendLine("    private const byte kSerializationVersion = 1;");
        sb.AppendLine();

        var allProps = def.Properties;

        // Server/Base/Cell: generate Serialize (full state)
        // Client: no Serialize (clients don't send full state)
        if (ctx != ProcessContext.Client)
        {
            EmitSerialize(sb, allProps);
            sb.AppendLine();
        }

        // All contexts: generate Deserialize
        // Client deserializes only client-visible fields; non-visible fields are read and discarded.
        EmitDeserialize(sb, allProps, ctx);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitSerialize(StringBuilder sb, List<PropertyDefModel> props)
    {
        sb.AppendLine("    public override void Serialize(ref SpanWriter writer)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteByte(kSerializationVersion);");
        sb.AppendLine($"        writer.WriteUInt16((ushort){props.Count});");
        sb.AppendLine("        var bodyWriter = new SpanWriter(256);");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        foreach (var prop in props)
        {
            var fieldName = DefTypeHelper.ToFieldName(prop.Name);
            var writeMethod = DefTypeHelper.WriteMethod(prop.Type);
            sb.AppendLine($"            bodyWriter.{writeMethod}({fieldName});");
        }
        sb.AppendLine("            writer.WriteUInt16((ushort)bodyWriter.Length);");
        sb.AppendLine("            writer.WriteRawBytes(bodyWriter.WrittenSpan);");
        sb.AppendLine("        }");
        sb.AppendLine("        finally { bodyWriter.Dispose(); }");
        sb.AppendLine("    }");
    }

    private static void EmitDeserialize(StringBuilder sb, List<PropertyDefModel> props, ProcessContext ctx)
    {
        sb.AppendLine("    public override void Deserialize(ref SpanReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine("        var version = reader.ReadByte();");
        sb.AppendLine("        var fieldCount = reader.ReadUInt16();");
        sb.AppendLine("        var bodyLength = reader.ReadUInt16();");
        sb.AppendLine("        var bodyStart = reader.Position;");

        for (int i = 0; i < props.Count; i++)
        {
            var readMethod = DefTypeHelper.ReadMethod(props[i].Type);
            bool hasField = ctx != ProcessContext.Client || IsClientVisible(props[i].Scope);

            if (hasField)
            {
                var fieldName = DefTypeHelper.ToFieldName(props[i].Name);
                sb.AppendLine($"        if (fieldCount > {i}) {fieldName} = reader.{readMethod}();");
            }
            else
            {
                // Read and discard — field doesn't exist in client context
                sb.AppendLine($"        if (fieldCount > {i}) _ = reader.{readMethod}();");
            }
        }

        sb.AppendLine("        var consumed = reader.Position - bodyStart;");
        sb.AppendLine("        if (consumed < bodyLength)");
        sb.AppendLine("            reader.Advance(bodyLength - consumed);");
        sb.AppendLine("    }");
    }

    private static bool IsClientVisible(PropertyScope scope)
    {
        return scope switch
        {
            PropertyScope.OwnClient => true,
            PropertyScope.AllClients => true,
            PropertyScope.OtherClients => true,
            PropertyScope.CellPublicAndOwn => true,
            PropertyScope.BaseAndClient => true,
            _ => false,
        };
    }
}
