using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

// Emits SpaceDataKeys.g.cs from the merged <space_data><key> entries
// across all .def files. Const ids + NameOf / KindOf lookup tables.
internal static class SpaceDataEmitter
{
    public const string Namespace = "Atlas.Space";

    public static string Emit(IReadOnlyList<SpaceDataKeyDefModel> keys)
    {
        var sorted = keys.Where(k => !k.Deprecated).OrderBy(k => k.KeyId).ToList();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {Namespace};");
        sb.AppendLine();
        sb.AppendLine("// SpaceData key registry — populated from <space_data><key> entries.");
        sb.AppendLine("// Ids are permanent; never reuse one even after the key is dropped.");
        sb.AppendLine("public static class SpaceDataKeys");
        sb.AppendLine("{");
        foreach (var k in sorted)
        {
            sb.AppendLine($"    public const ushort {DefTypeHelper.ToPropertyName(k.Name)} = {k.KeyId};");
        }
        if (sorted.Count > 0) sb.AppendLine();
        sb.AppendLine("    public static string? NameOf(ushort keyId) => keyId switch");
        sb.AppendLine("    {");
        foreach (var k in sorted)
        {
            sb.AppendLine($"        {k.KeyId} => \"{k.Name}\",");
        }
        sb.AppendLine("        _ => null,");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static SpaceDataKind KindOf(ushort keyId) => keyId switch");
        sb.AppendLine("    {");
        foreach (var k in sorted)
        {
            sb.AppendLine($"        {k.KeyId} => SpaceDataKind.{KindEnumName(k.Type.Kind)},");
        }
        sb.AppendLine("        _ => SpaceDataKind.Unknown,");
        sb.AppendLine("    };");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public enum SpaceDataKind : byte");
        sb.AppendLine("{");
        sb.AppendLine("    Unknown = 0,");
        sb.AppendLine("    Bool, Int32, Int64, UInt32, UInt64, Float, Double, String, Vector3,");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string KindEnumName(PropertyDataKind kind) => kind switch
    {
        PropertyDataKind.Bool => "Bool",
        PropertyDataKind.Int32 => "Int32",
        PropertyDataKind.Int64 => "Int64",
        PropertyDataKind.UInt32 => "UInt32",
        PropertyDataKind.UInt64 => "UInt64",
        PropertyDataKind.Float => "Float",
        PropertyDataKind.Double => "Double",
        PropertyDataKind.String => "String",
        PropertyDataKind.Vector3 => "Vector3",
        _ => "Unknown",
    };
}
