using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Atlas.Generators.Def.Emitters;

// Emits one `partial struct` per <struct> with Serialize / Deserialize;
// Field-mode structs additionally get per-field __WriteFieldOp / __ApplyFieldOp.
internal static class StructEmitter
{
    // Namespace every generated struct lands in. Kept as a constant so the
    // PropertiesEmitter can `using Atlas.Def;` unconditionally.
    public const string StructNamespace = "Atlas.Def";

    public static string Emit(StructDefModel s, Action<Diagnostic>? reportDiagnostic)
    {
        var decision = DecideSyncMode(s);
        ReportDecision(s, decision, reportDiagnostic);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("//");
        sb.AppendLine("// Extending this partial struct in a hand-written file is OK for");
        sb.AppendLine("// instance methods, computed properties, or interface impls — but");
        sb.AppendLine("// DO NOT add instance FIELDS. The auto-sync byte count and the");
        sb.AppendLine("// Serialize / Deserialize pair below assume exactly the fields");
        sb.AppendLine("// declared in the .def <struct> block. A hand-added field would");
        sb.AppendLine("// round-trip as zero on the wire and silently corrupt state.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {StructNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial struct {s.Name}");
        sb.AppendLine("{");

        foreach (var f in s.Fields)
        {
            var csType = CSharpTypeOf(f.Type);
            sb.AppendLine($"    public {csType} {DefTypeHelper.ToPropertyName(f.Name)};");
        }

        sb.AppendLine();
        EmitSerialize(sb, s);
        sb.AppendLine();
        EmitDeserialize(sb, s);
        sb.AppendLine();
        // Always emit the field-op codec — it costs nothing for Whole-
        // mode structs whose containers never call it, and lets the
        // generic list-of-struct codec dispatch StructFieldSet ops
        // without per-struct compile gates.
        EmitFieldOpCodec(sb, s);
        sb.AppendLine("}");

        if (decision.Mode == StructSyncMode.Field)
        {
            sb.AppendLine();
            EmitItemAt(sb, s);
        }
        return sb.ToString();
    }

    // Per-field op codec dispatched on a u8 field index. Reuses the
    // recursive element codec so container fields (list, dict) on
    // Whole-mode structs serialize integrally per-field — useful only
    // if a future opt-in lets Whole-mode structs also opt into field-
    // set ops, but cheap enough to always emit.
    private static void EmitFieldOpCodec(StringBuilder sb, StructDefModel s)
    {
        sb.AppendLine("    public void __WriteFieldOp(ref SpanWriter w, byte fieldIdx)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (fieldIdx)");
        sb.AppendLine("        {");
        var writeNames = new PropertyCodec.NameGen();
        for (int i = 0; i < s.Fields.Count; ++i)
        {
            var f = s.Fields[i];
            var name = DefTypeHelper.ToPropertyName(f.Name);
            sb.AppendLine($"            case {i}:");
            PropertyCodec.EmitElementWrite(sb, f.Type, "w", name, "                ", writeNames);
            sb.AppendLine($"                break;");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {s.Name} __ApplyFieldOp(ref SpanReader r, byte fieldIdx, {s.Name} cur)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (fieldIdx)");
        sb.AppendLine("        {");
        var readNames = new PropertyCodec.NameGen();
        for (int i = 0; i < s.Fields.Count; ++i)
        {
            var f = s.Fields[i];
            var name = DefTypeHelper.ToPropertyName(f.Name);
            sb.AppendLine($"            case {i}:");
            sb.AppendLine($"            {{");
            var local = PropertyCodec.EmitElementRead(sb, f.Type, "r", "                ",
                                                     readNames, plainContainers: true);
            sb.AppendLine($"                cur.{name} = {local};");
            sb.AppendLine($"                break;");
            sb.AppendLine($"            }}");
        }
        sb.AppendLine("        }");
        sb.AppendLine("        return cur;");
        sb.AppendLine("    }");
    }

    // ItemAt accessor: for `list[FieldStruct]` properties, scripts use
    // `entity.ListAt(slot).Field = value` to mutate one field. The
    // setter snapshots-and-records via ObservableList.RecordStructFieldSet
    // so the wire ships only that field's bytes instead of the whole
    // struct body.
    //
    // ItemAt instances allocate per `ListAt(slot)` call (~24 B each).
    // A single shared instance per list with mutable slot would race
    // when two slots are accessed in the same statement, so we eat the
    // alloc to keep usage safe.
    private static void EmitItemAt(StringBuilder sb, StructDefModel s)
    {
        var clsName = s.Name + "ItemAt";
        sb.AppendLine($"public sealed class {clsName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly global::Atlas.Observable.ObservableList<{StructNamespace}.{s.Name}> _list;");
        sb.AppendLine("    private readonly int _slot;");
        sb.AppendLine();
        sb.AppendLine($"    internal {clsName}(global::Atlas.Observable.ObservableList<{StructNamespace}.{s.Name}> list, int slot)");
        sb.AppendLine("    {");
        sb.AppendLine("        _list = list;");
        sb.AppendLine("        _slot = slot;");
        sb.AppendLine("    }");
        sb.AppendLine();
        for (int i = 0; i < s.Fields.Count; ++i)
        {
            var f = s.Fields[i];
            var name = DefTypeHelper.ToPropertyName(f.Name);
            var csType = CSharpTypeOf(f.Type);
            sb.AppendLine($"    public {csType} {name}");
            sb.AppendLine("    {");
            sb.AppendLine($"        get => _list.Items[_slot].{name};");
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine($"            var s = _list.Items[_slot];");
            sb.AppendLine($"            if (System.Collections.Generic.EqualityComparer<{csType}>.Default.Equals(s.{name}, value)) return;");
            sb.AppendLine($"            s.{name} = value;");
            sb.AppendLine("            _list.SetWithoutDirty(_slot, s);");
            sb.AppendLine($"            _list.RecordStructFieldSet(_slot, fieldIdx: {i});");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }
        sb.AppendLine("}");
    }

    private static void EmitSerialize(StringBuilder sb, StructDefModel s)
    {
        sb.AppendLine("    public void Serialize(ref SpanWriter w)");
        sb.AppendLine("    {");
        var names = new PropertyCodec.NameGen();
        foreach (var f in s.Fields)
        {
            var fieldName = DefTypeHelper.ToPropertyName(f.Name);
            PropertyCodec.EmitElementWrite(sb, f.Type, "w", fieldName, "        ", names);
        }
        sb.AppendLine("    }");
    }

    private static void EmitDeserialize(StringBuilder sb, StructDefModel s)
    {
        sb.AppendLine($"    public static {s.Name} Deserialize(ref SpanReader r)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var v = new {s.Name}();");
        var names = new PropertyCodec.NameGen();
        foreach (var f in s.Fields)
        {
            var fieldName = DefTypeHelper.ToPropertyName(f.Name);
            var local = PropertyCodec.EmitElementRead(sb, f.Type, "r", "        ", names,
                                                     plainContainers: true);
            sb.AppendLine($"        v.{fieldName} = {local};");
        }
        sb.AppendLine("        return v;");
        sb.AppendLine("    }");
    }

    // Struct fields that are containers stay plain List<T> / Dictionary<K,V>
    // — Observable wrappers can't safely hook into a value-type's copy
    // semantics (the IRebindableFields work that would unlock that lives
    // in a separate roadmap item). Scripts mutating an inner container
    // in-place won't dirty the owning struct slot; reassign the whole
    // struct slot to trigger replication.
    private static string CSharpTypeOf(DataTypeRefModel t) => PropertyCodec.CSharpTypeForStructField(t);

    // Heuristic from the design doc. Returns the mode to use and a short
    // rationale string for the Info diagnostic.
    internal readonly struct SyncDecision
    {
        public StructSyncMode Mode { get; }
        public string Reason { get; }
        public int FixedBytes { get; }
        public bool HasVariable { get; }
        public SyncDecision(StructSyncMode mode, string reason, int fixedBytes, bool hasVariable)
        {
            Mode = mode; Reason = reason; FixedBytes = fixedBytes; HasVariable = hasVariable;
        }
    }

    internal static SyncDecision DecideSyncMode(StructDefModel s)
    {
        // Explicit overrides are honoured verbatim.
        if (s.SyncMode == StructSyncMode.Whole)
            return new SyncDecision(StructSyncMode.Whole, "explicit sync=\"whole\"", 0, false);
        if (s.SyncMode == StructSyncMode.Field)
            return new SyncDecision(StructSyncMode.Field, "explicit sync=\"field\"", 0, false);

        int fixedBytes = 0;
        bool hasVariable = false;
        foreach (var f in s.Fields)
        {
            var width = FieldFixedWidth(f.Type);
            if (width == 0) hasVariable = true;
            else fixedBytes += width;
        }

        // Rule 1: variable-width fields force whole (nested struct field
        // sync not implemented yet; list/dict/string don't roundtrip
        // cleanly through the per-field codec).
        if (hasVariable)
            return new SyncDecision(StructSyncMode.Whole,
                $"has variable-width field, N={s.Fields.Count}", fixedBytes, true);

        if (fixedBytes <= 8)
            return new SyncDecision(StructSyncMode.Whole,
                $"S={fixedBytes}B ≤ 8", fixedBytes, false);

        if (s.Fields.Count <= 4)
            return new SyncDecision(StructSyncMode.Whole,
                $"N={s.Fields.Count} ≤ 4, S={fixedBytes}B", fixedBytes, false);

        if (fixedBytes >= 32 && s.Fields.Count >= 8)
            return new SyncDecision(StructSyncMode.Field,
                $"S={fixedBytes}B ≥ 32 and N={s.Fields.Count} ≥ 8", fixedBytes, false);

        return new SyncDecision(StructSyncMode.Whole,
            $"middle ground (S={fixedBytes}B, N={s.Fields.Count})", fixedBytes, false);
    }

    // Fixed width of the DataTypeRef seen from the struct-field codec's
    // perspective. Any kind it can't serialise inline (containers, nested
    // structs) reports 0, which pushes the struct into whole-sync mode.
    private static int FieldFixedWidth(DataTypeRefModel t)
    {
        return t.Kind switch
        {
            PropertyDataKind.Bool or
            PropertyDataKind.Int8 or PropertyDataKind.UInt8 => 1,
            PropertyDataKind.Int16 or PropertyDataKind.UInt16 => 2,
            PropertyDataKind.Int32 or PropertyDataKind.UInt32 or PropertyDataKind.Float => 4,
            PropertyDataKind.Int64 or PropertyDataKind.UInt64 or PropertyDataKind.Double => 8,
            PropertyDataKind.Vector3 => 12,
            PropertyDataKind.Quaternion => 16,
            _ => 0,
        };
    }

    private static void ReportDecision(StructDefModel s, SyncDecision d,
                                       Action<Diagnostic>? reportDiagnostic)
    {
        reportDiagnostic?.Invoke(Diagnostic.Create(
            DefDiagnosticDescriptors.DEF014, Location.None, s.Name,
            d.Mode.ToString().ToLowerInvariant(), d.Reason));
    }
}
