using System.Collections.Generic;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

// Generates DefStructRegistry.RegisterAllStructs() which walks each linked
// StructDefModel and feeds its wire layout to the C++ registry via
// NativeApi.RegisterStruct. Structs are registered BEFORE entity types so
// that DataTypeRef kStruct fields in entity descriptors resolve against a
// populated struct table.
//
// BuildAll mirrors the runtime path without the PInvoke side effect, so
// Atlas.Tools.DefDump can extract the raw blobs from a compiled assembly
// and emit a binary container file consumable by
// EntityDefRegistry::RegisterFromBinaryFile.
internal static class StructRegistryEmitter
{
    public static string Emit(List<StructDefModel> structs, ProcessContext ctx)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");
        sb.AppendLine();
        sb.AppendLine("namespace Atlas.Def;");
        sb.AppendLine();
        // public so the offline DefDump tool can reflect on BuildAll
        // without IVT plumbing.
        sb.AppendLine("public static class DefStructRegistry");
        sb.AppendLine("{");
        // Priority ensures RegisterAllStructs fires before
        // DefEntityTypeRegistry.RegisterAll; entity descriptors that
        // reference a struct by id would otherwise find an empty struct
        // table on RegisterType.
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void RegisterAllStructs()");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        foreach (var s in structs)
        {
            sb.AppendLine($"            Register_{s.Name}();");
        }
        sb.AppendLine("        }");
        sb.AppendLine("        catch (System.DllNotFoundException) { }");
        sb.AppendLine("        catch (System.InvalidOperationException) { }");
        sb.AppendLine("    }");

        // BuildAll — visits each struct blob without the PInvoke side
        // effect. Mirrors DefEntityTypeRegistry.BuildAll's contract.
        sb.AppendLine();
        sb.AppendLine("    public static void BuildAll(System.Action<byte[]> visit)");
        sb.AppendLine("    {");
        foreach (var s in structs)
        {
            sb.AppendLine("        {");
            sb.AppendLine("            var w = new SpanWriter(256);");
            sb.AppendLine($"            try {{ Build_{s.Name}(ref w); visit(w.WrittenSpan.ToArray()); }}");
            sb.AppendLine("            finally { w.Dispose(); }");
            sb.AppendLine("        }");
        }
        sb.AppendLine("    }");

        foreach (var s in structs)
        {
            sb.AppendLine();
            EmitRegisterStructMethod(sb, s, ctx);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitRegisterStructMethod(StringBuilder sb, StructDefModel s,
                                                 ProcessContext ctx)
    {
        // Register_<Foo> is the thin shim; Build_<Foo> owns the wire
        // sequence so RegisterAllStructs (PInvoke) and BuildAll (offline
        // dump) share one source of truth.
        sb.AppendLine($"    private static void Register_{s.Name}()");
        sb.AppendLine("    {");
        sb.AppendLine("        var writer = new SpanWriter(256);");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            Build_{s.Name}(ref writer);");
        if (ctx == ProcessContext.Client)
            sb.AppendLine("            Atlas.Client.ClientEntityRegistryBridge.RegisterStruct(writer.WrittenSpan);");
        else
            sb.AppendLine("            Atlas.Core.EntityRegistryBridge.RegisterStruct(writer.WrittenSpan);");
        sb.AppendLine("        }");
        sb.AppendLine("        finally { writer.Dispose(); }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    private static void Build_{s.Name}(ref SpanWriter writer)");
        sb.AppendLine("    {");
        sb.AppendLine($"        writer.WriteUInt16((ushort){s.Id});");
        sb.AppendLine($"        writer.WriteString(\"{s.Name}\");");
        sb.AppendLine($"        writer.WritePackedUInt32({(uint)s.Fields.Count});");
        foreach (var f in s.Fields)
        {
            sb.AppendLine($"        writer.WriteString(\"{f.Name}\");");
            TypeRegistryEmitter.EmitDataTypeRef(sb, f.Type);
        }
        sb.AppendLine("    }");
    }
}
