using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

internal static class TypeRegistryEmitter
{
    public static string Emit(
        List<(EntityDefModel Def, string ClassName, string Namespace)> entities,
        Dictionary<string, ushort> typeIndexMap,
        ProcessContext ctx)
    {
        // Sort by type name for deterministic type_id assignment
        var sorted = entities.OrderBy(e => e.Def.Name).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");

        // No process-specific using needed; calls are fully qualified

        sb.AppendLine();
        sb.AppendLine("namespace Atlas.Def;");
        sb.AppendLine();
        // Public so DefDump can reflect; RegisterAll stays internal (PInvoke effects).
        sb.AppendLine("public static class DefEntityTypeRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    internal static void RegisterAll()");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        foreach (var (def, className, ns) in sorted)
        {
            if (!typeIndexMap.TryGetValue(def.Name, out var typeId))
                continue;
            sb.AppendLine($"            Register_{def.Name}({typeId});");
        }
        sb.AppendLine("        }");
        sb.AppendLine("        catch (System.DllNotFoundException) { }");
        sb.AppendLine("        catch (System.InvalidOperationException) { }");
        sb.AppendLine("    }");

        // BuildAll visits the same blobs without PInvoke — DefDump uses it.
        sb.AppendLine();
        sb.AppendLine("    public static void BuildAll(System.Action<byte[]> visit)");
        sb.AppendLine("    {");
        foreach (var (def, _, _) in sorted)
        {
            if (!typeIndexMap.TryGetValue(def.Name, out var typeId))
                continue;
            sb.AppendLine($"        {{");
            sb.AppendLine($"            var w = new SpanWriter(1024);");
            sb.AppendLine($"            try {{ Build_{def.Name}(ref w, {typeId}); visit(w.WrittenSpan.ToArray()); }}");
            sb.AppendLine($"            finally {{ w.Dispose(); }}");
            sb.AppendLine($"        }}");
        }
        sb.AppendLine("    }");

        foreach (var (def, className, ns) in sorted)
        {
            if (!typeIndexMap.TryGetValue(def.Name, out var typeId))
                continue;
            sb.AppendLine();
            EmitRegisterMethod(sb, def, typeId, typeIndexMap, ctx);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitRegisterMethod(StringBuilder sb, EntityDefModel def, ushort typeId,
        Dictionary<string, ushort> typeIndexMap, ProcessContext ctx)
    {
        // Split: Build_<Foo> writes the blob; Register_<Foo> wraps PInvoke.
        sb.AppendLine($"    private static void Register_{def.Name}(ushort typeId)");
        sb.AppendLine("    {");
        sb.AppendLine("        var writer = new SpanWriter(1024);");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            Build_{def.Name}(ref writer, typeId);");
        if (ctx == ProcessContext.Client)
            sb.AppendLine("            Atlas.Client.ClientEntityRegistryBridge.RegisterEntityType(writer.WrittenSpan);");
        else
            sb.AppendLine("            Atlas.Core.EntityRegistryBridge.RegisterEntityType(writer.WrittenSpan);");
        sb.AppendLine("        }");
        sb.AppendLine("        finally { writer.Dispose(); }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    private static void Build_{def.Name}(ref SpanWriter writer, ushort typeId)");
        sb.AppendLine("    {");

        // Type header
        sb.AppendLine($"            writer.WriteString(\"{def.Name}\");");
        sb.AppendLine("            writer.WriteUInt16(typeId);");
        sb.AppendLine($"            writer.WriteBool({(def.HasCell ? "true" : "false")});");
        sb.AppendLine($"            writer.WriteBool({(def.HasClient ? "true" : "false")});");

        // ATLAS_DEF008 reserved `position` skipped so C# and C++ indices align.
        var effectiveProps = def.Properties.Where(p => !p.IsReservedPosition).ToList();
        sb.AppendLine($"            writer.WritePackedUInt32({(uint)effectiveProps.Count});");
        for (int i = 0; i < effectiveProps.Count; i++)
        {
            var prop = effectiveProps[i];
            var topKind = ResolveTopLevelKind(prop);
            sb.AppendLine($"            writer.WriteString(\"{prop.Name}\");");
            sb.AppendLine($"            writer.WriteByte({(byte)topKind});");
            sb.AppendLine($"            writer.WriteByte({(byte)prop.Scope});");
            sb.AppendLine($"            writer.WriteBool({(prop.Persistent ? "true" : "false")});");
            sb.AppendLine($"            writer.WriteByte(5);");  // detail_level default
            sb.AppendLine($"            writer.WriteUInt16({(ushort)i});");
            sb.AppendLine($"            writer.WriteBool(false);");  // identifier (not parsed from .def yet)
            sb.AppendLine($"            writer.WriteBool({(prop.Reliable ? "true" : "false")});");

            // Wire format consumed by RegisterType in entity_def_registry.cc.
            if (prop.TypeRef is not null && IsContainer(topKind))
            {
                EmitDataTypeRefBody(sb, prop.TypeRef);
                sb.AppendLine($"            writer.WritePackedUInt32({prop.MaxSize});");
            }
        }

        // Slot encoded into rpc_id so C++ registry treats body + components alike.
        var allRpcs = new List<(MethodDefModel Method, byte Direction, int Slot, int MethodIdx)>();

        void AddSection(List<MethodDefModel> methods, byte direction, int slot)
        {
            for (int i = 0; i < methods.Count; i++)
                allRpcs.Add((methods[i], direction, slot, i + 1));
        }

        AddSection(def.ClientMethods, 0x00, slot: 0);
        AddSection(def.CellMethods,   0x02, slot: 0);
        AddSection(def.BaseMethods,   0x03, slot: 0);

        foreach (var c in def.Components)
        {
            if (c.Locality != ComponentLocality.Synced) continue;
            AddSection(c.ClientMethods, 0x00, c.SlotIdx);
            AddSection(c.CellMethods,   0x02, c.SlotIdx);
            AddSection(c.BaseMethods,   0x03, c.SlotIdx);
        }

        sb.AppendLine($"            writer.WritePackedUInt32({(uint)allRpcs.Count});");

        foreach (var (method, direction, slot, methodIdx) in allRpcs)
        {
            int rpcId = RpcIdEncoder.Encode(slot, direction, typeId, methodIdx);

            // name (string)
            sb.AppendLine($"            writer.WriteString(\"{method.Name}\");");
            // rpc_id (packed uint32)
            sb.AppendLine($"            writer.WritePackedUInt32(0x{rpcId:X8});");
            // param_count (packed uint32)
            sb.AppendLine($"            writer.WritePackedUInt32({(uint)method.Args.Count});");
            // C++ stores kind for logging; arg payload is decoded C#-side.
            foreach (var arg in method.Args)
            {
                sb.AppendLine($"            writer.WriteByte({RpcArgCodec.WireKind(arg)});");
            }
            // ExposedScope (uint8)
            sb.AppendLine($"            writer.WriteByte({(byte)method.Exposed});");
        }

        // Slot table tail — lets ATDF readers map slot_idx → component_type_id
        // without the C# runtime. Local components (SlotIdx == -1) are skipped.
        var syncedSlots = def.Components
            .Where(c => c.Locality == ComponentLocality.Synced && c.SlotIdx >= 0
                        && c.ComponentTypeId > 0)
            .ToList();
        sb.AppendLine($"            writer.WritePackedUInt32({(uint)syncedSlots.Count});");
        foreach (var c in syncedSlots)
        {
            sb.AppendLine($"            writer.WriteUInt16({(ushort)c.SlotIdx});");
            sb.AppendLine($"            writer.WriteString(\"{c.SlotName}\");");
            sb.AppendLine($"            writer.WriteUInt16({(ushort)c.ComponentTypeId});");
            sb.AppendLine($"            writer.WriteByte({(byte)c.Scope});");
            sb.AppendLine($"            writer.WriteBool({(c.Lazy ? "true" : "false")});");
        }

        sb.AppendLine("    }");
    }

    internal static PropertyDataKind ResolveTopLevelKind(PropertyDefModel prop)
    {
        // Containers: TypeRef.Kind; scalars: legacy DefTypeHelper mapping
        // so RegisterType reading [u8 kind] for scalars stays wire-compatible.
        if (prop.TypeRef is not null) return prop.TypeRef.Kind;

        // kCustom here = legitimate scalar "custom" — DefTypeExprParser would
        // have promoted any unknown name to kStruct with TypeRef set.
        return (PropertyDataKind)DefTypeHelper.DataTypeId(prop.Type);
    }

    internal static bool IsContainer(PropertyDataKind kind) =>
        kind == PropertyDataKind.List ||
        kind == PropertyDataKind.Dict ||
        kind == PropertyDataKind.Struct;

    // Kind-specific tail only; callers needing a self-describing ref wrap
    // with EmitDataTypeRef.
    internal static void EmitDataTypeRefBody(StringBuilder sb, DataTypeRefModel t)
    {
        switch (t.Kind)
        {
            case PropertyDataKind.List:
                EmitDataTypeRef(sb, t.Elem!);
                break;
            case PropertyDataKind.Dict:
                EmitDataTypeRef(sb, t.Key!);
                EmitDataTypeRef(sb, t.Elem!);
                break;
            case PropertyDataKind.Struct:
                sb.AppendLine($"            writer.WriteUInt16((ushort){t.StructId});");
                break;
            default:
                // Scalars have no tail; reaching here means a caller bug.
                break;
        }
    }

    internal static void EmitDataTypeRef(StringBuilder sb, DataTypeRefModel t)
    {
        sb.AppendLine($"            writer.WriteByte({(byte)t.Kind});");
        if (IsContainer(t.Kind)) EmitDataTypeRefBody(sb, t);
    }
}
