using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Atlas.Generators.Def.Emitters;

/// <summary>
/// Generates DefEntityTypeRegistry.RegisterAll() that serializes entity type descriptors
/// (including RPC descriptors with ExposedScope) and calls NativeApi.RegisterEntityType()
/// to populate the C++ EntityDefRegistry at startup.
/// </summary>
internal static class TypeRegistryEmitter
{
    public static string Emit(
        List<(EntityDefModel Def, string ClassName, string Namespace)> entities,
        Dictionary<string, ushort> typeIndexMap,
        ProcessContext ctx)
    {
        // Sort by type name for deterministic type_id assignment
        var sorted = entities.OrderBy(e => e.Def.Name).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Atlas.Generators.Def/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Atlas.Serialization;");

        // No process-specific using needed; calls are fully qualified

        sb.AppendLine();
        sb.AppendLine("namespace Atlas.Def;");
        sb.AppendLine();
        sb.AppendLine("internal static class DefEntityTypeRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void RegisterAll()");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        foreach (var (def, className, ns) in sorted)
        {
            if (!typeIndexMap.TryGetValue(def.Name, out var typeId))
                continue;
            sb.AppendLine($"            Register_{def.Name}({typeId});");
        }
        sb.AppendLine("        }");
        sb.AppendLine("        catch (System.DllNotFoundException) { }");
        sb.AppendLine("        catch (System.InvalidOperationException) { }");
        sb.AppendLine("    }");

        foreach (var (def, className, ns) in sorted)
        {
            if (!typeIndexMap.TryGetValue(def.Name, out var typeId))
                continue;
            sb.AppendLine();
            EmitRegisterMethod(sb, def, typeId, typeIndexMap, ctx);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitRegisterMethod(StringBuilder sb, EntityDefModel def, ushort typeId,
        Dictionary<string, ushort> typeIndexMap, ProcessContext ctx)
    {
        sb.AppendLine($"    private static void Register_{def.Name}(ushort typeId)");
        sb.AppendLine("    {");
        sb.AppendLine("        var writer = new SpanWriter(1024);");
        sb.AppendLine("        try");
        sb.AppendLine("        {");

        // Type header
        sb.AppendLine($"            writer.WriteString(\"{def.Name}\");");
        sb.AppendLine("            writer.WriteUInt16(typeId);");
        sb.AppendLine($"            writer.WriteBool({(def.HasCell ? "true" : "false")});");
        sb.AppendLine($"            writer.WriteBool({(def.HasClient ? "true" : "false")});");

        // Properties. ATLAS_DEF008 reserved-position properties are skipped
        // so the C++ registry's property index matches the generated C#
        // field layout — both sides iterate the filtered list.
        var effectiveProps = def.Properties.Where(p => !p.IsReservedPosition).ToList();
        sb.AppendLine($"            writer.WritePackedUInt32({(uint)effectiveProps.Count});");
        for (int i = 0; i < effectiveProps.Count; i++)
        {
            var prop = effectiveProps[i];
            sb.AppendLine($"            writer.WriteString(\"{prop.Name}\");");
            sb.AppendLine($"            writer.WriteByte({DefTypeHelper.DataTypeId(prop.Type)});");
            sb.AppendLine($"            writer.WriteByte({(byte)prop.Scope});");
            sb.AppendLine($"            writer.WriteBool({(prop.Persistent ? "true" : "false")});");
            sb.AppendLine($"            writer.WriteByte(5);");  // detail_level default
            sb.AppendLine($"            writer.WriteUInt16({(ushort)i});");
            sb.AppendLine($"            writer.WriteBool(false);");  // identifier (not parsed from .def yet)
            sb.AppendLine($"            writer.WriteBool({(prop.Reliable ? "true" : "false")});");
        }

        // RPCs — collect ALL methods from all sections
        var allRpcs = new List<(MethodDefModel Method, string Section, byte Direction)>();
        foreach (var m in def.ClientMethods.OrderBy(m => m.Name))
            allRpcs.Add((m, "client_methods", 0x00));
        foreach (var m in def.CellMethods.OrderBy(m => m.Name))
            allRpcs.Add((m, "cell_methods", 0x02));
        foreach (var m in def.BaseMethods.OrderBy(m => m.Name))
            allRpcs.Add((m, "base_methods", 0x03));

        sb.AppendLine($"            writer.WritePackedUInt32({(uint)allRpcs.Count});");

        foreach (var (method, section, direction) in allRpcs)
        {
            // Compute RPC ID (must match RpcIdEmitter)
            var methodsInSection = section switch
            {
                "client_methods" => def.ClientMethods.OrderBy(m => m.Name).ToList(),
                "cell_methods" => def.CellMethods.OrderBy(m => m.Name).ToList(),
                "base_methods" => def.BaseMethods.OrderBy(m => m.Name).ToList(),
                _ => new List<MethodDefModel>(),
            };
            int methodIndex = methodsInSection.FindIndex(m => m.Name == method.Name) + 1;
            int rpcId = (direction << 22) | (typeId << 8) | methodIndex;

            // name (string)
            sb.AppendLine($"            writer.WriteString(\"{method.Name}\");");
            // rpc_id (packed uint32)
            sb.AppendLine($"            writer.WritePackedUInt32(0x{rpcId:X6});");
            // param_count (packed uint32)
            sb.AppendLine($"            writer.WritePackedUInt32({(uint)method.Args.Count});");
            // param types (uint8 each)
            foreach (var arg in method.Args)
            {
                sb.AppendLine($"            writer.WriteByte({DefTypeHelper.DataTypeId(arg.Type)});");
            }
            // ExposedScope (uint8)
            sb.AppendLine($"            writer.WriteByte({(byte)method.Exposed});");
        }

        // Compression — default none for now
        sb.AppendLine("            writer.WriteByte(0);");
        sb.AppendLine("            writer.WriteByte(0);");

        sb.AppendLine();

        // Call NativeApi via the public bridge
        if (ctx == ProcessContext.Client)
            sb.AppendLine("            Atlas.Client.ClientEntityRegistryBridge.RegisterEntityType(writer.WrittenSpan);");
        else
            sb.AppendLine("            Atlas.Core.EntityRegistryBridge.RegisterEntityType(writer.WrittenSpan);");

        sb.AppendLine("        }");
        sb.AppendLine("        finally");
        sb.AppendLine("        {");
        sb.AppendLine("            writer.Dispose();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }
}
