using System;
using System.Collections.Generic;
using System.IO;
using Atlas.Generators.Def;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Atlas.Tools.CppEmitter;

public static class Program
{
    public static int Main(string[] args)
    {
        string? entityDefsDir = null;
        string? outputDir = null;
        string @namespace = "atlas::mvp";

        for (int i = 0; i < args.Length; ++i)
        {
            var arg = args[i];
            switch (arg)
            {
                case "--entity-defs":
                {
                    if (!TryReadValue(args, ref i, arg, out var v)) return 1;
                    entityDefsDir = v; break;
                }
                case "--output":
                {
                    if (!TryReadValue(args, ref i, arg, out var v)) return 1;
                    outputDir = v; break;
                }
                case "--namespace":
                {
                    if (!TryReadValue(args, ref i, arg, out var v)) return 1;
                    @namespace = v; break;
                }
                case "-h":
                case "--help":
                    PrintUsage(); return 0;
                default:
                    Console.Error.WriteLine($"CppEmitter: unknown argument '{arg}'");
                    PrintUsage();
                    return 1;
            }
        }

        if (entityDefsDir is null || outputDir is null)
        {
            PrintUsage();
            return 1;
        }

        var entityDefsPath = Path.GetFullPath(entityDefsDir);
        var outputPath = Path.GetFullPath(outputDir);

        if (!Directory.Exists(entityDefsPath))
        {
            Console.Error.WriteLine($"CppEmitter: --entity-defs '{entityDefsPath}' is not a directory");
            return 2;
        }
        Directory.CreateDirectory(outputPath);

        var manifestPath = Path.Combine(entityDefsPath, EntityIdManifestParser.FileName);
        if (!File.Exists(manifestPath))
        {
            Console.Error.WriteLine($"CppEmitter: missing {EntityIdManifestParser.FileName} in {entityDefsPath}");
            return 3;
        }

        var diagnostics = new List<Diagnostic>();
        void Report(Diagnostic d) => diagnostics.Add(d);

        var manifest = EntityIdManifestParser.Parse(File.ReadAllText(manifestPath), manifestPath, Report);
        if (manifest is null)
        {
            FlushDiagnostics(diagnostics);
            Console.Error.WriteLine("CppEmitter: failed to parse entity_ids.xml");
            return 4;
        }

        var entities = new List<EntityDefModel>();
        var standaloneComponents = new List<ComponentDefModel>();
        foreach (var defPath in Directory.EnumerateFiles(entityDefsPath, "*.def"))
        {
            var text = SourceText.From(File.ReadAllText(defPath));
            var parsed = DefParser.ParseAny(text, defPath, Report);
            if (parsed?.Entity is not null) entities.Add(parsed.Entity);
            if (parsed?.StandaloneComponent is not null) standaloneComponents.Add(parsed.StandaloneComponent);
        }

        var linked = DefLinker.Link(entities, standaloneComponents, Report);
        FlushDiagnostics(diagnostics);
        if (linked is null)
        {
            Console.Error.WriteLine("CppEmitter: DefLinker failed");
            return 5;
        }

        int emitted = 0;
        foreach (var entity in linked.Entities)
        {
            if (!manifest.ActiveByName.TryGetValue(entity.Name, out var typeId))
            {
                Console.Error.WriteLine($"CppEmitter: entity '{entity.Name}' has no active id in entity_ids.xml — skipping");
                continue;
            }
            EmitPlaceholder(outputPath, @namespace, entity.Name, typeId);
            ++emitted;
        }

        Console.WriteLine($"CppEmitter: emitted {emitted}/{linked.Entities.Count} entity placeholders to {outputPath}");
        return 0;
    }

    private static void EmitPlaceholder(string outputDir, string @namespace, string entityName, ushort typeId)
    {
        var className = "F" + entityName;
        var headerName = $"{entityName}.gen.h";
        var implName = $"{entityName}.gen.cc";

        var header = $@"// Auto-generated by Atlas.Tools.CppEmitter — do not edit.
#pragma once

#include ""AtlasCore/client_entity.h""

namespace {@namespace} {{

class {className} : public atlas::ClientEntity {{
 public:
  static constexpr atlas::EntityTypeId kTypeId = {typeId};
  explicit {className}(atlas::EntityId id) : atlas::ClientEntity(id, kTypeId) {{}}
}};

}}  // namespace {@namespace}
";
        var impl = $@"// Auto-generated by Atlas.Tools.CppEmitter — do not edit.
#include ""{headerName}""
";
        File.WriteAllText(Path.Combine(outputDir, headerName), header);
        File.WriteAllText(Path.Combine(outputDir, implName), impl);
    }

    private static void FlushDiagnostics(List<Diagnostic> ds)
    {
        foreach (var d in ds)
        {
            Console.Error.WriteLine(d.ToString());
        }
        ds.Clear();
    }

    private static bool TryReadValue(string[] args, ref int i, string flag, out string value)
    {
        if (i + 1 >= args.Length)
        {
            Console.Error.WriteLine($"CppEmitter: {flag} requires a value");
            value = string.Empty;
            return false;
        }
        value = args[++i];
        return true;
    }

    private static void PrintUsage()
    {
        Console.WriteLine("Usage: Atlas.Tools.CppEmitter --entity-defs <dir> --output <dir> [--namespace <ns>]");
        Console.WriteLine("  --entity-defs DIR    Directory containing *.def + entity_ids.xml");
        Console.WriteLine("  --output DIR         Output directory for .gen.h / .gen.cc files");
        Console.WriteLine("  --namespace NS       C++ namespace for emitted classes (default: atlas::mvp)");
        Console.WriteLine("  --help, -h           Show this message");
    }
}
