<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(AtlasTargetFramework)</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Atlas.Mvp.Cell</RootNamespace>
    <AssemblyName>Atlas.Mvp.Cell</AssemblyName>
    <DefineConstants>ATLAS_CELL</DefineConstants>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\csharp\Atlas.Runtime\Atlas.Runtime.csproj" />
    <ProjectReference Include="..\..\..\src\csharp\Atlas.Generators.Def\Atlas.Generators.Def.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\..\..\entity_defs\entity_ids.xml" />
    <AdditionalFiles Include="..\..\..\entity_defs\component_ids.xml" />
    <AdditionalFiles Include="..\..\..\entity_defs\Account.def" />
    <AdditionalFiles Include="..\..\..\entity_defs\Avatar.def" />
    <AdditionalFiles Include="..\..\..\entity_defs\Npc.def" />
    <AdditionalFiles Include="..\..\..\entity_defs\MvpSpace.def" />
    <AdditionalFiles Include="..\..\..\entity_defs\space_data.def" />
  </ItemGroup>

</Project>
